### ISSUE TITLE
potential memory leak [1 of 40] USB transfer buffers will be disposed during shutdown

### ISSUE THREAD

**Issue by vishalmalli** [DSheirer/sdrtrunk#1008]
Hello,

First I want to say thank you for providing this awesome tool. I am scanning a simulcast P25 Phase 1 system in my area, and the audio quality is great!

I am running sdrtrunk 0.4.0 on a headless machine with dual core AMD 3.0 GHz APU, 8GB memory, Windows 10. This machine is dedicated to SDR purposes only.

Overall the program has performed smoothly, however, today I RDPed into the machine to check on something and noticed high memory usage. I figure that it is normal for memory use to accumulate over time. I have the JVM options set to 5GB max heap size in the batch file.

My reason for posting this is because I did notice this warning message in the console:
`WARN  i.g.d.s.t.u.USBTransferProcessor - [R820T 00000001] - potential memory leak [1 of 40] USB transfer buffers will be disposed during shutdown  [4GB/5GB 85%]`

I did some searches of these terms but didn't find anything, so I'm hoping someone can help me make sense of what this means? Do I have a bad SDR dongle? I am using 2 RTL-SDR v.3 dongles. They both have the WinUSB drivers.

Thanks!

**Comment by DSheirer** [comment]
Closing.  Resolved under recent changes.
