### ISSUE TITLE
NO SOURD

### ISSUE THREAD

**Issue by gaspar1987** [DSheirer/sdrtrunk#1010]
![image](https://user-images.githubusercontent.com/13591469/101899471-2b325800-3bae-11eb-8549-b9efa68d164f.png)

**Comment by gaspar1987** [comment]
Bonjour monsieur je voudrais savoir comment ça se fait que je n'ai pas de son sur mon décrypteur je suis sur windows je n'arrive pas à décrypter avec votre logiciel sdrtunk merci de me donner la réponse pour que je puisse réparer où mettre des paramètres qu'il manque dans votre logiciel expliquez-moi le avec une photo ou quelque chose qui pourrait me montrer comment on peut utiliser sans que je puisse avoir des erreurs quand je le manipule le logiciel est très bien constituer mais je n'arrive pas à mettre en route le son de l'appareil en lecteur play.

**Comment by trengking** [comment]
it is easier for others if you would spend a little more time to translate it in english.

**Comment by gaspar1987** [comment]
Hello, sir, I used your software there is a problem, I can not listen to the sound of the dr

**Comment by gaspar1987** [comment]
Hello sir, I can't see the DR ds that works on audio mode

**Comment by gaspar1987** [comment]
Hello I would like to know how you do to program the library to have the sound DMR thanks for giving me to create the library I do not understand how to program it you can give me a tip with photos or a better instructions because I do not understand how it is made
![image](https://user-images.githubusercontent.com/13591469/102690343-09b41a80-4205-11eb-8047-4e7aac8a6b4a.png)

**Comment by LordDonkey** [comment]
You have no JMBE library set. Click on "Create Library." It will automatically download and compile the latest JMBE library.


https://user-images.githubusercontent.com/52051804/102694219-a2d73700-41ed-11eb-9be6-1c6b94935a30.mp4

**Comment by gaspar1987** [comment]
[](

**Comment by gaspar1987** [comment]
IMG_20201219_173955_8.jpg -->

**Comment by gaspar1987** [comment]
Hello, sir, you're using this with the internet because it doesn't work. I tested it and it doesn't do the same thing you reproduced on the video

**Comment by gaspar1987** [comment]
Hello, I would like you to contact him to put the bookstore on it, because I don't and

**Comment by gaspar1987** [comment]
Hello, sir, explain to me how we can get the sound with

**Comment by gaspar1987** [comment]
Good morning.
I've set up.
Your software, but it doesn't work. I don't have the.
His.
Can you give me any indications that allows?
From.
Have the audio by showing me how it can be installed? Already because I have problems, the sound does not work. I created the library, it doesn't work.

**Comment by gaspar1987** [comment]
Good morning.
I've set up.
Your software, but it doesn't work. I don't have the.
His.
Can you give me any indications that allows?
From.
Have the audio by showing me how it can be installed? Already because I have problems, the sound does not work. I created the library, it doesn't work.

**Comment by gaspar1987** [comment]
Good morning.
I've set up.
Your software, but it doesn't work. I don't have the.
His.
Can you give me any indications that allows?
From.
Have the audio by showing me how it can be installed? Already because I have problems, the sound does not work. I created the library, it doesn't work.
