### ISSUE TITLE
NO INSTALL

### ISSUE THREAD

**Issue by gaspar1987** [DSheirer/sdrtrunk#1020]
Good morning.
I've set up.
Your software, but it doesn't work. I don't have the.
His.
Can you give me any indications that allows?
From.
Have the audio by showing me how it can be installed? Already because I have problems, the sound does not work. I created the library, it doesn't work.

**Comment by DSheirer** [comment]
@gaspar1987 GitHub Issues is used to report bugs in the software. 

You are asking a user support question.  Please email user support questions to the support group: https://groups.google.com/g/sdrtrunk
