### ISSUE TITLE
Feature Request: Record All Unknown Alias

### ISSUE THREAD

**Issue by jamren01** [DSheirer/sdrtrunk#1024]
Looking for the ability to record audio of P25 trunking talkgroups that currently do not have an alias. This would assist in documenting unknown talkgroups.

**Comment by GTR8000** [comment]
Create a new alias named Unknown. Assign a talkgroup range of 1-65535.

**Comment by trengking** [comment]
> Create a new alias named Unknown. Assign a talkgroup range of 1-65535.

TRUE. 
Currently using this trick to sweep (and also) record new TGID to be monitored.

Analyze the 'Unknown' recorded TGIDs for further info and also make new aliases based on those recordings.
