### ISSUE TITLE
Add Gradle Build Support for Mac OSX AARCH64

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#1026]

**Comment by DSheirer** [comment]
Experimental sdrtrunk build for OSX aarch-64 is build and added to the releases tab for end-user testing.

**Comment by awipslinuxuser** [comment]
i got a issue with connecting to radio reference

**Comment by rkcheung** [comment]
Tried to use this build, but got this error loading java:

<img width="896" alt="Screen Shot 2021-02-19 at 9 11 29 PM" src="https://user-images.githubusercontent.com/19496882/108584556-2e0ca000-72f7-11eb-9ef3-568f20a5d027.png">

**Comment by DSheirer** [comment]
Support added under separate issue.
