### ISSUE TITLE
Add Support for OpenMHZ

### ISSUE THREAD

**Issue by Pcpro745** [DSheirer/sdrtrunk#1027]
Not sure if this is possible but can you add support for uploading to OpenMHZ?

**Comment by ImagoTrigger** [comment]
is there any documentation for this or is it in trunk-recorder somewhere?

**Comment by Pcpro745** [comment]
its in Trunk Recorder

**Comment by Pcpro745** [comment]
Bumping this again

**Comment by theficus** [comment]
Adding a +1 to this. Right now I have to use a gnarly combination of running a Hyper-V Linux VM running trunk-recorder and proxying my RTL-SDRs via usbip so I can upload to both Broadcastify and OpenMHz simultaneously. Being able to do this through SDRTrunk would save a lot of layers of complexity and frustration in my setup.

**Comment by tadscottsmith** [comment]
@DSheirer are you open to an OpenMHz broadcaster? I could tackle that.

**Comment by DSheirer** [comment]
Sure!

**Comment by Ctpolicelive** [comment]
Working perfect. Great feature. Thanks.

**Comment by jmp367** [comment]
When using 0.6.0 to feed OpenMHz, the feed periodically becomes disconnected and will not reconnect to OpenMHz automatically. SDRTrunk shows "Error" for the OpenMHz connection status when this occurs and there are no messages related to this issue in the log file.

**Comment by DSheirer** [comment]
@jmp367 this issue should have been closed because the scope for this issue was to implement the original feature.  If there's a bug in the current implementation that you're reporting, please open a new issue.
