### ISSUE TITLE
WACM and System values include letters

### ISSUE THREAD

**Issue by Ambassador7** [DSheirer/sdrtrunk#1030]
Thank you for this really cool software! I can't seem to enter the correct WACN and System values for Phase II. It allows me to type numbers in the box, but not letters. Sorry, I'm new to this. Is it possible to type letters? 

Also, I don't see NAC on my county radio reference page. Is there a default value that I should use for that?

**Comment by DSheirer** [comment]
For phase 2 systems, you can monitor the control channel which is phase 1 and it will auto configure the wacn nac and sysid values for you.

When the wacn has letters it is in hexadecimal format. Convert it to decimal format for all numbers.
