### ISSUE TITLE
Call events log is missing a quote character, outputting malformed csv

### ISSUE THREAD

**Issue by profporridge** [DSheirer/sdrtrunk#1038]
When I enable logging of a DMR system's call events the resulting file is missing a quote character, which makes parsing the log difficult. Sample attached. The issue seems to be in the 'Timeslot' column. 
[20210204_191244.813_0_Hz_Control_call_events.log](https://github.com/DSheirer/sdrtrunk/files/5937912/20210204_191244.813_0_Hz_Control_call_events.log)

This is on 0.5.0 alpha 06

**Comment by ge0metrix** [comment]
I think this line :

https://github.com/DSheirer/sdrtrunk/blob/75ef3217ac12d380d3622bf1b9fcf2c1d627ebea/src/main/java/io/github/dsheirer/module/log/DecodeEventLogger.java#L150 

is missing a `.append("\"")` 

I'd file a PR for it, but I'm not a java dev and dont have an environment to build and test with.
