### ISSUE TITLE
Suggestion: Add Ability to Completely Delete/Edit Alias List

### ISSUE THREAD

**Issue by wa3riz** [DSheirer/sdrtrunk#1060]
After deleting all the individual aliases from an Alias List the remove list name itself.
-or-
Beside the "New Alias List" button add a button "Delete Alias List" and another to "Edit Alias List Name".

In the process of learning how to configure the alias lists, I've created a list names which I no longer need or would like to Edit.

**Comment by Brad-git-man** [comment]
I 2nd the motion on a delete Aliases List button, an "Edit Aliases List" button would also be great, that would pop up your Aliases  List in Notepad.
