### ISSUE TITLE
DMR Motorola Connect Plus - System and Site do not decode

### ISSUE THREAD

**Issue by balleman** [DSheirer/sdrtrunk#1063]
I am decoding the [MADRN](https://www.radioreference.com/apps/db/?sid=5621) with SDRTrunk but it does not display the site and system information.  I have the following messages when decoding:
`20210518 201721,PASSED,CC:9 CON+ NEIGHBORS:1,7,43,57,31 UNK:000008
20210518 201721,PASSED,SLC UNKNOWN OPCODE:10 MSG:A08D0908E`

It appears that the `SLC UNKNOWN OPCODE:10` message is something that should be decoded by `ConnectPlusControlChannel` class.  In debugging this, it is decoding the vendor to be `HYTERA` which is causing `ShortLCMessage.getOpcode` to return `SHORT_STANDARD_UNKNOWN` instead of `SHORT_CONNECT_PLUS_CONTROL_CHANNEL`.  If I change this opcode from `Vendor.Standard` to `Vendor.HYTERA_8` it seems to decode successfully.

The vendor is determined by looking at bit 1 of the message which is set, and then by reading bits 4-11 as the vendor ID. I'm wondering if this is correct for this message, because bits 4-11 appear to be read as part of the system ID by `ConnectPlusControlChannel`.  Or maybe that is correct, and this is a Hytera system that is not yet supported?

**Comment by DSheirer** [comment]
Closing.  OBE?
