### ISSUE TITLE
SdrTrunk v0.5.0-alpha5--- Is there a way to repeat the events in the event list. I'd like to replay the events.

### ISSUE THREAD

**Issue by garamus** [DSheirer/sdrtrunk#1068]
SdrTrunk v0.5.0-alpha5--- Is there a way to repeat the events in the event list. I'd like to replay the events.
![Untitled](https://user-images.githubusercontent.com/50639317/120374408-20e05380-c2df-11eb-90af-576d6bc37ca9.png)
Would be nice to have a replay button on the event list. Is there a way to do this now without scrolling thru the recordings?

**Comment by GTR8000** [comment]
Install Trunking Recorder and use that for audio archiving/playback.

**Comment by infecticide** [comment]
Trunking Recorder is only available for Windows.  Is there a Linux compatible solution?

**Comment by garamus** [comment]
Trunking Recorder works like a charm. Thanks
