### ISSUE TITLE
sdrtrunk should not create directories in the home root

### ISSUE THREAD

**Issue by fjl82** [DSheirer/sdrtrunk#1093]
After starting up sdrtrunk (on Fedora 34), it creates a directory 'SDRtrunk' in the root of my home directory. I'm trying to get it to store it elsewhere, but so far no luck. The only thing I managed to do is move most of the directories out of the way (using the settings in the application, and 'root.directory' in SDRtrunk.properties), but this is kinda pointless if the main directory remains. How do I do this? Would I have to recompile sdrtrunk myself or is there a setting I haven't found yet? And can you update the code to not store its files in the home root by default? This is annoying and generally considered bad practise for software.

**Comment by fjl82** [comment]
After an hour or so of tinkerng, I found a hack that worked. For anyone else who's annoyed with an unwanted directory in his home root, here's my solution. Add "-Duser.home=$HOME/.local/share" (or whatever other directory you want) to the last line of the script. It should read:
```
exec "$JAVACMD" -Duser.home=$HOME/.local/share "$@"
```
This tells java to use an alternative home directory, which sdrtrunk will use as base. It'll create $HOME/.local/share/SDRTrunk instead. I think it's kinda ugly (it's a misuse of settings meant for a different purpose), but it works.

Feel free to close this ticket if you think creating non-hidden directories in the homedir is somehow acceptable, but I'll leave it open in case you may consider changing this.

**Comment by DSheirer** [comment]
Closing - reassign as sub-task under #1348
