### ISSUE TITLE
DMR MBE Audio Frame Recorder - Inconsistent Identifiers

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#1110]
Update the DMR MBE recorder to better capture TO/FROM identifiers.

Consider monitoring the Terminator messages for identifiers, instead of closing out the recording at the first terminator.

**Comment by davidbelle** [comment]
Thanks Denny

Just some further testing I ran from my previous email. It is unrelated to adding extra recording / logging, unlike what I thought initially . More testing shows that it is completely random.
