### ISSUE TITLE
Any way to feed audio/data from the GRE based Phase I scanners into SDRT to decode Phase II ?

### ISSUE THREAD

**Issue by Brad-git-man** [DSheirer/sdrtrunk#1126]
The GRE based Phase I scanners were made under several diff brands & model numbers, but are all the same radio and they include the WS1065, PSR600, Pro197 & Pro652. They can output P25 data from their PC/IF port. I don't know if the output data could be used or if you would need discriminator tap audio. With the proliferation of Phase II all over the country, it would be nice to be able to use these phase I scanners as a source for SDRT, So that you could hear Phase II. The scanners I am talking about look like the pic.

Do you think it is possible @DSheirer 
![Tiny on air flow stand](https://user-images.githubusercontent.com/56703559/147805385-352d11f6-dee2-4f96-9ddc-982ed8efae82.jpg)
?

**Comment by DSheirer** [comment]
It would be possible, but I don't have one of these scanners, so that would make it a challenge for me to add support.
