### ISSUE TITLE
PR #1129 breaks NBFM

### ISSUE THREAD

**Issue by ge0metrix** [DSheirer/sdrtrunk#1133]
After building the latest version of the code, NBFM no longer functions with the following:
`Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: FM Demodulator with channel bandwidth [12500.0] requires a channel sample rate of [25000.0] - sample rate of [12631.578947368422] is not supported`

Not sure where it's getting the original sample rate to attempt to compare with, as I have the tuners rate set to 2.560MHz, and cannot find a location for setting the channel sample rate. 

#1129

**Comment by DSheirer** [comment]
Resolved with PR #1134
