### ISSUE TITLE
[Feature] NBFM Squelch Tail

### ISSUE THREAD

**Issue by ghoward02** [DSheirer/sdrtrunk#1136]
Currently with the lack of tone (CTCSS/DCS) support there tends to be a significant squelch tail/crash at the end of NBFM transmissions from certain sources. This makes them undesirable for streaming or archiving.

Would it be possible to have an adjustable trim option for NBFM channels settable in milliseconds? Since sdrtrunk does not stream a transmission until it is written to disk I'm hoping this is a feasible possibility to make NBFM channels much more usable for streaming.

**Comment by DSheirer** [comment]
Closing as resolved with the new power-squelch enhancement.
