### ISSUE TITLE
Latest update broken (03/04/2022)

### ISSUE THREAD

**Issue by k8tek** [DSheirer/sdrtrunk#1149]
I tried compiling the update that was released today and it has several issues.

`> Configure project :
Skipping OS Image - Linux ARM 64-bit JDK was not found at /home/denny/java_jdks/linux-arm64/jdk-17.0.2-full
Skipping OS Image - Linux x86 64-bit JDK was not found at /home/denny/java_jdks/linux-x64/jdk-17.0.2-full
Skipping OS Image - OSX x86 64-bit JDK was not found at /home/denny/java_jdks/osx-x64/jdk-17.0.2-full.jdk
Skipping OS Image - Windows x86 64-bit JDK was not found at /home/denny/java_jdks/windows-x64/jdk-17.0.2-full

> Task :compileJava
warning: using incubating module(s): jdk.incubator.vector
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\action\AliasAction.java:30: error: package javafx.beans does not exist
import javafx.beans.Observable;
                   ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\action\AliasAction.java:31: error: package javafx.beans.property does not exist
import javafx.beans.property.SimpleStringProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\action\AliasAction.java:32: error: package javafx.util does not exist
import javafx.util.Callback;
                  ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\action\AliasAction.java:47: error: cannot find symbol
    private SimpleStringProperty mValueProperty = new SimpleStringProperty();
            ^
  symbol:   class SimpleStringProperty
  location: class AliasAction
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\action\AliasAction.java:57: error: cannot find symbol
    public SimpleStringProperty valueProperty()
           ^
  symbol:   class SimpleStringProperty
  location: class AliasAction
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:33: error: package javafx.beans does not exist
import javafx.beans.Observable;
                   ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:34: error: package javafx.beans.binding does not exist
import javafx.beans.binding.Bindings;
                           ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:35: error: package javafx.beans.binding does not exist
import javafx.beans.binding.BooleanBinding;
                           ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:36: error: package javafx.beans.property does not exist
import javafx.beans.property.BooleanProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:37: error: package javafx.beans.property does not exist
import javafx.beans.property.IntegerProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:38: error: package javafx.beans.property does not exist
import javafx.beans.property.SimpleBooleanProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:39: error: package javafx.beans.property does not exist
import javafx.beans.property.SimpleIntegerProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:40: error: package javafx.beans.property does not exist
import javafx.beans.property.SimpleStringProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:41: error: package javafx.beans.property does not exist
import javafx.beans.property.StringProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:42: error: package javafx.collections does not exist
import javafx.collections.FXCollections;
                         ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:43: error: package javafx.collections does not exist
import javafx.collections.ObservableList;
                         ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:44: error: package javafx.collections.transformation does not exist
import javafx.collections.transformation.FilteredList;
                                        ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:45: error: package javafx.util does not exist
import javafx.util.Callback;
                  ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\action\AliasAction.java:93: error: cannot find symbol
    public static Callback<AliasAction,Observable[]> extractor()
                  ^
  symbol:   class Callback
  location: class AliasAction
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\action\AliasAction.java:93: error: cannot find symbol
    public static Callback<AliasAction,Observable[]> extractor()
                                       ^
  symbol:   class Observable
  location: class AliasAction
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:65: error: cannot find symbol
    private BooleanProperty mRecordable = new SimpleBooleanProperty();
            ^
  symbol:   class BooleanProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:66: error: cannot find symbol
    private BooleanProperty mStreamable = new SimpleBooleanProperty();
            ^
  symbol:   class BooleanProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:67: error: cannot find symbol
    private BooleanProperty mOverlap = new SimpleBooleanProperty();
            ^
  symbol:   class BooleanProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:68: error: cannot find symbol
    private IntegerProperty mColor = new SimpleIntegerProperty();
            ^
  symbol:   class IntegerProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:69: error: cannot find symbol
    private IntegerProperty mPriority = new SimpleIntegerProperty(Priority.DEFAULT_PRIORITY);
            ^
  symbol:   class IntegerProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:70: error: cannot find symbol
    private IntegerProperty mNonAudioIdentifierCount = new SimpleIntegerProperty();
            ^
  symbol:   class IntegerProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:71: error: cannot find symbol
    private StringProperty mAliasListName = new SimpleStringProperty();
            ^
  symbol:   class StringProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:72: error: cannot find symbol
    private StringProperty mGroup = new SimpleStringProperty();
            ^
  symbol:   class StringProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:73: error: cannot find symbol
    private StringProperty mIconName = new SimpleStringProperty();
            ^
  symbol:   class StringProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:74: error: cannot find symbol
    private StringProperty mName = new SimpleStringProperty();
            ^
  symbol:   class StringProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:75: error: cannot find symbol
    private ObservableList<AliasID> mAliasIDs = FXCollections.observableArrayList();
            ^
  symbol:   class ObservableList
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\id\AliasID.java:48: error: package javafx.beans does not exist
import javafx.beans.Observable;
                   ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\id\AliasID.java:49: error: package javafx.beans.property does not exist
import javafx.beans.property.BooleanProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\id\AliasID.java:50: error: package javafx.beans.property does not exist
import javafx.beans.property.SimpleBooleanProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\id\AliasID.java:51: error: package javafx.beans.property does not exist
import javafx.beans.property.SimpleStringProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\id\AliasID.java:52: error: package javafx.util does not exist
import javafx.util.Callback;
                  ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:76: error: cannot find symbol
    private ObservableList<AliasAction> mAliasActions = FXCollections.observableArrayList();
            ^
  symbol:   class ObservableList
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:104: error: cannot find symbol
    public IntegerProperty nonAudioIdentifierCountProperty()
           ^
  symbol:   class IntegerProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:113: error: cannot find symbol
    public IntegerProperty priorityProperty()
           ^
  symbol:   class IntegerProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:123: error: cannot find symbol
    public BooleanProperty overlapProperty()
           ^
  symbol:   class BooleanProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:132: error: cannot find symbol
    public BooleanProperty recordableProperty()
           ^
  symbol:   class BooleanProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:141: error: cannot find symbol
    public BooleanProperty streamableProperty()
           ^
  symbol:   class BooleanProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:150: error: cannot find symbol
    public StringProperty aliasListNameProperty()
           ^
  symbol:   class StringProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:159: error: cannot find symbol
    public StringProperty groupProperty()
           ^
  symbol:   class StringProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:169: error: cannot find symbol
    public StringProperty nameProperty()
           ^
  symbol:   class StringProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:178: error: cannot find symbol
    public IntegerProperty colorProperty()
           ^
  symbol:   class IntegerProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:187: error: cannot find symbol
    public StringProperty iconNameProperty()
           ^
  symbol:   class StringProperty
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:196: error: cannot find symbol
    public ObservableList<AliasID> aliasIds()
           ^
  symbol:   class ObservableList
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:205: error: cannot find symbol
    public ObservableList<AliasAction> aliasActions()
           ^
  symbol:   class ObservableList
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:709: error: cannot find symbol
    public static Callback<Alias,Observable[]> extractor()
                  ^
  symbol:   class Callback
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\Alias.java:709: error: cannot find symbol
    public static Callback<Alias,Observable[]> extractor()
                                 ^
  symbol:   class Observable
  location: class Alias
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\id\AliasID.java:80: error: cannot find symbol
    private SimpleStringProperty mValueProperty = new SimpleStringProperty();
            ^
  symbol:   class SimpleStringProperty
  location: class AliasID
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\id\AliasID.java:81: error: cannot find symbol
    private BooleanProperty mOverlapProperty = new SimpleBooleanProperty();
            ^
  symbol:   class BooleanProperty
  location: class AliasID
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\id\AliasID.java:91: error: cannot find symbol
    public SimpleStringProperty valueProperty()
           ^
  symbol:   class SimpleStringProperty
  location: class AliasID
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\id\AliasID.java:100: error: cannot find symbol
    public BooleanProperty overlapProperty()
           ^
  symbol:   class BooleanProperty
  location: class AliasID
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\id\AliasID.java:161: error: cannot find symbol
    public static Callback<AliasID,Observable[]> extractor()
                  ^
  symbol:   class Callback
  location: class AliasID
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\id\AliasID.java:161: error: cannot find symbol
    public static Callback<AliasID,Observable[]> extractor()
                                   ^
  symbol:   class Observable
  location: class AliasID
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\AliasList.java:48: error: package javafx.collections does not exist
import javafx.collections.FXCollections;
                         ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\AliasList.java:49: error: package javafx.collections does not exist
import javafx.collections.ObservableList;
                         ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\identifier\tone\ToneSequence.java:25: error: package javafx.collections does not exist
import javafx.collections.FXCollections;
                         ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\identifier\tone\ToneSequence.java:26: error: package javafx.collections does not exist
import javafx.collections.ObservableList;
                         ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\AliasList.java:79: error: cannot find symbol
    private ObservableList<Alias> mAliases = FXCollections.observableArrayList(Alias.extractor());
            ^
  symbol:   class ObservableList
  location: class AliasList
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\AliasList.java:95: error: cannot find symbol
    public ObservableList<Alias> aliases()
           ^
  symbol:   class ObservableList
  location: class AliasList
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\identifier\tone\ToneSequence.java:35: error: cannot find symbol
    private ObservableList<Tone> mTones = FXCollections.observableArrayList(Tone.extractor());
            ^
  symbol:   class ObservableList
  location: class ToneSequence
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\identifier\tone\Tone.java:24: error: package javafx.beans does not exist
import javafx.beans.Observable;
                   ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\identifier\tone\Tone.java:25: error: package javafx.beans.property does not exist
import javafx.beans.property.SimpleStringProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\identifier\tone\Tone.java:26: error: package javafx.beans.property does not exist
import javafx.beans.property.StringProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\identifier\tone\Tone.java:27: error: package javafx.util does not exist
import javafx.util.Callback;
                  ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\identifier\tone\ToneSequence.java:66: error: cannot find symbol
    public ObservableList<Tone> tonesProperty()
           ^
  symbol:   class ObservableList
  location: class ToneSequence
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\identifier\tone\Tone.java:36: error: cannot find symbol
    private StringProperty mValueProperty = new SimpleStringProperty();
            ^
  symbol:   class StringProperty
  location: class Tone
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\identifier\tone\Tone.java:73: error: cannot find symbol
    public StringProperty valueProperty()
           ^
  symbol:   class StringProperty
  location: class Tone
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\identifier\tone\Tone.java:157: error: cannot find symbol
    public static Callback<Tone,Observable[]> extractor()
                  ^
  symbol:   class Callback
  location: class Tone
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\identifier\tone\Tone.java:157: error: cannot find symbol
    public static Callback<Tone,Observable[]> extractor()
                                ^
  symbol:   class Observable
  location: class Tone
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\AliasModel.java:29: error: package javafx.collections does not exist
import javafx.collections.FXCollections;
                         ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\AliasModel.java:30: error: package javafx.collections does not exist
import javafx.collections.ListChangeListener;
                         ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\AliasModel.java:31: error: package javafx.collections does not exist
import javafx.collections.ObservableList;
                         ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\AliasModel.java:50: error: cannot find symbol
    private ObservableList<Alias> mAliases = FXCollections.observableArrayList(Alias.extractor());
            ^
  symbol:   class ObservableList
  location: class AliasModel
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\AliasModel.java:51: error: cannot find symbol
    private ObservableList<String> mAliasListNames = FXCollections.observableArrayList();
            ^
  symbol:   class ObservableList
  location: class AliasModel
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\AliasModel.java:60: error: cannot find symbol
    public ObservableList<Alias> aliasList()
           ^
  symbol:   class ObservableList
  location: class AliasModel
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\AliasModel.java:65: error: cannot find symbol
    public ObservableList<String> aliasListNames()
           ^
  symbol:   class ObservableList
  location: class AliasModel
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\AliasModel.java:335: error: cannot find symbol
    public class AliasListChangeListener implements ListChangeListener<Alias>
                                                    ^
  symbol:   class ListChangeListener
  location: class AliasModel
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\AliasModel.java:338: error: package ListChangeListener does not exist
        public void onChanged(ListChangeListener.Change<? extends Alias> change)
                                                ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\id\tone\TonesID.java:26: error: package javafx.collections does not exist
import javafx.collections.ListChangeListener;
                         ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\id\tone\TonesID.java:34: error: cannot find symbol
public class TonesID extends AliasID implements ListChangeListener<Tone>
                                                ^
  symbol: class ListChangeListener
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\alias\id\tone\TonesID.java:146: error: cannot find symbol
    public void onChanged(Change<? extends Tone> c)
                          ^
  symbol:   class Change
  location: class TonesID
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:29: error: package javafx.beans.property does not exist
import javafx.beans.property.BooleanProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:30: error: package javafx.beans.property does not exist
import javafx.beans.property.IntegerProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:31: error: package javafx.beans.property does not exist
import javafx.beans.property.SimpleBooleanProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:32: error: package javafx.beans.property does not exist
import javafx.beans.property.SimpleIntegerProperty;
                            ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:33: error: package javafx.collections does not exist
import javafx.collections.FXCollections;
                         ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:34: error: package javafx.collections does not exist
import javafx.collections.ObservableSet;
                         ^
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:67: error: cannot find symbol
    private BooleanProperty mComplete = new SimpleBooleanProperty(false);
            ^
  symbol:   class BooleanProperty
  location: class AudioSegment
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:68: error: cannot find symbol
    private BooleanProperty mDuplicate = new SimpleBooleanProperty(false);
            ^
  symbol:   class BooleanProperty
  location: class AudioSegment
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:69: error: cannot find symbol
    private BooleanProperty mRecordAudio = new SimpleBooleanProperty(false);
            ^
  symbol:   class BooleanProperty
  location: class AudioSegment
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:70: error: cannot find symbol
    private IntegerProperty mMonitorPriority = new SimpleIntegerProperty(Priority.DEFAULT_PRIORITY);
            ^
  symbol:   class IntegerProperty
  location: class AudioSegment
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:71: error: cannot find symbol
    private ObservableSet<BroadcastChannel> mBroadcastChannels = FXCollections.observableSet(new HashSet<>());
            ^
  symbol:   class ObservableSet
  location: class AudioSegment
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:136: error: cannot find symbol
    public BooleanProperty completeProperty()
           ^
  symbol:   class BooleanProperty
  location: class AudioSegment
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:145: error: cannot find symbol
    public BooleanProperty duplicateProperty()
           ^
  symbol:   class BooleanProperty
  location: class AudioSegment
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:158: error: cannot find symbol
    public ObservableSet<BroadcastChannel> broadcastChannelsProperty()
           ^
  symbol:   class ObservableSet
  location: class AudioSegment
C:\sdrtrunk-master\src\main\java\io\github\dsheirer\audio\AudioSegment.java:186: error: cannot find symbol
    public BooleanProperty recordAudioProperty()
           ^
  symbol:   class BooleanProperty
  location: class AudioSegment`

**Comment by hans109h** [comment]
I had the same issue and Denny reminded me I need Bellsoft Liberica 'Full' JDK or the Azul 'Full' JDK that includes the JavaFX libraries.

Since I already had Bellsoft it reminded me that on my system I needed to set JAVA_HOME to point to the right JDK.

**Comment by k8tek** [comment]
Nevermind, I deleted gradle and it compiled.
