### ISSUE TITLE
Feature Request: Encrypted Audio Placeholder mp3

### ISSUE THREAD

**Issue by hrusakcha** [DSheirer/sdrtrunk#1167]
I think it would be cool if SDRTrunk could generate a blank / empty audio file with metadata for encrypted calls that are detected on the control channel. 
Currently, If I wanted to see encrypted talkgroups, I would have to export logs and import to excel. I just think it would be so much easier if an audio file could be generated with the metadata that other calls have included.

**Comment by DSheirer** [comment]
If you're looking to find the talkgroups that use encrypted audio, you can turn on MBE recording.  The JSON content will tell you the TO/FROM talkgroups and if the call is encrypted.
