### ISSUE TITLE
P25 ISSI Patch Talkgroup Aliasing

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#1188]
P25 (I & II) currently only supports aliasing to the TALKGROUP or RADIOID level.  When a cross-system ISSI patch call is encountered, sdrtrunk attempts to alias the external SYSID radio ID to the local pool of aliased radio ID values, resulting in an alias mismatch.

sdrtrunk already has support for fully qualified RADIOID and TALKGROUP on the identifier side.  Add aliasing support for fully qualified P25 Alias Identifiers that require the user to specify a WACN, SYSID and a RADIOID/TALKGROUP value.

**Comment by DSheirer** [comment]
Note: is there a way to allow users to export existing aliases that are not fully qualified, to another alias list as fully qualified aliases?  This would require the user to specify the WACN and SYSID prefix values.

**Comment by ImagoTrigger** [comment]
possibly allow loading multiple playlist xml files unique to sysid and/or alias group name
