### ISSUE TITLE
[linux] SDRTrunk.properties frequently gets reverted to defaults on startup app launch

### ISSUE THREAD

**Issue by sdr-stack** [DSheirer/sdrtrunk#1200]
When autostart launching app with ~/.config/autostart foo.desktop file the SDRTrunk.properties file will often revert to defaults upon launch. Not seen on manual launch.

**Comment by boteman** [comment]
I've given up trying to set defaults, like window size and position. It has a mind of its own.

Visual Studio seems to use the properties file in the directory from which the executable was invoked, regardless of where the binary lives. It would be nice to have some educated guidance so I can get consistent results.

**Comment by ImagoTrigger** [comment]
i set the file to read only chmod -w or something like that

**Comment by DSheirer** [comment]
Closing - reassign as sub-task under #1348
