### ISSUE TITLE
Hangs while closing, printing problematic frame

### ISSUE THREAD

**Issue by pfbram** [DSheirer/sdrtrunk#1205]
Debian 11 fully patched, OpenJDK 11.0.14 2022-01-18, SDRTrunk 0.5.0 beta 2.  I haven't see the following issues in alpha6, but do see them in beta2.

Seeing this in the terminal window while starting the app:

WARNING: Using incubator modules: jdk.incubator.vector
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop

Sometimes, but not always, SDRTrunk hangs while trying to shut down the program.  Eventually it times out after a couple minutes and finally closes.  It generates an error like this:

A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x00007f5ef0cc186c, pid=2613, tid=2712

JRE version: OpenJDK Runtime Environment (17.0.2+9) (build 17.0.2+9-LTS)
Java VM: OpenJDK 64-Bit Server VM (17.0.2+9-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
Problematic frame:
C  [libc.so.6+0x8686c]
[timeout occurred during error reporting in step "printing problematic frame"] after 30 s.
No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

If you would like to submit a bug report, please visit:
https://bell-sw.com/support

---------------  S U M M A R Y ------------

Command Line: --add-exports=javafx.base/com.sun.javafx.event=ALL-UNNAMED --add-modules=jdk.incubator.vector --add-exports=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED io.github.dsheirer.gui.SDRTrunk

Host: 
[timeout occurred during error reporting in step "printing summary machine and OS info"] after 30 s.
Time: Tue Apr 12 09:45:27 2022 CDT elapsed time: 893.671062 seconds (0d 0h 14m 53s)

---------------  T H R E A D  ---------------

Current thread (0x00007f5e40517e90):  JavaThread "sdrtrunk USB event processor" [_thread_in_vm, id=2712, stack(0x00007f5e04872000,0x00007f5e04973000)]

Stack: [0x00007f5e04872000,0x00007f5e04973000],  sp=0x00007f5e04971a80,  free space=1022k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x8686c]
------ Timeout during error reporting after 120 s. ------

**Comment by DSheirer** [comment]
Thanks for the report.

This issue is being addressed under issue #1190
