### ISSUE TITLE
Tuner Editor NPE

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#1221]
NPE thrown when attempting to restart an error tuner.

**Comment by Brad-git-man** [comment]
Yes, I get that error on SDRT after a few hours, I am running 5 Nooelec SDRs. I have attached a pic of them
![Snapshot_20220411](https://user-images.githubusercontent.com/56703559/165830949-eebed85f-926e-4807-976f-859ea1b75329.JPG)
.
