### ISSUE TITLE
USB Tuners Should Use Port Hierarchy To Identify Correct Tuner

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#1229]
Update tuner manager to use the port lineage to correctly identify the tuner.  LibUsb provides both a method to identify the single port that the tuner is plugged into and it also provides a method to get the root-to-device port lineage for device and any hubs that it is plugged into.  Without including the hub lineage, there can be conflicts with multiple devices showing at the same port number and causing the incorrect USB tuner to be identified.

**Comment by Brad-git-man** [comment]
I was just wondering if there are any daily/weekly or milestone builds to try. To see how the work on the memory leak and the can't play channel prob are coming, that occur after running 0.5.0-beta2 for an hour or two.
