### ISSUE TITLE
Numerous "unable to source channel" messages after 0.5.0-beta3 Gradle 7.4.2 is running

### ISSUE THREAD

**Issue by w8jfj** [DSheirer/sdrtrunk#1264]
System is WIN10 with 32gb memory. 

Running 0.5.0-alpha6 3 gradle 6.3 no issues - very stable. 

Testing 0.5.0-beta3 Gradle 7.4.2 after about 5 minutes of running I get a large number of "unable to source channel" messages. I also notice channel activity without audio when the messages flow. Eventually the waterfall goes into "streak" mode and the messages continue to flow.

I can shutdown Beta and then restart Alpha using the exact same dongle and all is well.

Did I miss a step somewhere? I did a fresh download this morning.

Alpha log - running about 12 minutes:

[Alpha6 Log.txt](https://github.com/DSheirer/sdrtrunk/files/8780784/Alpha6.Log.txt)

Beta Log - running about 5 minutes

[Beta 3 Log.txt](https://github.com/DSheirer/sdrtrunk/files/8780786/Beta.3.Log.txt)

**Comment by DSheirer** [comment]
Beta 3 changed the naming of tuners.  Update the preferred tuner in your channel configurations.  

Note: you ;ll have to change this each time you go from Beta 2 to Beta 3 or vice-versa.
