### ISSUE TITLE
DMR Event Tab UI won't update in real time

### ISSUE THREAD

**Issue by Nokoa** [DSheirer/sdrtrunk#1287]
The event tab for DMR channels will not update in real time while clicked on a channel. Deselecting and reselecting the channel in the currently playing tab will update the events. 

I believe this issue is related to the event tab filtering. It appeared that in the DecodeEventModel.java file for DMR events fall for
`if (!mEventFilterSet.passes(event))`

**Comment by DSheirer** [comment]
Issue resolved with PR #1384 by disabling event filtering until the feature is fully implemented.
