### ISSUE TITLE
Build error - Release v0.5.0-beta.5 - Linux Mint /w gradlew

### ISSUE THREAD

**Issue by jafo2128** [DSheirer/sdrtrunk#1306]
sdrtrunk fails to build with gradlew

[Version 0.5.0 Beta 5](https://github.com/DSheirer/sdrtrunk/releases/tag/v0.5.0-beta.5)

~/apps/sdrtrunk$ ./gradlew clean build

> Configure project :
Building a single runtime image using locally installed JDK

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> error: invalid source release: 17

-------------------------------------
~$ java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

-------------------------------------
Issue appears to be back.   
Is OpenJDK supported?   or does it have to be Oracle java.

**Comment by DSheirer** [comment]
sdrtrunk requires Java version 17 or higher.  You're using Java 11.  Closing.
