### ISSUE TITLE
Crash when tuner connected/disconnected

### ISSUE THREAD

**Issue by cfc62** [DSheirer/sdrtrunk#1307]
This doesn't happen very often, but I did catch one today:

11:07:49.415 INFO  i.g.d.s.t.m.DiscoveredTuner - Stopping Tuner: Airspy USB Bus:2 Port:2  [515MB/594MB 86%]
11:07:49.416 ERROR i.g.d.s.t.u.USBTunerController - Error submitting USB transfer - status [-99] LIBUSB_ERROR_OTHER - previous status [1] and transferred [0]  [515MB/594MB 86%]
11:07:49.416 INFO  i.g.d.s.t.m.DiscoveredTuner - Tuner Error - Stopping - Airspy USB Bus:2 Port:2 Error: Usb I/O Error - Can't submit buffers to tuner - stopping tuner  [515MB/594MB 86%]
11:07:49.416 INFO  i.g.d.s.t.m.DiscoveredTuner - Stopping Tuner: Airspy USB Bus:2 Port:2  [515MB/594MB 86%]
11:07:49.427 INFO  i.g.d.s.t.m.TunerManager - Tuner Unplugged: Airspy USB Bus:2 Port:2  [521MB/594MB 87%]
11:07:49.933 INFO  i.g.d.s.t.m.TunerManager - Tuner plug-in detected at USB Bus [2] Port [2] Tuner Class [Airspy]  [527MB/594MB 88%]
11:07:49.934 INFO  i.g.d.s.t.m.TunerManager - Tuner: USB Tuner - Airspy USB Bus:2 Port:2 - Added / Starting ...  [527MB/594MB 88%]
11:07:49.950 INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [10000000.0] providing [400] channels at [25000.0] Hz each  [527MB/594MB 88%]
11:07:49.952 INFO  i.g.d.s.t.m.TunerManager - Tuner: USB Tuner - Airspy USB Bus:2 Port:2 - Applying Tuner Configuration  [527MB/594MB 88%]
11:07:53.048 ERROR i.g.d.s.t.u.USBTunerController - Error submitting USB transfer - status [-99] LIBUSB_ERROR_OTHER - previous status [1] and transferred [0]  [420MB/594MB 70%]
11:07:53.048 INFO  i.g.d.s.t.m.DiscoveredTuner - Tuner Error - Stopping - Airspy USB Bus:2 Port:2 Error: Usb I/O Error - Can't submit buffers to tuner - stopping tuner  [420MB/594MB 70%]
11:07:53.048 INFO  i.g.d.s.t.m.DiscoveredTuner - Stopping Tuner: Airspy USB Bus:2 Port:2  [420MB/594MB 70%]
11:07:53.048 INFO  i.g.d.s.t.m.DiscoveredTuner - Stopping Tuner: Airspy USB Bus:2 Port:2  [421MB/594MB 70%]
11:07:53.048 INFO  i.g.d.s.t.m.TunerManager - Tuner Unplugged: Airspy USB Bus:2 Port:2  [421MB/594MB 70%]
11:07:53.769 INFO  i.g.d.s.t.m.TunerManager - Tuner plug-in detected at USB Bus [2] Port [2] Tuner Class [Airspy]  [426MB/594MB 71%]
11:07:53.769 INFO  i.g.d.s.t.m.TunerManager - Tuner: USB Tuner - Airspy USB Bus:2 Port:2 - Added / Starting ...  [426MB/594MB 71%]
11:07:53.784 INFO  i.g.d.d.f.c.ComplexPolyphaseChannelizerM2 - Sample Rate [10000000.0] providing [400] channels at [25000.0] Hz each  [426MB/594MB 71%]
11:07:53.785 INFO  i.g.d.s.t.m.TunerManager - Tuner: USB Tuner - Airspy USB Bus:2 Port:2 - Applying Tuner Configuration  [426MB/594MB 71%]
Assertion failed: (pthread_mutex_destroy(mutex) == 0), function usbi_mutex_destroy, file threads_posix.h, line 58.

**Comment by DSheirer** [comment]
Potentially resolved under issue #1827.
