### ISSUE TITLE
154: exec: /home/t/sdr-trunk-v5/bin/java: Exec format error

### ISSUE THREAD

**Issue by oldirty91** [DSheirer/sdrtrunk#1311]
When attempting to use any of the v0.5, I get the following error:

./sdr-trunk: 154: exec: /home/t/sdr-trunk-v5/bin/java: Exec format error

v0.4 works fine. Here is my java -version:

openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

any ideas? Thanks.

**Comment by infecticide** [comment]
This sounds like a corrupt file or possibly a 32-bit / 64-bit mismatch between the Java install and the OS.
