### ISSUE TITLE
[Feature Request] Import/Export Aliases, Channels, Playlists

### ISSUE THREAD

**Issue by ecrist** [DSheirer/sdrtrunk#1314]
I've not found a way to easily export the above, in a format that is easy to manually edit or share with others.  The import option from RR is nice, but I think we could expand on this a bit.

**Comment by DSheirer** [comment]
@ecrist you can make a copy the playlist XML file and send it to another user.  Likewise, if another user sends you a copy of their playlist, simply copy it to the 'sdrtrunk/playlist' folder and then in the Playlist Editor, 'Playlists' tab click the 'Add' button to add the imported playlist to your playlists.
