### ISSUE TITLE
Rafael Micro R828D tuner doesn't work.

### ISSUE THREAD

**Issue by thpryrchn** [DSheirer/sdrtrunk#1315]
What is the story with this tuner? every other RTL SDR app seems to work with it on my mac. The whole reason I ordered it was for police radio scanning. as I had another RTL-SDR tuner that works with SDRTrunk. Is the tuner that different? 

The dongle I got is https://www.ebay.com/itm/254987260147
RTL-SDR Blog RTL SDR V3 R820T2 RTL2832U 1PPM TCXO SMA RTLSDR Software
Obviously a knockoff, otherwise it world work for SDRTrunk.

```
rtl_test 
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R828D tuner
Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6 
[R82XX] PLL not locked!
Sampling at 2048000 S/s.

Info: This tool will continuously read from the device, and report if
samples get lost. If you observe no further output, everything is fine.
```

**Comment by DSheirer** [comment]
R828D tuner is not supported.  I don't have one to test against.
