### ISSUE TITLE
Can't open USB tuner 

### ISSUE THREAD

**Issue by Urminme** [DSheirer/sdrtrunk#1317]
Ive got the app downloaded and it works fine but no matter what I try the program doesn't seem to pick up my driver, it says reinstall drivers, but there is no where on here to download any drivers, it never mentions even downloading drivers. any help?

**Comment by ecrist** [comment]
Have you used zadig to install the WinUSB driver?

**Comment by DSheirer** [comment]
Zadig here: https://www.rtl-sdr.com/tag/zadig/
