### ISSUE TITLE
Analog voice with P25P1 data

### ISSUE THREAD

**Issue by moffa90** [DSheirer/sdrtrunk#1322]
Hey, nice work with this piece of software.

I am trying to decode P25P1 data over analog voice, but i am struggling with that since the P25P1 data is randomly captured. 

I am attaching a wav file with a sample; it should detect 3 packets:

- 1TSBK (starting transmission)
- 1 PDU (ending transmission)
- 1 TSBK (ending transmission)

NBFM - BW 12.5 khz 
Center freq 486 mhz
Channel Freq 486.0125 mhz

I have tried with another fully digital P25P1 signals, and it seems to work properly. Please let me know if this feature is not supported or if there is an issue with the signal i am providing.

Also, i tried doing a quick test with DSD+ and get the 3 packages. The difference i saw is that DSD+ demodules from NFM audio and SDRTrunk from raw IQ.

Thank you, 
[raw-iq.zip](https://github.com/DSheirer/sdrtrunk/files/9749296/raw-iq.zip)

**Comment by DSheirer** [comment]
P25 decode from demodulated FM is not supported.
