### ISSUE TITLE
~/SDRTrunk folder is recreated in any case

### ISSUE THREAD

**Issue by drws** [DSheirer/sdrtrunk#1331]
I've changed all data folders' paths from the default folder `~/SDRTrunk`. However, the folder still gets recreated every startup containing parts of settings. Apparently some smaller parts of code have a hardcoded path.

**Comment by Nokoa** [comment]
I think I have noticed something similar. Some persistent settings are used, which are saved internally somewhere, and not specifically to a file.

**Comment by DSheirer** [comment]
Closing - recreating issue as subtask under #1348
