### ISSUE TITLE
Alias Identifers tooltips for DMR not quite correct

### ISSUE THREAD

**Issue by hockeyref2** [DSheirer/sdrtrunk#1393]
In Playlist Editor ->Aliases->Identifiers..
For talkgroup, talkgroup range and radio range....
DMR tooltips were incorrect (for example showing 0-FFFFFFF when in decimal format, when the program wants 1-16777215. 

In TalkgroupEditor.java  I changed the minimum for DMR to 1 from 0 (lines 242-245)
In TalkgroupRangeEditor.java, I added DMR category with proper tooltips (lines 317-320)
In RadioIdRangeEditor.java, I added DMR category with proper tooltips (lines 303-306)

[updated tg id.zip](https://github.com/DSheirer/sdrtrunk/files/10329421/updated.tg.id.zip)

**Comment by DSheirer** [comment]
@hockeyref2 Thanks very much!  I included logging for when we can't find an editor for the specific protocol/format so that we can catch this oversight earlier in the development process for future protocols.
