### ISSUE TITLE
DMR IDs not decoding correctly

### ISSUE THREAD

**Issue by PhilRW** [DSheirer/sdrtrunk#1422]
This goes for talkgroups and for radio IDs.

For example, a radio ID that transmits with the 24-bit decimal ID `3108128` (binary `0010 1111 0110 1101 0010 0000`) gets decoded as the 16-bit decimal ID `27936` (binary `0110 1101 0010 0000`).

The same goes for talkgroup IDs. Talkgroup `700` (`0000 0010 1011 1100`) gets decoded as `188` (`1011 1100`).

I think perhaps the DMR channel type needs a way to specify what kind of system it is. Conventional DMR systems use 24-bit talkgroups and radio IDs, while Motorola Capacity Plus systems use 8-bit talkgroups and 16-bit radio IDs. I'm not sure about the other types of DMR systems.

**Comment by DSheirer** [comment]
@PhilRW Can you please make a bitstream recording in sdrtrunk of this channel where you're seeing that the DMR identifiers are not being handled correctly?

You may be able to attach it to this issue.  If not, please let me know and I can send you another email address to send it to.

**Comment by PhilRW** [comment]
Okay, I checked 'Demodulated Bitstream', I hope that's right. The TG should be `721` and Radio ID `3108128`, but they are `209` and `27936`, respectively.

[20230120_062645_9600BPS_DMR_RMHam_Eldorado_output_16.zip](https://github.com/DSheirer/sdrtrunk/files/10466860/20230120_062645_9600BPS_DMR_RMHam_Eldorado_output_16.zip)

**Comment by DSheirer** [comment]
On decoding the bitstream recordings that you sent, the system is presenting with a Motorola Capacity Plus vendor ID and transmitting the identifiers using the Motorola capacity plus flavor of full link control messages.  These message types don't follow the DMR standard and support in sdrtrunk can always be enhanced.

Can you provide any details about this system?  Do you know how it's configured?  Is it a single repeater setup?  

What is your confidence level about what you think the correct from/to identifiers should be?  Do you have access to someone that setup the system, or do you have access to a mobile that is authorized on the system?

**Comment by PhilRW** [comment]
I do know there are multiple linked repeaters, I believe using IP Site Connect. I am 100% confident about the decoding of the identifiers, since I have multiple DMR radios decoding the IDs.
