### ISSUE TITLE
Feature Request: Add Record toggle to bulk alias editor

### ISSUE THREAD

**Issue by hockeyref2** [DSheirer/sdrtrunk#1431]
[AliasBulkEditor.zip](https://github.com/DSheirer/sdrtrunk/files/10528417/AliasBulkEditor.zip)
In the Alias bulk editor, you could select/deselect 'listen' but you could not do the same for 'record'
This code adds this feature to the bulk editor.

**Comment by axmeone** [comment]
yes, great request, please add

**Comment by DSheirer** [comment]
Implemented in version 0.6.0
