### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by Allen-colton** [DSheirer/sdrtrunk#1432]
this is the crash dump from my install on kali lunix wasnt shore where to send them so im putting on here 

/home/candc/SDRTrunk/bin/hs_err_pid42701.log
/home/candc/SDRTrunk/bin/hs_err_pid3677.log
[hs_err_pid42701.log](https://github.com/DSheirer/sdrtrunk/files/10528797/hs_err_pid42701.log)
[hs_err_pid3677.log](https://github.com/DSheirer/sdrtrunk/files/10528798/hs_err_pid3677.log)

**Comment by DSheirer** [comment]
Closing.  Please add a comment if this issue is not yet resolved and I'll reopen.

**Comment by Allen-colton** [comment]
It happens randomly i replaced my usb cables and it seems to of helped i
guess it flips it out if it looses connection with my hackrf

Colton King
