### ISSUE TITLE
Version v0.6.0-alpha2 Gradle Build Is Not Creating Valid Releases

### ISSUE THREAD

**Issue by Brad-git-man** [DSheirer/sdrtrunk#1459]
The gradle build script is not producing the correct release versions with recent updates for adding the sdrplay RSP tuner support.

Task: update gradle build to produce correct releases.

------------------------------------------
Original Comments:

How do I fix this fatal error when trying to start v0.6.0-alpha2
![SDRT_v0 6 0-alpha2_fatal_error](https://user-images.githubusercontent.com/56703559/219969286-4d53a181-21e1-4ca7-936f-6fff76d7d7e0.jpg)

@DSheirer

**Comment by uzbek197** [comment]
Такая же ошибка НЕ ЗАПУСКАЕТСЯ ЧТО ДЕЛАТЬ?????

вс, 19 февр. 2023 г. в 22:01, Ulti P. Uzzer ***@***.***>:

**Comment by DSheirer** [comment]
This error means that you're using an older version of Java than what is needed.

Your error indicates that you're trying to run Version 0.6.0-alpha2.  Are you running the published release for that version, using the Java that is bundled with the release, or have you pulled down the source code and you're attempting to run it using a locally installed version of Java?

**Comment by uzbek197** [comment]
Загрузил версию 0.6.0-alpha3 и все заработало СПАСИБО БОЛЬШОЕ Отличная
работа!!!

пн, 20 февр. 2023 г. в 13:12, Denny Sheirer ***@***.***>:

**Comment by uzbek197** [comment]
Привет Всем возник такой вопрос использую
sdr-trunk-windows-x86_64-v0.6.0-beta-5 в папке recordings появился файл
LST_XXX.dat и вот такой вопрос что это за файл и как его можно
посмотреть????
Всем заранее спасибо!!!
