### ISSUE TITLE
Tuner Error - Stopping - RTL-2832 USB Bus:2 Port:2.4 Error: Unsupported/Unrecognized Tuner Type

### ISSUE THREAD

**Issue by renzo-1954** [DSheirer/sdrtrunk#1474]
20230226 105328.506 [main] INFO  i.g.d.log.ApplicationLog - SDRTrunk Version  : 0.5.1-beta1  [11MB/384MB 2%]
20230226 111345.734 [main] INFO  i.g.d.s.t.manager.TunerManager - Discovered tuner at USB Bus [2] Port [2.4] Tuner Class [RTL-2832]  [15MB/56MB 27%]
20230226 111345.735 [main] INFO  i.g.d.s.t.manager.TunerManager - Tuner: USB Tuner - RTL-2832 USB Bus:2 Port:2.4 - Added / Starting ...  [15MB/56MB 27%]
20230226 111346.520 [main] INFO  i.g.d.s.t.m.DiscoveredTuner - Tuner Error - Stopping - RTL-2832 USB Bus:2 Port:2.4 Error: Unsupported/Unrecognized Tuner Type  [17MB/56MB 31%]
20230226 111346.521 [main] INFO  i.g.d.s.t.m.DiscoveredTuner - Stopping Tuner: RTL-2832 USB Bus:2 Port:2.4  [17MB/56MB 31%]
20230226 111346.522 [main] ERROR i.g.d.s.t.m.DiscoveredUSBTuner - Unable to start tuner [RTL-2832] - error: Unsupported/Unrecognized Tuner Type  [17MB/56MB 31%]

running on win10, any help would be greatly appreciated...

**Comment by DSheirer** [comment]
The RTL2832 dongle that you're using has an unsupported tuner chip.  sdrtrunk currently supports the R820T, R820T2, and E4000 tuner chips.

It doesn't support the FC0012 or FC0013 chips.

**Comment by ame1991net** [comment]
Thanks
