### ISSUE TITLE
Nooelec/airspy issue

### ISSUE THREAD

**Issue by dave3825us** [DSheirer/sdrtrunk#1475]
Windows 10 Sdrtrunk alpha 6

Have all beta versions on pc and they work fine running nooelec and airspy mini on 3 systems. Alpha 6, can longer run and record the same 3 systems I have been doing for a year.Detailed thread here
https://groups.google.com/g/sdrtrunk/c/8RcCa2YPYR0/m/5kchTakpAgAJ

Alias set to both listen and record do not produce sound or recorded files.

20230228 181919.533 [main] INFO  i.g.d.log.ApplicationLog - SDRTrunk Version  : 0.6.0-alpha3  [6MB/124MB 5%]
20230228 181919.534 [main] INFO  i.g.d.log.ApplicationLog - Gradle Version    : Gradle 7.6  [6MB/124MB 5%]
20230228 181919.534 [main] INFO  i.g.d.log.ApplicationLog - Build Timestamp   : 2023-02-20T12:11:05.057-0500  [6MB/124MB 5%]
20230228 181919.534 [main] INFO  i.g.d.log.ApplicationLog - Build-JDK         : 19.0.1 (BellSoft 19.0.1+11  [6MB/124MB 5%]
20230228 181919.535 [main] INFO  i.g.d.log.ApplicationLog - Build OS          : Linux (amd64 5.15.0-58-generic  [6MB/124MB 5%]
20230228 181919.537 [main] INFO  i.g.d.log.ApplicationLog -   [6MB/124MB 5%]
20230228 181919.537 [main] INFO  i.g.d.log.ApplicationLog - *******************************************************************  [6MB/124MB 5%]
20230228 181919.538 [main] INFO  i.g.d.log.ApplicationLog - **** sdrtrunk: a trunked radio and digital decoding application ***  [6MB/124MB 5%]
20230228 181919.538 [main] INFO  i.g.d.log.ApplicationLog - ****  website: https://github.com/dsheirer/sdrtrunk             ***  [6MB/124MB 5%]
20230228 181919.538 [main] INFO  i.g.d.log.ApplicationLog - *******************************************************************  [6MB/124MB 5%]
20230228 181919.538 [main] INFO  i.g.d.log.ApplicationLog - Memory Logging Format: [Used/Allocated PercentUsed%]  [6MB/124MB 5%]
20230228 181919.538 [main] INFO  i.g.d.log.ApplicationLog - Host OS Name:          Windows 10  [6MB/124MB 5%]
20230228 181919.539 [main] INFO  i.g.d.log.ApplicationLog - Host OS Arch:          amd64  [6MB/124MB 5%]
20230228 181919.539 [main] INFO  i.g.d.log.ApplicationLog - Host OS Version:       10.0  [6MB/124MB 5%]
20230228 181919.539 [main] INFO  i.g.d.log.ApplicationLog - Host CPU Cores:        8  [6MB/124MB 5%]
20230228 181919.540 [main] INFO  i.g.d.log.ApplicationLog - Host Max Java Memory:  1 GB  [6MB/124MB 5%]
20230228 181919.540 [main] INFO  i.g.d.log.ApplicationLog - Storage Directories:  [6MB/124MB 5%]
20230228 181919.541 [main] INFO  i.g.d.log.ApplicationLog -  Application Root: C:\Users\Preferred Customer\SDRTrunk  [6MB/124MB 5%]
20230228 181919.541 [main] INFO  i.g.d.log.ApplicationLog -  Application Log:  C:\Users\Preferred Customer\SDRTrunk\logs  [6MB/124MB 5%]
20230228 181919.542 [main] INFO  i.g.d.log.ApplicationLog -  Event Log:        C:\Users\Preferred Customer\SDRTrunk\event_logs  [6MB/124MB 5%]
20230228 181919.547 [main] INFO  i.g.d.log.ApplicationLog -  Playlist:         C:\Users\Preferred Customer\SDRTrunk\playlist  [6MB/124MB 5%]
20230228 181919.549 [main] INFO  i.g.d.log.ApplicationLog -  Recordings:       C:\Users\Preferred Customer\SDRTrunk\recordings  [6MB/124MB 5%]
20230228 181919.549 [main] INFO  i.g.dsheirer.util.ThreadPool - Application thread pool created SCHEDULED and CACHED executors threads  [6MB/124MB 5%]
20230228 181919.550 [main] INFO  i.github.dsheirer.gui.SDRTrunk - Home path: C:\Users\Preferred Customer\SDRTrunk  [6MB/124MB 5%]
20230228 181919.551 [main] INFO  i.g.d.p.SystemProperties - SystemProperties - loaded [C:\Users\Preferred Customer\SDRTrunk\SDRTrunk.properties]  [6MB/124MB 5%]
20230228 181919.551 [main] INFO  i.g.d.p.SystemProperties - SystemProperties - application properties loaded [C:\Users\Preferred Customer\SDRTrunk\SDRTrunk.properties]  [6MB/124MB 5%]
20230228 181919.800 [main] INFO  i.g.d.s.t.manager.TunerManager - Discovering tuners ...  [15MB/27MB 57%]
20230228 181919.905 [main] INFO  i.g.d.s.t.manager.TunerManager - LibUsb API Version: 1.0.262  [17MB/27MB 62%]
20230228 181919.906 [main] INFO  i.g.d.s.t.manager.TunerManager - LibUsb Version: 1.0.22.11312  [17MB/27MB 62%]
20230228 181919.935 [main] INFO  i.g.d.s.t.manager.TunerManager - LibUsb - discovered [9] potential usb devices  [17MB/27MB 62%]
20230228 181919.941 [main] INFO  i.g.d.s.t.manager.TunerManager - Discovered tuner at USB Bus [2] Port [11] Tuner Class [RTL-2832]  [17MB/27MB 62%]
20230228 181919.943 [main] INFO  i.g.d.s.t.manager.TunerManager - Discovered tuner at USB Bus [2] Port [7] Tuner Class [Airspy]  [17MB/27MB 62%]
20230228 181919.945 [main] INFO  i.g.d.s.t.manager.TunerManager - Tuner: USB Tuner - RTL-2832 USB Bus:2 Port:11 - Added / Starting ...  [17MB/27MB 64%]
20230228 181921.302 [main] INFO  i.g.d.s.t.manager.TunerManager - Tuner: USB Tuner - Airspy USB Bus:2 Port:7 - Added / Starting ...  [20MB/27MB 76%]
20230228 181921.344 [main] WARN  i.g.d.vector.VectorUtilities - CPU supports maximum SIMD instructions of Species[float, 8, S_256_BIT]  [7MB/27MB 25%]
20230228 181921.403 [main] INFO  i.g.d.s.t.manager.TunerManager - LibUsb Hotplug event notification Is Not Supported on this platform.  [8MB/27MB 29%]
20230228 181921.410 [main] INFO  i.g.d.s.t.sdrplay.api.SDRplay - Loading API Library from default install path: C:\Program Files\SDRplay\API\x64\sdrplay_api  [8MB/27MB 30%]
20230228 181921.456 [main] INFO  i.g.d.s.t.sdrplay.api.SDRplay - API library - open status: Fail  [10MB/27MB 37%]
20230228 181921.456 [main] INFO  i.g.d.s.t.sdrplay.api.SDRplay - API library is not available.  [10MB/27MB 37%]
20230228 181921.462 [main] INFO  i.g.d.settings.SettingsManager - SettingsManager - loading settings file [C:\Users\Preferred Customer\SDRTrunk\settings\settings.xml]  [10MB/27MB 38%]
20230228 181922.604 [main] INFO  i.g.d.playlist.PlaylistManager - Loading playlist [C:\Users\Preferred Customer\Desktop\playlist\my playlist.xml]  [14MB/27MB 55%]
20230228 181922.831 [main] INFO  i.github.dsheirer.gui.SDRTrunk - starting main application gui  [18MB/76MB 24%]
20230228 181934.100 [sdrtrunk scheduled thread 2] INFO  i.g.d.c.c.ChannelAutoStartFrame - Starting [3] now - timer invoked  [90MB/148MB 61%]
20230228 181934.149 [sdrtrunk scheduled thread 2] INFO  i.g.d.a.c.mbe.JmbeAudioModule - Loading JMBE library from [C:\Users\Preferred Customer\SDRTrunk\jmbe\jmbe-1.0.9.jar]  [93MB/148MB 63%]
20230228 181934.163 [sdrtrunk scheduled thread 2] INFO  i.g.d.a.c.mbe.JmbeAudioModule - JMBE audio conversion library loaded: JMBE Audio Conversion Library v1.0.9  [94MB/148MB 63%]
20230228 181934.164 [sdrtrunk scheduled thread 2] INFO  i.g.d.a.c.mbe.ImbeAudioModule - JMBE audio conversion library IMBE CODEC successfully loaded - P25-1 audio will be available  [94MB/148MB 63%]
20230228 181937.551 [sdrtrunk heterodyne channel 770206250] INFO  i.g.d.a.c.mbe.AmbeAudioModule - AMBE CODEC successfully loaded - P25-2/DMR/NXDN audio will be available  [447MB/674MB 66%]

**Comment by DSheirer** [comment]
Closing.  I believe this has been resolved, but if not, please add a comment here and I'll reopen to investigate.
