### ISSUE TITLE
Trying to decode Cap+ system

### ISSUE THREAD

**Issue by wedgef5** [DSheirer/sdrtrunk#1482]
I'm trying to decode a MotoTRBO Capacity+ system. I've entered the three frequencies given by RR and assigned the LSNs to the appropriate channels. I never hear any audio. I have tested the audio output from User Preferences and confirmed it is working. I have observed the following...

- "Status" will show one of IDLE, ACTIVE, CALL or FADE
- The "To" TGID and Alias sometimes populate with expected TGIS info. I don't think I've ever seen "From" populated
- The "Channel Name" will show either Control or TRAFFIC

I've looked at the Messages pane, and it appears that sdrtrunk is at least "sort of" decoding the system, but I also see a fair number of "CRC Error" and "SYNC LOSS" messages.

Maybe sdrtrunk doesn't support DMR Cap+...I don't know for sure. Any input is appreciated.

Matt

**Comment by DSheirer** [comment]
Hi Matt.  There's several user-support forums where you can ask user-support questions like these: https://github.com/DSheirer/sdrtrunk/wiki/Support

GitHub issues are used to report bugs or feature requests for sdrtrunk software.

sdrtrunk does support decoding DMR Capacity Plus systems.  At first read, it sounds like you may not be getting a strong enough signal to the decoder and you're not getting a good decode.  Recommend you ask this question again in the email forum and include screen shots of the spectral display showing the signal you're trying to decode and the 'Messages' tab that would show the quality of the decodes.

I'm closing this issue.

cheers,
Denny
