### ISSUE TITLE
Hello im new to this Also im running it on linux mint 

### ISSUE THREAD

**Issue by discobiscuit65** [DSheirer/sdrtrunk#1494]
My problem is when I try to set up playlist editor and click new it will not let me pick any decoders 
![Screenshot from 2023-03-14 19-33-09](https://user-images.githubusercontent.com/104811673/225169644-d6acf332-ab64-471f-bda8-037827c65fe6.png)
       
Please help Thanks

**Comment by DSheirer** [comment]
When you click the New button, does it show a drop down list of decoders or what does it show?

**Comment by discobiscuit65** [comment]
when I click it no it does not show nothing at all

**Comment by bradjtrammell** [comment]
I realize this was posted months ago, and this is kind of a stupid question... but do you have the proper drivers installed?

Linux (except DragonOS Focal) doesn't ship by default with the SDR Libraries needed to operate most SDR Dongles. You need to install them from the command line.

Run `sudo apt-get install rtlsdr`, then reboot and launch SDRTrunk again. That SHOULD enable you to be able to control the dongle from software.

**Comment by discobiscuit65** [comment]
I do thanks for the help iv got it working just a simple fix it was a mistake on my part

**Comment by DSheirer** [comment]
Closing as resolved/OBE.
