### ISSUE TITLE
Is there a way to ignore a SDR. 

### ISSUE THREAD

**Issue by garamus** [DSheirer/sdrtrunk#1495]
Im wondering if I can get sdrtrunk to ignore a SDR. I want SDRTrunk to use one and SDR Console to use the other. When SDRTrunk starts it picks up both SDRs.

**Comment by hans109h** [comment]
Yes, click the tuners tab, click the tuner you don't want to load and click the disable button.

**Comment by garamus** [comment]
![SDRTrunk](https://user-images.githubusercontent.com/50639317/225421962-34638710-e681-4765-b9a2-5ba3dafb000d.png)
I dont see an option to disable.

**Comment by hans109h** [comment]
It was introduced in v5 Beta 4.  If you want this feature you'll need to run a more current version.

**Comment by garamus** [comment]
Ok, Ill upgrade.

**Comment by garamus** [comment]
The update worked. Thank you
