### ISSUE TITLE
Decoding part.

### ISSUE THREAD

**Issue by Pascal66** [DSheirer/sdrtrunk#1505]
Just a question:
Is **sdrtrunk** able to do things like URH do (or rtl_433) ?

**Comment by DSheirer** [comment]
GitHub Issues is for documenting issues (bugs/feature requests) with the sdrtrunk software and not a place for posting end user questions.

You can post questions like these using any of the support options listed in the wiki: https://github.com/DSheirer/sdrtrunk/wiki
