### ISSUE TITLE
Crash can occur with SDRPlay API in place, but service stopped

### ISSUE THREAD

**Issue by alphafox02** [DSheirer/sdrtrunk#1511]
**sdrtrunk Version**
[Version 0.6.0 Alpha 4](https://github.com/DSheirer/sdrtrunk/releases/tag/v0.6.0-alpha.4)

**Describe the bug**
Crash in program without SDRPlay service running

**To Reproduce**
1. On linux, 22.04 aarch64 (most likely AMD64 too) have the SDRPlay 3.x API installed, but have the service stopped with sudo systemctl stop sdrplay.service
2. Start SDRTrunk from terminal and observe SDRtrunk finding the sdrplay.so file, but crashing due to service not running.

**Expected behavior**
SDRTrunk should continue to start and run even without sdrplay started, maybe just warn the user instead of crashing.

**Comment by DSheirer** [comment]
Resolved in PR #1514
