### ISSUE TITLE
No right channel audio streamed to broadcastify

### ISSUE THREAD

**Issue by doctorwizz** [DSheirer/sdrtrunk#1537]
SDRT does not send any audio to the right channel when connected to Broadcastify. I can hear both channels in perfect stereo in windows audio. 
Broadcastify does not recognize this as a stereo broadcast and they show only one channel on the statistics tab in feed manager. Conversations are missed as a result. I have to broadcast in mono. This is not that great. During busy time, calls are missed and can be garbled.

**Comment by DSheirer** [comment]
Redundant to #175.  Closing.
