### ISSUE TITLE
SDRPlay driver not linking to driver on m1 mac. I have a workaround...

### ISSUE THREAD

**Issue by jaminmc** [DSheirer/sdrtrunk#1553]
I'm using sdr-trunk-osx-aarch64-v0.6.0-alpha5

SDRTrunk doesn't work with my SDRPlay out of the box. It tries to link to /usr/local/lib/libsdrplay_api.dylib, but it is not that file... The M1 drivers from SDRPlay install /usr/local/lib/libsdrplay_api.so instead. I can get it to work by running;
`sudo ln /usr/local/lib/libsdrplay_api.so /usr/local/lib/libsdrplay_api.dylib`

**Comment by DSheirer** [comment]
Thanks for the report.

I updated the User Manual Tuner's Section and created a FAQ entry for this issue.

The SDRplay team is already aware of this issue and will resolve it in a future release of the API installer.

User Manual: https://github.com/DSheirer/sdrtrunk/wiki/Tuners#sdrplay-on-mac-os
FAQ: https://github.com/DSheirer/sdrtrunk/wiki/FAQ#how-can-i-use-sdrplay-receivers-on-a-mac-os-computer
