### ISSUE TITLE
Out of range tuning in Het mode

### ISSUE THREAD

**Issue by AC9BX** [DSheirer/sdrtrunk#1558]
**sdrtrunk Version**
0.6.0 alpha or 0.5.3

**Describe the bug**
In **heterodyne** mode when attempting to tune a frequency substantially above (by about 3.59 MHz) the range of a tuner locked frequency it will drop anything locked and tune to said attempted frequency versus ignoring it or displaying a "no tuner available" message. Going below the locked frequency does not appear to do this. This is problematic because if monitoring a trunk system for example with frequencies too far apart for a single tuner it will willingly drop the control channel if it needs to reach a frequency substantially too high.

**To Reproduce**
1 Put program in Heterodyne mode
2a Use any trunk system too wide for a single tuner, wait for a call on a frequency too high for the tuner to reach while locked on the control channel, or try tuning a conventional frequency too high.
2b or tune to any frequency. (In this example an always on VHF channel) Then tune to another frequency too high for the tuner to reach. The range moves to include the new frequency, dropping anything too low. 
3 Stopping the 'too high' channel, the software does NOT move back to the original when in analog. It will eventually get back to normal when trunking.
4 Selecting a frequency too low, the range moves to tune the highest frequency.

**Expected behavior**
"Cannot tune, no tuner available" message
"fade" indication when trunking that the channel cannot be reached.

**Desktop (optional - complete the following information):**
Windows and Linux

![20230520_123719_screen_capture](https://github.com/DSheirer/sdrtrunk/assets/113632555/d04366b4-16de-4f6f-b2af-8f7fd09e8278)
![20230520_123720_screen_capture](https://github.com/DSheirer/sdrtrunk/assets/113632555/bd9472f6-a547-4494-8203-c3df32e243e3)
![20230520_123736_screen_capture](https://github.com/DSheirer/sdrtrunk/assets/113632555/c13c24f0-616a-4585-8ddd-d0f8b2ba5a76)
![20230520_123742_screen_capture](https://github.com/DSheirer/sdrtrunk/assets/113632555/1156480e-2e1b-4c8e-8a1d-6e65093dac6b)
![20230520_123809_screen_capture](https://github.com/DSheirer/sdrtrunk/assets/113632555/10d51560-89a1-4c0f-843c-eafa79c3740a)
![20230520_123813_screen_capture](https://github.com/DSheirer/sdrtrunk/assets/113632555/14310d7f-9b3f-4425-ad24-c578fd07a3a0)
![20230520_124050_screen_capture](https://github.com/DSheirer/sdrtrunk/assets/113632555/7b98a89e-5f3f-4de0-b343-79e783345a0f)
![20230520_124925_screen_capture](https://github.com/DSheirer/sdrtrunk/assets/113632555/f7f07b2c-8a82-4c3d-8aeb-e62ad17ec97c)
![20230520_125015_screen_capture](https://github.com/DSheirer/sdrtrunk/assets/113632555/bc449c44-241b-46d2-9d8b-d17e2f079c02)
![20230520_125106_screen_capture](https://github.com/DSheirer/sdrtrunk/assets/113632555/c379fed5-5751-4fe5-b065-d8f38d9d801e)

[sdrtrunk_app.log](https://github.com/DSheirer/sdrtrunk/files/11522889/sdrtrunk_app.log)

**Comment by jamren01** [comment]
I too am observing this; however, only on 0.6.0 alpha 4 and newer, observing 700/800MHz P25 traffic on 3 SDRplay RSP1a devices.

**Comment by DSheirer** [comment]
@AC9BX Thanks for the detailed bug report.
