### ISSUE TITLE
GUI not launching

### ISSUE THREAD

**Issue by techyporcupine** [DSheirer/sdrtrunk#1587]
**sdrtrunk Version:**
v0.6.0-alpha6

**Describe the bug:**
When running ./sdr-trunk, it detects my SDR and such, but doesn't launch the GUI. It says `INFO  i.g.dsheirer.gui.SDRTrunk - starting main application headless`

**To Reproduce:**
1. Run ./sdr-trunk
2. Notice that it does not launch GUI

**Expected behavior:**
I would expect it to launch the GUI as it does on Xfce on this same device

**Desktop:**
 - OS: Fedora 38
 - CPU Cores: 2 cores, 4 threads
 - RAM: 8GB
 - Windowing Manager: Hyprland

**Additional context:**
I think this has to do with me using Hyprland as my WM, this is not an issue on Xfce on the same device.
It is like this on the Alpha version, and the latest stable version.

I can supply more info if needed.

**Comment by hans109h** [comment]
It's been a while since I had to deal with this, but you might try setting a $DISPLAY variable when you execute the command.

**Comment by hans109h** [comment]
You'll need to know what display you want the GUI to be on, but something like:

DISPLAY=:1 ./sdr-trunk

or multi-line:
export DISPLAY=:1
./sdr-trunk
unset DISPLAY
