### ISSUE TITLE
TDULC Data Packets Status Column Shows "Active" not "Data"

### ISSUE THREAD

**Issue by jamren01** [DSheirer/sdrtrunk#1595]
**sdrtrunk Version**
'master-branch' if you are running the latest code - 7/3/23

**Describe the bug**
TDU packets appear to breifly show "Data" in the "Status" column; however, TDULC packets do not.

**Expected behavior**
"Data" to be shown in "Status" column

**Screenshots**
Attached
![Screenshot from 2023-07-03 11-49-31](https://github.com/DSheirer/sdrtrunk/assets/76674437/888a0033-1665-445e-beda-17e493bf4313)
![Screenshot from 2023-07-03 11-54-24](https://github.com/DSheirer/sdrtrunk/assets/76674437/1426bf88-09eb-4507-98bd-89457d3a46a5)

**Comment by DSheirer** [comment]
I use a status of 'active' when it's decoding terminator data units.  The 'data' status is used when it's transmitting actual data packets.
