### ISSUE TITLE
latest windows update and inability to monitor 

### ISSUE THREAD

**Issue by Clats97** [DSheirer/sdrtrunk#1597]
**sdrtrunk Version**
Master branch most recent update

**Describe the bug**
No reception and no latching to control channel after the latest windows update

**To Reproduce**
1. Update Windows computer
2. try to listen to to a local system

**Expected behavior**
I expected it to work as per usual

**Desktop (optional - complete the following information):**
 - OS: Windows 11
 - CPU Cores: 8
 - RAM: 20GB

**Comment by DSheirer** [comment]
I need more details.  Are you seeing signals in the spectral display?  Can you post a screenshot?  Have you tried reinstalling the zadig driver?

**Comment by Clats97** [comment]
All good! Turns out it was a simple tuner error. I restarted it and boom it's working. Sorry for bothering you mate.

Thanks,
Josh Clatney
________________________________

**Comment by DSheirer** [comment]
Closing as resolved.
