### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException

### ISSUE THREAD

**Issue by jamren01** [DSheirer/sdrtrunk#1598]
**sdrtrunk Version**
'master-branch' 

**Describe the bug**
Terminal window shows increasing number of "Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException" errors. No apparent effect on operation of decoding or visual interface.

**To Reproduce**
Leave software running for a few days.

**Expected behavior**
No errors

**Comment by DSheirer** [comment]
Can you please post the full error/stacktrace?

**Comment by DSheirer** [comment]
Closing.  Resolved under PR #1601
