### ISSUE TITLE
Events Tab Shows Duplicate Events

### ISSUE THREAD

**Issue by jpryor223** [DSheirer/sdrtrunk#1603]
**sdrtrunk Version**
Version 0.6.0 Alpha 7

**Describe the bug**
The Now Playing > active Channel > Events sub panel > "Duration" column value rendering process is adding new rows continuously with incrementing duration time values while an active call plays.

**To Reproduce**
1. Go to and click on a Status CALL active channel in Now Playing.
2. Click on the "Events" sub panel.
3. View the incrementing Duration values and new rows being added while the channel is active.

**Expected behavior**
In previous versions (Alpha 6 and prior) the Duration column current row value would increment the duration value only, and not add new rows as the active call progressed.

**Screenshots**
Active Channel with Events Duration repeating rows (during active channel):
![image](https://github.com/DSheirer/sdrtrunk/assets/66096304/f7f00f9c-9e5d-4099-a1e7-5d3c7c2e4eec)

Idle Channel with no Events Duration repeated rows (leave channel and come back to idle channel):
![image](https://github.com/DSheirer/sdrtrunk/assets/66096304/33e166cf-0c22-4f91-becc-c9765f75933c)

**Application Log**
N/A, no error in application log.  This Bug is visible in Events sub panel.

**Desktop (optional - complete the following information):**
 - OS: Windows 10
 - CPU Cores: 4
 - RAM: 8GB

**Additional context**
Able to reproduce the Events Duration repeating rows with AM, NBFM (with and without DCS decoder enabled), P25-1 conventional channel and trunking traffic channel Decoders.
After leaving the active channel and coming back to a previous idle channel, the Events sub panel no longer shows the repeating rows.
Also noted by and further screen shots in Discord from user "M.C.B.": https://discord.com/channels/565715676749103115/565715676749103117/1129496726022131752

**Comment by linuxnut79** [comment]
i also have this issue.  I have noticed that i can remove the duplicated events by selecting another channel upon refresh the single event is shown.

**Comment by dave3825us** [comment]
I have this issue also. Win 10 64 bit

**Comment by Ctpolicelive** [comment]
Same issue on Linux.. Also if you toggle the event slider lower and then toggle any filter on and off. Then if you turn go back and toggle the slider again it loses all channel aliases and other info in events and just repeats (Identifier Collection Timeslot) 

![Untitlsdrtrunked](https://github.com/DSheirer/sdrtrunk/assets/71675946/109de28c-96c8-4e1b-b63e-499f368e6088)
<img src="/path/to/img.jpg](https://github.com/DSheirer/sdrtrunk/assets/71675946/109de28c-96c8-4e1b-b63e-499f368e6088" alt="Alt text" title="Optional title">

**Comment by Seagravebuff60** [comment]
Same issue here. Im actually the original one who reported it in Discord. https://discord.com/channels/565715676749103115/565715676749103117/1129496726022131752
