### ISSUE TITLE
Events Tab - UI Layout Resizing Issue

### ISSUE THREAD

**Issue by swiftraccoon** [DSheirer/sdrtrunk#1604]
**sdrtrunk Version**
sdr-trunk-windows-x86_64-v0.6.0-alpha7

**Describe the bug**
Events tab does not resize appropriately. Large blank area between headers and filters button. Unable to resize this area.

**To Reproduce**
1. Go to Main Screen
2. Click on Control signal, then Events tab
3. Resize window to be very long vertically.
4. See large blank space in the Events section.

**Expected behavior**
Not for there to be a large blank space.

**Screenshots**
![sdrtrunk](https://github.com/DSheirer/sdrtrunk/assets/47705353/ccce954a-7ed1-42de-9ecf-6f947467df95)

**Application Log**
N/A

**Desktop (optional - complete the following information):**
 - OS: Windows 10 Pro
 - CPU Cores: 8
 - RAM: 64GB

**Additional context**
N/A

**Comment by DSheirer** [comment]
Resolved in PR #1610
