### ISSUE TITLE
Rdio-Scanner API uploader "unknown.dat"

### ISSUE THREAD

**Issue by canuckcam** [DSheirer/sdrtrunk#1620]
0.6.0a7, uploading via the Streaming tab to Rdio-Scanner 6.6.3 (Ubuntu 22.04LTS). 

I think there's a bug in the way SDRTrunk uploads files via the Rdio-Scanner API and it buggers up the process to download and save a call in Rdio-Scanner. Does SDRTrunk send .mp3 or .m4a files?

In the Rdio-Scanner logs, I notice that the Trunk-Recorder and Rdio-Scanner upstream instances show a filename in the logs, where as SDRTrunk a7 doesn't. And this results in an error when saving on a phone, and "unknown.dat" file when downloading on Windows or MacOS. Thanks for any help with this!

Trunk-Recorder:
08/07 00:30 newcall: system=10 talkgroup=36176 file=36176-1691382647_142290000.0-call_331570.m4a success

SDRTrunk:
08/07 00:30 newcall: system=1 talkgroup=1605 file= success

**Comment by DSheirer** [comment]
Recommend submitting this as a bug to the Rdio-Scanner project.
