### ISSUE TITLE
DMR Voice Encryption Header - Motorola vs Hytera

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#1630]
Update FLC opcode 0x21 to correctly detect Motorola vs Hytera message format.

**Comment by DSheirer** [comment]
Resolved.

**Comment by markcarter17** [comment]
i how can you put tetra on windows beta 2 and how can you add this softwear Update FLC opcode 0x21 to correctly detect Motorola vs Hytera message format. thanks
