### ISSUE TITLE
DMR Trunking ‘Check Frequency Map’

### ISSUE THREAD

**Issue by kazzaw** [DSheirer/sdrtrunk#1637]
**sdrtrunk Version**
0.6.0b1

**Describe the bug**
Tested on DMR TIII network - when a call is granted, SDRTrunk reports CHANNEL GRANT - NO FREQUENCY - CHECK LSN CHANNEL MAP. Reprogrammed the system with the LCN instead of LSN but also yielded the same results

**To Reproduce**
1. Tune to DMR TIII control channel 
2. Upon call grant error will display 

**Expected behavior**
A channel grant will display and call audio will play 

**Screenshots**
https://imgur.com/a/0HS3Xh9

**Additional context**
Reverting to v0.5 alpha resolves issue

**Comment by KrumbEMT** [comment]
I had the same issue ([1634](https://github.com/DSheirer/sdrtrunk/issues/1634)) with 6.0b1. Reverted back to 6.0a7 with no issues.

**Comment by Seagravebuff60** [comment]
Were you able to get any audio when SDR Trunk was displaying the error "CHANNEL GRANT - NO FREQUENCY - CHECK LSN CHANNEL MAP"?

**Comment by kazzaw** [comment]
No, no audio, SDRTrunk acted as if it had no channel map so didn’t even show the seperate channels
