### ISSUE TITLE
Automatically Scan Frequency in Range

### ISSUE THREAD

**Issue by ChrisDev8** [DSheirer/sdrtrunk#1639]
# Automatic Frequency Scanner & NFM Improvements

A feature that will scan for radio signals in a range. For example, Air Traffic Control broadcasts a amplitude modulated signal between 118 and 137 MHz. It could be nice to automatically scan this range of frequencies and somehow isolate noise as well, since my local airport doesn't make their frequencies clear. Instead of setting up every signal NFM signal for my local railroad, I could input a start and end frequency, and have support for alias as well. For NFM site, you could input multiple frequencies in a single site to make it faster and easier to input 25 different frequencies. Then NFM aliases would use a frequency instead of a number, making it even easier.

**Comment by DSheirer** [comment]
I don't think this aligns with the focus of sdrtrunk.  There may be other applications/options to achieve what you're looking for.
