### ISSUE TITLE
DMR T3 LCN-LSN Mapping not working

### ISSUE THREAD

**Issue by Hermite123456** [DSheirer/sdrtrunk#1645]
SDRTrunk V6.B1 is not resolving the Frequency either by simply using the CC or by manualy populating the LSN mapping frequencies for a DMR Tier 3 Trunking TINY Network. DSDPlus and Winradio confirm the CH id (LSN), but SDRTrunk cannot resolve. Any clue?

![rtl](https://github.com/DSheirer/sdrtrunk/assets/54645050/8576996f-5295-4f7b-8f42-7f0160122f5e)

**Comment by Hermite123456** [comment]
SDRTrunk V6.B1 is not resolving the Frequency either by simply using the CC or by manualy populating the LSN mapping frequencies for a DMR Tier 3 Trunking TINY Network. DSDPlus and Winradio confirm the CH id (LSN), but SDRTrunk cannot resolve. Any clue? 

![rtl](https://github.com/DSheirer/sdrtrunk/assets/54645050/deda5c7e-d5ac-4ff6-bef4-7625a8df088a)

**Comment by DSheirer** [comment]
Resolved as #1637 / #1646
