### ISSUE TITLE
Duplicate calls in Broadcastify Calls platform

### ISSUE THREAD

**Issue by jmp367** [DSheirer/sdrtrunk#1659]
I have been a provider to Broadcastify Calls for some time, however since using SDRTrunk v0.5.3 to stream two Broadcastify Feeds, I have noticed numerous duplicated calls in certain talkgroups in Broadcastify Calls. The duplicated calls seem to coincide with the talkgroups carried in the two feeds.

**Comment by N8LOL** [comment]
This is a Broadcastify issue. They've allowed duplicates of sites, not sure
why. When you listen to archived recordings, you will hear calls from all
of the sites. It's disappointing, but I don't think they care anymore.

**Comment by jmp367** [comment]
Indeed, right you are. I looked at the source node of each duplicated call, and one was sourced from a different node.

Thanks!

**Comment by DSheirer** [comment]
Closing ... Broadcastify issue.
