### ISSUE TITLE
Regarding Demodulator ViewerFX

### ISSUE THREAD

**Issue by JasleenKaur2308** [DSheirer/sdrtrunk#1682]
How i can use Demodulator Viewer Fx application that is mention in DemodulatorViewerFX.java file 

link - https://github.com/DSheirer/sdrtrunk/blob/a27ddbe0d022a82263608211898990bf50c85bc1/src/main/java/io/github/dsheirer/gui/instrument/DemodulatorViewerFX.java

**Comment by DSheirer** [comment]
I answered this under a separate discussion thread ... closing.
