### ISSUE TITLE
FR: aarch64 support?  libusb4java

### ISSUE THREAD

**Issue by chudgoo** [DSheirer/sdrtrunk#169]
Hello again~
I have been sent a version of libusb4java that I was told was compiled for aarch64, but I'm not entirely sure how to turn the .so file into a usable .jar. 

I'd love to see sdrtrunk supported on 64 bit ARM architectures.  Is this process something you're familiar with?

https://www.dropbox.com/s/urk5eqn5as5drf0/libusb4java.so?dl=0

**Comment by DSheirer** [comment]
I'll get this bundled up and included in the project.

**Comment by DSheirer** [comment]
aarch64 native library now included in master branch.

**Comment by chudgoo** [comment]
Awesome!  I will start testing it tonight on the ODROID C2.  
I'm hoping that with the reduced audio processing load and various other changes you've made recently, that this little $40 SBC -may- be able to replace my primary streaming box, a 2014 Macbook Pro.  I'll chime in with results on this thread later.  Thanks @DSheirer !

**Comment by spinnaker813** [comment]
Wondering if there is an update for the ODROID C2, looking to use one on a project I am working on. How capable is it at decoding a large P25 Phase 1 system
