### ISSUE TITLE
FR: Recorded call events / searchable DVR type view?

### ISSUE THREAD

**Issue by chudgoo** [DSheirer/sdrtrunk#171]
Hello again~  This request has got to be the absolute farthest back burner type of thing...  ;)

I think it would be really cool to have a "Call history" view similar to the control channel "events" view under "Now Playing", but instead of displaying live and recent events, it displays a searchable/filterable history of calls that you can click to play.  Even better, select a range of calls or define in filters something like "show me all calls from TGID "04EA" between 10AM and 10:15AM on October 14th 2016", right click and export as either a collection of files in zip format or a single mp3 file of all of the selected calls merged into one.  Thoughts?  

(also, i realize that it's relatively easy to simply search through the recordings folder, but an in-app  simple search / filter set would add a lot to the already impressive application, IMO)

**Comment by DSheirer** [comment]
I've added your comments to #95 and will expand on the recording view concept to include your ideas.
