### ISSUE TITLE
DMR (MOT) Tier III Capacity Max - Group Calls Duration and TG Recording

### ISSUE THREAD

**Issue by Tbolt10033** [DSheirer/sdrtrunk#1740]
**sdrtrunk Version**
Version 0.6.0 Beta 5

**Describe the bug**
DMR Tier III Capacity Max system - Duration of group calls show 0 or 0.1 in length while group calls are coming in and talkgroups are not recorded.

**Expected behavior**
Group calls to properly show the duration and talkgroups to be recorded.

**Screenshots**
![Screenshot 2023-11-15 011037](https://github.com/DSheirer/sdrtrunk/assets/114013434/1c3433d6-d164-42dd-ae9b-5719e9b4642a)
![Screenshot 2023-11-15 011644](https://github.com/DSheirer/sdrtrunk/assets/114013434/2fe00bc2-421f-460d-b2fd-37cd315373b7)
![Screenshot 2023-11-15 011726](https://github.com/DSheirer/sdrtrunk/assets/114013434/1acb7257-4d4d-4e58-ad44-e9b534b01da9)

**Application Log**
This shows on the command prompt window log when a group call happens.
2023-11-14 23:45:01.366 DEBUG i.g.d.r.AudioRecordingManager - Audio Segment detected with NO TO identifiers  [148MB/540MB 27%]

**Comment by Nokoa** [comment]
I also noticed this issue with a T3 that I found while traveling.  It's as if no continuation call grants are processed?

If you start monitoring the control during an already active group call, will SDRTrunk tune to that call, or will SDRTrunk only tune to T3 calls at their very beginning?

**Comment by Tbolt10033** [comment]
For me, group calls work as normal and come in except for the duration on all say either 0 or 0.1.

**Comment by DSheirer** [comment]
Resolved in issue #1787
