### ISSUE TITLE
SDRPlay AGC Error

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#1757]
**sdrtrunk Version**
latest

**Describe the bug**

From Discord ...

@Denny  Regarding the SDRPlay AGC, with my RSP2pro I always get the following error when toggling AGC on/off (happened with previous versions of SDRTrunk + the very latest build from today with those AGC changes): ERROR i.g.d.s.t.s.RspTunerEditor - Error setting AGC mode on RSP device
I should also note that a few months ago when I first started with the RSP2pro, enabling AGC would really crank the gain way up, then I'd back it down. With the more recent releases of SDRTrunk, I can set the gain all the way to 22 or whatever it tops out at with AGC enabled, and the gain is way too low for any decent decoding. I've instead run it with AGC off and gain set to 17 manually, which is one notch below where I'd normally see overloading @ around 19ish
It's stable with AGC off and gain at 17, just figured I'd mention it since I know you just made some adjustments in that area

**Comment by denny** [comment]
Oh, bad tag.

**Comment by GTR8000** [comment]
Thanks for creating the ticket. I either always forget to do so myself, or I'm just a lazy prick lol

**Comment by cfc62** [comment]
Just a sidenote - I am having all sorts of issues with my RSP1A in other SDR software as well. 

I am really wondering if the API just isn't working right - it (the API service) has crashed several times, and even when running I get really odd behavior when using the RSP1A. 

The RSP1A works fine in their software, so I'm giving stink-eye to the API service.
