### ISSUE TITLE
In presence of multiple SDRs choose preferred ones

### ISSUE THREAD

**Issue by rxes** [DSheirer/sdrtrunk#1763]
**Is your feature request related to a problem? Please describe.**
I have multiple types of SDRs, Nooelec, SDR RTL, AirSpy Discovery, SDRPlay RSPa. When all plugged in, it always defaults to Nooelec, which is not optimal. Seems that even when SDRPlay or AirSpy Discovery, is selected as default tuner for control, it's never used to pick up talk, but Nooelec gets to do it.

**Describe the solution you'd like**
Ability to select preferred tuners that can decode the voice calls

**Describe alternatives you've considered**
None

**Additional context**
![403405912_938604477674046_8051809460258304623_n](https://github.com/DSheirer/sdrtrunk/assets/153829270/190d55a6-b200-4fd9-a80f-8cfb97f4f12f)
![403402143_733007198235157_8879632593452111391_n](https://github.com/DSheirer/sdrtrunk/assets/153829270/a9aee3b1-0b9e-40b4-ada1-a9401262b97e)
![403402000_1038070867521198_4310795786998559753_n](https://github.com/DSheirer/sdrtrunk/assets/153829270/93b0cd84-15ef-4f5d-ade8-59a0a9d19f9d)

**Comment by DSheirer** [comment]
Closing as resolved under https://github.com/DSheirer/sdrtrunk/pull/1808
