### ISSUE TITLE
P25 Control channel is centered while auto-generated traffic channels are always offset.

### ISSUE THREAD

**Issue by nelson1christopher** [DSheirer/sdrtrunk#1765]
**sdrtrunk Version**
0.6.0beta5 and 0.6.0alpha5

**Describe the bug**
When setting a high ppm value (~220) to hit my local control channels, I am able to decode the CC, but the autogenerated traffic channel is consistently offset from the actual signal by about the value of the ppm I've set, and I don't get any audio. Traffic channel comes up blue.

**To Reproduce**
Start SDRTrunk and tune to local control channel. 

**Expected behavior**
Expect the traffic channels to be centered on the signal like the control channel is

**Screenshots**
I'll upload screenshots when I'm in front of my PC again

**Application Log**
I can upload this if it's necessary

**Desktop (optional - complete the following information):**
 - Debian 12 (KVM guest)
 - CPU Cores: 16
 - RAM:16gb

**Additional context**
One of my SDR dongles is from about 2016, the other I ordered recently. One has the dinky little antenna that ships with the unit, the other has a longer antenna I ordered from Amazon rated for 978MHz and 1090MHz... Maybe this is my problem?

**Comment by nelson1christopher** [comment]
![Screenshot (13)](https://github.com/DSheirer/sdrtrunk/assets/31422800/119d3e68-6015-4f3f-8b16-bd57196a1704)
![Screenshot (14)](https://github.com/DSheirer/sdrtrunk/assets/31422800/d5b40c72-7781-4cd7-a925-ef7802f03ff2)
![Screenshot (18)](https://github.com/DSheirer/sdrtrunk/assets/31422800/a87940b6-7ddd-412f-97f2-6b8ce11a7fbe)

Attached are my screenshots. A couple of notes:

- It does the same thing whether there's two dongles or one plugged in. I figured for the sake of simplicity, I'd start with one.

- The temp on the SDR is stable as it's been running all day.

- I haven't made any adjustments such as ppm since this morning (about 16 hours ago)

**Comment by DSheirer** [comment]
You can also go to the details tab for the control channel ... I think it should tell you what the actual primary control channel frequency is for the site.

**Comment by nelson1christopher** [comment]
This worked... the RR frequencies were incorrect, but I was so stuck on using them, I didn't think to try the frequency reported by the control itself. Calls are uploading now. Not a bug, just an ID-10t/pebkac error...
