### ISSUE TITLE
RRDB Enterprise Account Import

### ISSUE THREAD

**Issue by BrendanMan3** [DSheirer/sdrtrunk#1781]
Hello I am running v0.6.0 and have tried to link to my RRDB account which is an enterprise account. However I receive the error that my account is not a premium RRDB account in sdrtrunk, although it is.

**Comment by DSheirer** [comment]
You may want to try logging into the webpage and verify that you can browse through the frequency database.  If that's ok, then check with the radio reference folks to see why your account login doesn't reflect premium.

**Comment by BrendanMan3** [comment]
My account is not Premium, it is Enterprise. So while it is also premium it also includes a few extra perks.
Enterprise and Premium should be the same for importing from the RRDB.

**Comment by DSheirer** [comment]
The sdrtrunk application attempts to use the radio reference API using the login credentials that you provide.  If the API service is reporting that your account is not enabled to use the API, then that's something you'll have to resolve with the radio reference team.

Even though sdrtrunk reports the error as 'you don't have a premium account', the reality is that your login credentials are not authorized to access the API.

I don't believe this is a bug in the sdrtrunk software.

**Comment by blantonl** [comment]
Dennis, can you advise how SDRTrunk is determining premium subscription status and authorization?  What API call are you using, and what attributes are you keying off of to make the determination?

This seems to be localized to SDRTrunk and I'm trying to determine why... other API consumers appears to be working ok (this person is able to use ProScan for instance just fine with his enterprise account)

**Comment by DSheirer** [comment]
In discussion with @blantonl the API ```getUserDetails``` method can return the following values:

* An expiration date
* Never - Feed Provider
* Never - Admin
* Never - Enterprise

Will update sdrtrunk to accept any non-date value strings that start with 'Never' as valid expiration dates.

**Comment by DSheirer** [comment]
After inspecting the code, it should be handling the optional response values for any of the 'Never - ' expiration status and allowing the user to use the RR API.

I tested each of these response values and confirmed that the code functions correctly.

@BrendanMan3 can you post a screen shot of the radio reference tab in the playlist editor?  This should display the 'Expiration Date' value that was returned from the radio reference API for your account.

**Comment by BrendanMan33** [comment]
![Screenshot 2024-07-29 113035](https://github.com/user-attachments/assets/926cfdcf-9aec-4377-bb35-1da4b3695641)
That did the trick.

Thank you all for the help.
