### ISSUE TITLE
RSPduo spectrum expanded

### ISSUE THREAD

**Issue by ah1102** [DSheirer/sdrtrunk#1782]
sdrtrunk 0.6.0 release
macOS 10.15
RSPduo

I observe that RSPduo's spectrum is expanded compared to hackRF and rtl-sdr. It can be seen that adjacent P25p1 channels overlap each other. On hackRF the channels are clearly visible.

![Снимок экрана 2024-01-07 в 14 06 52](https://github.com/DSheirer/sdrtrunk/assets/58341369/41c14318-c9fc-4a38-9f40-3a081d12d745)
![Снимок экрана 2024-01-07 в 14 08 17](https://github.com/DSheirer/sdrtrunk/assets/58341369/268114f0-9534-4536-983e-8fe01636168a)

**Comment by ah1102** [comment]
Or here is the NBFM channel 12.5 kHz. The spectrum goes beyond.

![Снимок экрана 2024-01-07 в 14 29 33](https://github.com/DSheirer/sdrtrunk/assets/58341369/b3b27081-5160-4ce2-9187-8adb38b47bd4)
![Снимок экрана 2024-01-07 в 14 34 26](https://github.com/DSheirer/sdrtrunk/assets/58341369/96f0ecd3-4909-41fe-a484-bd48e90e2354)

**Comment by ah1102** [comment]
I installed Nightly available the version now and nothing has changed in the spectrum. SDRPLAY API 3.15

**Comment by DSheirer** [comment]
I can't fix this.

**Comment by ah1102** [comment]
> I can't fix this.

Look. This screenshot is made today. The version of the program is the last **vnightly**. I have the impression that the width of the spectrum depends on the signal level. Very weak signals contain the width of the spectrum.

![Снимок экрана 2024-10-28 в 16 49 28](https://github.com/user-attachments/assets/732cefae-5044-413a-8de8-872c5b3e3ea5)
