### ISSUE TITLE
Regarding designing of 4-FSK using siglib

### ISSUE THREAD

**Issue by JasleenKaur2308** [DSheirer/sdrtrunk#1804]
I am successfully able to get the results for 2-FSK  using siglib as designed in the link below.
Link - https://github.com/Numerix-DSP/siglib/blob/main/Examples/CExamples/fsk.c

I wanted to design for 4-FSK using the siglib in the same way , how should i designed it and what all changes are required to get the results for 4-FSK using Siglib .

**Comment by DSheirer** [comment]
I don't understand how this applies to sdrtrunk?

**Comment by DSheirer** [comment]
Closing.  If this is indeed an sdrtrunk issue, then please reopen and clarify what the issue is.
