### ISSUE TITLE
Cannot decode MPT-1327 FILES

### ISSUE THREAD

**Issue by EmmaChissit** [DSheirer/sdrtrunk#1826]
**sdrtrunk Version**
Indicate which sdrtrunk version you are using.  Use 'master-branch' if you are running the latest code.
V0.6.0

**Describe the bug**
Have set up everything to decode MPT-1327 SIGNALS
When I press the green play icon, I would expect an arrow to appear in the playing column appropriate to that site. this does not happen

**To Reproduce**

**Expected behavior**
![MPT-1327](https://github.com/DSheirer/sdrtrunk/assets/159229918/1cd0b324-58fd-4830-ad6b-1019f4838238)

**Screenshots**

**Application Log**
If applicable, include either the full application log,or a snippet of the error logging.

**Desktop (optional - complete the following information):**
 - CPU Cores: [e.g. 4 cores]
 - RAM:[e.g. 16GB]

**Additional context**
Dennis replied to my facebook page with how to fix problem:Disable SIMD & vector processing in user preferences. This action fixed the problem
![MPT-1327](https://github.com/DSheirer/sdrtrunk/assets/159229918/f399f7ef-b4c6-4b71-a9d2-11babf2a2604)

D

**Comment by DSheirer** [comment]
Reopening the issue.  The stack trace (error printout) indicates there's an issue in one of the components that needs resovled.

**Comment by DSheirer** [comment]
@EmmaChissit the fix was merged into the master branch and once the nightly build updates, you can use the new version and turn your Vector / SIMD processing back on to make the application run more efficiently.  Please let me know if it continues to generate errors for you.
