### ISSUE TITLE
Don't Change Tuner Center Frequency Unless Have To

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#1845]
**Is your feature request related to a problem? Please describe.**
Update the Polyphase tuner channel manager to only change the tuner center frequency when it's necessary to fit the channels.  

Currently, the polyphase channel manager attempts to find the optimal center frequency that places the majority of the channels aligned to the channel bandwidth raster and this causes the center frequency to update with each channel that gets allocated.

**Comment by GTR8000** [comment]
Another awesome update!
