### ISSUE TITLE
Heap leak

### ISSUE THREAD

**Issue by amigan** [DSheirer/sdrtrunk#1863]
**sdrtrunk Version**
master-branch

**Describe the bug**
I noticed on a couple occasions my two tuner raspberry pi 5 8GB would spin its fan up with occasional truncated calls, and suspected GC hell. I started using a JMX prometheus exporter to take a look. I haven't gotten it reproduce that specific behavior yet, but heap usage is definitely increasing over the long term.
![image](https://github.com/DSheirer/sdrtrunk/assets/1175936/5ce1406c-6bf4-4334-aca2-a2e0ea712221)
![image](https://github.com/DSheirer/sdrtrunk/assets/1175936/5c4b467b-6fc8-47fe-805e-90176c6750eb)

The middle of those graphs was a restart. I am fairly certain the blip of concurrent GC before the restart was while the system was starting to truncate calls, but I'm no longer positive. I am continuing to leave this running to collect more data, but it definitely looks like the heap is growing? I'm not a java guy, so forgive me.

I am happy to take any dumps, or enable further profiling to assist in the effort to fix this.

**To Reproduce**
1. Monitor the RISCON P25 Phase 1 trunk system (10MHz allocation, 4x simulcast sites) with two RTL-SDRs.
2. Leave it running.

**Expected behavior**
Not fans spinning up with calls truncated.

**Screenshots**

**Application Log**
If applicable, include either the full application log,or a snippet of the error logging.

**Desktop (optional - complete the following information):**
- Raspberry Pi 5 8GB running Arch Linux ARM and liberica JDK
- Fluxbox WM, Xvnc
- Spectrograms always disabled
- Two RTL-SDRs 2.4MSPS

**Additional context**
Streaming to rdio-scanner running on another machine and an icecast sink. This and icecast-kh are the sole workload of this system. The P25 system is moderately busy at times but not insane. I do think the problem manifests quicker during rare traffic spikes.

**Comment by amigan** [comment]
This is definitely happening right now. I have taken a heap dump hprof that I can furnish if necessary.

![image](https://github.com/DSheirer/sdrtrunk/assets/1175936/5ca20dee-3386-4892-a481-eaae6e6a189c)
![image](https://github.com/DSheirer/sdrtrunk/assets/1175936/d1454a1b-4327-4b30-ae0e-447cdc282920)

I have attached a heap histogram.
[histogram.txt](https://github.com/DSheirer/sdrtrunk/files/14482202/histogram.txt)

**Comment by DSheirer** [comment]
@amigan can you please run your testing against the latest nightly and let me know if you're seeing the same behavior.

The latest nightly is running JDK23 which has a different GC profile.

There will certainly be some level of increase of heap usage over time as the application stores/caches some of the network details but it should be more than a couple tens of megabytes.

If you perform a manual garbage collect, does the heap usage reduce in size? 

Also, are you looking specifically at allocated heap, or used heap?  VisualVM can give you details for those 2 values.

**Comment by amigan** [comment]
I've installed current `HEAD` and jdk23 and will let things run a few days to see if anything changes. I have never tried to manually initiate GC, but will do so if this issue recurs. Those graphs do specifically show used heap.

**Comment by amigan** [comment]
@DSheirer Things are looking promising. I will continue to monitor.

![image](https://github.com/user-attachments/assets/ae4dafc5-3498-4284-8517-d6ee9f0dfa35)

**Comment by amigan** [comment]
@DSheirer Unfortunately the issue is still occurring. A manual GC does nothing, and left long enough, it indeed begins to truncate calls.

![image](https://github.com/user-attachments/assets/de30794e-265c-410d-b081-98215a75c322)

**Comment by DSheirer** [comment]
Can you capture a Heap Dump in Visual VM and send it to me?  I'm interested to see what's being held onto and not garbage collected.

**Comment by DSheirer** [comment]
To clarify, can you capture a Heap Dump when it's in that extreme memory usage state where the GC is not bring the consumed heap back down to minimums.

**Comment by amigan** [comment]
I built the latest HEAD and am monitoring. I will take a heap dump once it enters the state.

**Comment by amigan** [comment]
@DSheirer I have a heap dump. It is 6GB; how should I get it to  you?

**Comment by DSheirer** [comment]
Heap dump showed memory leak in the incoming audio segment queue where the processing thread either died (unlikely) or was never started (better possibility).  Redesigned the thread start/stop here #2086 and will keep this issue open until testing shows if the issue is resolved.

**Comment by amigan** [comment]
This looks like it is fixed. Thank you!
![image](https://github.com/user-attachments/assets/74e65cf5-4f29-4e9c-bef6-4cacab0a2a5d)

**Comment by DSheirer** [comment]
Awesome!  Thanks for you help in capturing that heap dump.  I don't think I would have been able to chase that down without it.
