### ISSUE TITLE
Icons missing from Releases

### ISSUE THREAD

**Issue by rd0fun** [DSheirer/sdrtrunk#1864]
**sdrtrunk Version**
0.6.0 Final

**Describe the bug**
Icons appear missing from all Releases

2024-02-28 13:23:19.123 INFO  i.g.d.icon.IconModel - loading icons file [/Users/me/SDRTrunk/settings/icons.xml]  [15MB/512MB 3%]
2024-02-28 13:23:19.126 INFO  i.g.d.icon.IconModel - Icons file not found at [/Users/me/SDRTrunk/settings/icons.xml]  [16MB/512MB 3%]

**Comment by bradjtrammell** [comment]
Can you be more specific? 

Icon files are missing or SDR Trunk is not finding the icons.xml file?

Also, what OS are you running?

**Comment by rd0fun** [comment]
I think it's both. I don't see the icons anywhere in the release. Perhaps they are compiled into the binary? The release doesn't seem to actually contain an icons.xml file. I'm running on Mac OS. The system is decoding a P25 network perfectly. Perhaps I simply don't know how to enable the icons? I didn't see anything specific in the Wiki or Readme either.

Thank you.

**Comment by DSheirer** [comment]
Testing against the 0.6.1 beta 2 release, I downloaded the release and verified that the icon files are included.
