### ISSUE TITLE
v0.6.1. beta 1

### ISSUE THREAD

**Issue by Nickp103** [DSheirer/sdrtrunk#1870]
I keep getting a threadlock error message after about 15 mins running the latest version i attached the log message 

[20240214_070601_sdrtrunk_processing_diagnostic_report.txt](https://github.com/DSheirer/sdrtrunk/files/14530262/20240214_070601_sdrtrunk_processing_diagnostic_report.txt)

sdrtrunk detected a critical application error with a threading deadlock, described as follows:
Thread ID[32] Name [sdrtrunk scheduled thread 4] Lock [java.util.concurrent.locks.ReentrantLock$NonfairSync@5c0fb1a4] Owned By [ID:143 | NAME:java.util.concurrent.locks.ReentrantLock$NonfairSync@5c0fb1a4]
Thread ID[143] Name [sdrtrunk polyphase channel thread 1] Lock [io.github.dsheirer.module.decode.dmr.DMRTrafficChannelManager$TrafficChannelTeardownMonitor@2666a005] Owned By [ID:144 | NAME:io.github.dsheirer.module.decode.dmr.DMRTrafficChannelManager$TrafficChannelTeardownMonitor@2666a005]
Thread ID[144] Name [sdrtrunk polyphase channel thread 1] Lock [java.util.concurrent.locks.ReentrantLock$NonfairSync@5c0fb1a4] Owned By [ID:143 | NAME:java.util.concurrent.locks.ReentrantLock$NonfairSync@5c0fb1a4]

=========================================================================

sdrtrunk Processing Diagnostic Report

=========================================================================

JVM and Application Environment Report

Version  : 0.6.1-beta-1
Gradle Version    : Gradle 8.2
Build Timestamp   : 2024-02-10T06:13:36.523-0500
Build-JDK         : 20.0.1 (BellSoft 20.0.1+10
Build OS          : Linux (amd64 6.2.0-39-generic
Host OS Name:          Windows 10
Host OS Arch:          amd64
Host OS Version:       10.0
Host CPU Cores:        4
Host Max Java Memory:  3 GB
Host Allocated Memory: 486 MB
Host Free Memory:      275 MB
Host Used Memory:      210 MB
Storage Directories:
 Application Root: C:\Users\nperr\SDRTrunk
 Application Log:  C:\Users\nperr\SDRTrunk\logs
 Event Log:        C:\Users\nperr\SDRTrunk\event_logs
 Playlist:         C:\Users\nperr\SDRTrunk\playlist
 Recordings:       C:\Users\nperr\Dropbox\Starcom21

=========================================================================

**Comment by DSheirer** [comment]
I believe this was resolved with either #1829 or #1857.

If not, please reopen this issue.
