### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by ADM12-1** [DSheirer/sdrtrunk#1873]
**sdrtrunk Version**
Indicate which sdrtrunk version you are using.  Use 'master-branch' if you are running the latest code.
V0.6.1-beta-1

**Describe the bug**
Apologize for yet another no audio issue.  Everything installed correctly, the JMBE directory was created successfully, the application runs fine, i see no errors in the log file, yet, no audio. it is not muted and the audio test from user preferences works fine. I am using the RTL-SDR 2832U R860T. I have the waterfall and it is receiving signal. I am testing on an FM radio station so I know there should be audio. My system information is attached. Just curious if anyone else had this issue that didn't resolve by one of the other threads. Appreciate any input.  I will attach screenshots & my system information.

**To Reproduce**
I just start the application.

**Expected behavior**
To Hear Audio

**Screenshots**
attached

**Application Log**
I have attached the sound.properties conf file but do not see an application log or an error log.

**Desktop (optional - complete the following information):**
attached
![NowPlayingEvents-Screenshot 2024-03-14 120023](https://github.com/DSheirer/sdrtrunk/assets/163433319/bc1ad2de-db8b-4735-b7ac-77fa050cecec)
![OutputTones-Screenshot 2024-03-14 115225](https://github.com/DSheirer/sdrtrunk/assets/163433319/c07d1f9d-8bda-4a60-bdf5-ecf9fc3df2f6)
![NowPlaying-Screenshot 2024-03-14 115006](https://github.com/DSheirer/sdrtrunk/assets/163433319/cb4acf80-74ff-494b-a33d-4d00cae25390)
![Tuner-Screenshot 2024-03-14 114907](https://github.com/DSheirer/sdrtrunk/assets/163433319/7a0be047-45c1-42e6-a4e9-3384e3a997c7)
![System-Screenshot 2024-03-14 095612](https://github.com/DSheirer/sdrtrunk/assets/163433319/56651ded-e7a5-4de0-a652-cc747766df46)

**Additional context**

**Comment by JamesK455** [comment]
Do you have a channel defined in the [Playlist Editor](https://github.com/DSheirer/sdrtrunk/wiki/Playlist-Editor)? You need one defined in there, plus an Alias list set to Listen. Manually tuning the tuner to a frequency won't pipe any audio.

**Comment by DSheirer** [comment]
@ADM12-1 Here's the user's manual for how to create playlists and channels: https://github.com/DSheirer/sdrtrunk/wiki/Playlist-Editor

Closing - this is not a software bug.  If you have any followup user questions, please use one of the support forums.

**Comment by ADM12-1** [comment]
DSheirer,  I appreciate you taking the time. Thank you.
