### ISSUE TITLE
Api error -no frequency table

### ISSUE THREAD

**Issue by scottyb908** [DSheirer/sdrtrunk#1881]
**sdrtrunk Version**

**Describe the bug**

I am trying to get the SDR Trunk set up to feed to broadcatify calls from a conventional system. Whenever there's activity I am seeing the stream being uploaded to the standard streams but calls doesn't report any activity. in the logs I am seeing an error [Broadcastify Calls API upload URL Request failed [1 no-freq-table-entry-for-upload]. I don't see any place to add freq information specific to calls.

**To Reproduce**
Create a calls broadcastify system, 
configure tuner and create “talk group”/alias
Try to upload transmission to broadcastify. 

**Expected behavior**

**Screenshots**

**Application Log**
If applicable, include either the full application log,or a snippet of the error logging.

**Desktop (optional - complete the following information):**
 - CPU Cores: [e.g. 4 cores]
 - RAM:[e.g. 16GB]

**Additional context**

**Comment by DSheirer** [comment]
I don't know what this error means.  Have you reported this to the Broadcastify support forum?

**Comment by scottyb908** [comment]
I have posted there as well. I am not sure which side is causing the error, bad api response vs bad call. Sent from my iPhoneOn Mar 27, 2024, at 3:36 AM, Denny Sheirer ***@***.***> wrote:﻿
I don't know what this error means.  Have you reported this to the Broadcastify support forum?
