### ISSUE TITLE
Radio ID alias 

### ISSUE THREAD

**Issue by minecrafter12345** [DSheirer/sdrtrunk#1884]
A good idea would be to make the Radio Alias display instead of the Radio ID, when for instance it changes channel, or affiliates to whatever channel its on.

I would like for the Radio Alias, and the channel Alias to pop up when a radio changes channel or affiliates with a channel instead of the channel TG Number or Radio ID number.
This us under the Events Tab.
Thanks! hopefully this made sense lol

**Comment by ikm19** [comment]
you already can do that. 

open your playlist editor

go to tab "Aliases" then to secondary tab "Alias"

on the right click "new"

this will create new entry in the alias list. then bellow the list add your name, group and identifiers as on the screenshot bellow. hope this help my friend. happy scanning.
![sdr trunk rid](https://github.com/user-attachments/assets/913ad414-4db8-490b-8bef-135d9fc45144)

**Comment by minecrafter12345** [comment]
Yes, I have those setup, I am refering in the events tab, where you can watch and see what channel a radio swaps to, on the side instead of the channel name it’s uses the number instead of the alias for that channel

**Comment by DSheirer** [comment]
This sounds very comlicated.  Closing.
