### ISSUE TITLE
Missing Call/Audio

### ISSUE THREAD

**Issue by IMG20191023** [DSheirer/sdrtrunk#1885]
**sdrtrunk Version**
v0.6.0

**Describe the bug**
The system im monitoring currently has three talkgroups that are patched together, I only have one talkgroup configured as listen and recording as this is the main talkgroup i want to monitor. SDRtrunk is missing calls while im listening, not every second call, but randomly it will miss a call here and there and i assume its because the application it switching to a talkgroup that isn't set for listen or record when they all become active.
In addition when the issue happens, I sometimes find a recording file in my recording folder with the name of one of the patched talkgroups that is not set to record !

**To Reproduce**
Have two patched talkgroups that are active on one site, only have one talkgroup set to listen.

**Expected behavior**
Every call on the talkgroup configured as listen and record is heard.

**Screenshots**
n/a

**Application Log**
If applicable, include either the full application log,or a snippet of the error logging.

**Desktop (optional - complete the following information):**
 - OS: Win 10
 - CPU Cores: 4
 - RAM: 16gb

**Additional context**

**Comment by DSheirer** [comment]
@IMG20191023 can you please try the latest nightly build to see if this resolves the issue?  I updated a lot of the code to resolve issues with patch group management and missing P25 messaging support.

**Comment by IMG20191023** [comment]
Thanks, will do & report back.
