### ISSUE TITLE
SDRPlay RSP1B tuner settings 

### ISSUE THREAD

**Issue by dleiken** [DSheirer/sdrtrunk#1889]
The tuner settings for the SDRPlay RSP1B are very limited compared to a tuner like the Airspy. Will more options be available in the future?

**Comment by DSheirer** [comment]
I can only give you control over the settings that the tuner vendor provides.  Is there a specific setting that's available via the SDRPlay API for the RSP1B that you know is missing?

**Comment by dleiken** [comment]
As you can see from the attached photo I need to make some adjustments for proper decoding. When I turn down the gain it loses locking on my CC and when gain is up it does not decode 100%. Should I be making settings change with the SDRPlay console, and will they reflect to SDRT? I don’t see any settings within the API. Thanks for your help. Sent from my iPhoneOn Apr 17, 2024, at 3:05 AM, Denny Sheirer ***@***.***> wrote:﻿
I can only give you control over the settings that the tuner vendor provides.  Is there a specific setting that's available via the SDRPlay API for the RSP1B that you know is missing?

**Comment by DSheirer** [comment]
@dleiken there's no photo attached here.  You'll need to use the github interface to attach photos.

You should only make changes in the sdrtrunk application ... I don't know/think that making changes to an SDRPlay tuner that is in-use by sdrtrunk will have any effect.

The user manual for setting gain on sdrplay tuners is here: https://github.com/DSheirer/sdrtrunk/wiki/Tuners#setting-gain-on-rsp-tuners

**Comment by culleydog2005** [comment]
Polk County Florida scanner for all sites down
