### ISSUE TITLE
Support for RTL2832P tuner

### ISSUE THREAD

**Issue by am-silex** [DSheirer/sdrtrunk#1896]
Hello
I've bought Astrometa DVB-T2 tuner and discovered that it has RTL2832P and R828D tuner. Basically, it's the same as RTL-SDR Blog V4. Hoverer, while I've added support for ven & prod ID in local build using commit with tag beta-1 I can't start this tuner. It's available in list, but when I'm trying to enable it says 
Status Error - Unable to initialize R828D

```
rtl_eeprom

Using device 0: Astrometa DVB-T/DVB-T2
Found Rafael Micro R828D tuner

Current configuration:
__________________________________________
Vendor ID:              0x15f4
Product ID:             0x0131
Manufacturer:           astrometadvbt2
Product:                dvbt2
Serial number:          0011
Serial number enabled:  no
Bias Tee always on:     no
Remote wakeup enabled:  no
```

**Describe the solution you'd like**
I'd like to investigate this error add add support for tuners based on RTL2832P chip

**Describe alternatives you've considered**
Can't think of any...

**Additional context**
I understand that this chip is no match to authentic RTL-SDR Blogs

**Comment by DSheirer** [comment]
There's an existing issue for this: #227 - Closing.

Feel free to add support for this tuner and submit a pull request.  Otherwise I plan to add support at some time in the future.
