### ISSUE TITLE
Audio Output always on same device

### ISSUE THREAD

**Issue by dtmf1313** [DSheirer/sdrtrunk#1917]
Running V0.6.0

Trying to get the audio out to a specific device.

Under User Preferences, Audio, Output/Tones Audio Output device, I see the basic speakers and all of my 4 USB to Audio devices showed under the name "Headphones (1-TX 96Khz USB Audio)" and "Headphones (2-TX 96Khz USB Audio)" and "Headphones (3-TX 96Khz USB Audio)" and "Headphones (4-TX 96Khz USB Audio)".

I was expecting SDRTrunk to pipe the audio to the selected device but, whatever device I choose, the audio is always going to the first one "Headphones (1-TX 96Khz USB Audio)". 

Windows 10 Pro
i3-8100
8GB

**Comment by DSheirer** [comment]
sdrtrunk can only use the audio devices that the Java runtime exposes from the OS.  If the existing options don't work for you, there's nothing else that I can do.
