### ISSUE TITLE
DMR Decode in bits

### ISSUE THREAD

**Issue by alwinhb** [DSheirer/sdrtrunk#1938]
Can we decode DMR Wave into the bits using sdrtrunk? Tried message recording viewer but unable to see bit streams

**Comment by DSheirer** [comment]
This is a user question and not a software discrepancy/issue.  Please post questions like this in the user support forums.

You can add the DMR wave file as a recording tuner in the Tuners tab and then create a channel configuration to decode it and record the raw bits to a file and then use the message viewer tool to view the messages.
