### ISSUE TITLE
Help with SDRtrunk

### ISSUE THREAD

**Issue by Bonk01** [DSheirer/sdrtrunk#1949]
I bought another Airspy to use on another computer with SDRtrunk the analyzer looks smeared I adjusted the sensitivity up and down then I connected it to my main computer and it worked and the Airspy I had already in my main computer to the other computer and it did the same thing SDRtrunk works on my main computer but not the other but the RTL-SDR works, What could be the problem?
![Screenshot 2024-08-13 105154](https://github.com/user-attachments/assets/cdd7bf39-528d-40fc-b71c-4a3dd1c39cef)
![Screenshot 2024-08-13 105135](https://github.com/user-attachments/assets/132b0a28-108b-499e-93d7-ff15ae16dc2a)

**Comment by DSheirer** [comment]
@Bonk01 the GitHub issues is used for reporting errors with the software.  You can use the support forum for asking user support questions like this.

It's not clear what the issue you're having.  Recommend posting there.

Closing.
