### ISSUE TITLE
No sound 

### ISSUE THREAD

**Issue by aka1ceman** [DSheirer/sdrtrunk#1951]
**sdrtrunk 0.6.0 ** with 2x    RTL-SDR  V4

**No Sound**
**To Reproduce**
Install, preferences /Output tones / Select any sound device ( have 2 each having mono and stereo) and ? Test
I GET TEST SOUND

I go to manual dial in frequency, and signals show up on waterfall but no sound. I even key up my radio next to it on same frequency. It shows again in waterfall, yet NO sound from speakers. 

![Screenshot 2024-08-21 142923](https://github.com/user-attachments/assets/008db270-8767-412d-bf51-193f5d731ea8)

**Desktop 
Windows 11 23H2
Intel(R) Core(TM) i9-14900KF   3.20 GHz
32.0 GB (31.8 GB usable)
2x RTL-SDR V4
*SDR# works fine on same setup

**Comment by DSheirer** [comment]
@aka1ceman this is not a software deficiency.  You may be making assumptions that sdrtrunk works the same as other sdr applications.  Please read the user's manual about the playlist editor and creating channel configurations.  Please post followup questions to the user support forums.
