### ISSUE TITLE
Audio recordable alias

### ISSUE THREAD

**Issue by davidmckenzie** [DSheirer/sdrtrunk#197]
Hi Denny!

Would it be possible to have an alias tag to enable recording of a single alias? Basically the opposite of the non-recordable tag. I'd like to only record audio on one talkgroup (to identify RIDs), but doing so would mean adding the non-recordable tag to 20+ other aliases.

Thanks!
Dave

**Comment by CGUTH** [comment]
One option is you can highlight multiple aliases and set the Dot Not Record tag.

**Comment by davidmckenzie** [comment]
Omg, how did I not know you could select multiple aliases :D

![](https://media.giphy.com/media/EldfH1VJdbrwY/giphy.gif)

**Comment by CGUTH** [comment]
I just figured it out by accident 2 days ago, I love it.

**Comment by DSheirer** [comment]
I probably need to get the user's manual updated this weekend.

**Comment by DSheirer** [comment]
Did the multi-select and 'Non-Recordable' work out ok for you?

**Comment by davidmckenzie** [comment]
Yup! Thanks both!
