### ISSUE TITLE
Audio recording file handles left open

### ISSUE THREAD

**Issue by ImagoTrigger** [DSheirer/sdrtrunk#198]
When you tell sdrtrunk to write .wavs to /recordings/ it seems that it will sometimes not close all the files when done writing. (observed on windows)

**Comment by ImagoTrigger** [comment]
![image](https://cloud.githubusercontent.com/assets/3333956/23084943/801d627a-f52a-11e6-8027-cf344e5398b8.png)

**Comment by ImagoTrigger** [comment]
going to try to repro on XP/Linux just to make sure it's not my setup...  probably not closing the filechannel....poison pills... ugh.... *headache*

**Comment by ImagoTrigger** [comment]
![image](https://cloud.githubusercontent.com/assets/3333956/23411062/df9a3e02-fd96-11e6-8be3-64daf9674d9d.png)

**Comment by ImagoTrigger** [comment]
think i found this one too...gotta let it run for a while to be sure

**Comment by ImagoTrigger** [comment]
![image](https://cloud.githubusercontent.com/assets/3333956/23448732/53f82576-fe18-11e6-9c40-89e04922cdeb.png)

**Comment by ImagoTrigger** [comment]
well my change made it more atomic lol but not fixed... still leaving handles open regardless of the platform

**Comment by ImagoTrigger** [comment]
![image](https://cloud.githubusercontent.com/assets/3333956/23449656/233c9480-fe1d-11e6-8b34-ada15996fbfa.png)

**Comment by ImagoTrigger** [comment]
fixed it.....

[atomicfiles-patch.txt](https://github.com/DSheirer/sdrtrunk/files/811232/atomicfiles-patch.txt)

**Comment by DSheirer** [comment]
@ImagoTrigger thanks again for finding the problem and figuring out the corrective patch!!

**Comment by ImagoTrigger** [comment]
thanks for fixing it correctly ;-)

**Comment by DSheirer** [comment]
Team work!
