### ISSUE TITLE
SDR Trunk Nightly - P25 Trunking Missed calls

### ISSUE THREAD

**Issue by Tbolt10033** [DSheirer/sdrtrunk#1988]
**sdrtrunk Version**
Indicate which sdrtrunk version you are using.  Use 'master-branch' if you are running the latest code.
master - nightly release

**Describe the bug**
Sometimes, I miss a call even though I should be able to hear all calls like with version 0.6.0. Occasionally, I only hear the second transmission in a conversation, missing the first one. For example, I might hear "Roger pump xx back at quarters" but not "Dispatch Pump xx back at quarters." This issue started after some changes to P25 decoder were made, I believe this: https://github.com/DSheirer/sdrtrunk/pull/1898

**To Reproduce**
Unknown

**Expected behavior**
Like version 0.6.0 the latest version should be able to hear all calls and not miss a call.

**Radio System Protocol**
P25 Trunking Phase I CC with Phase II TDMA talkgroups

**Comment by DSheirer** [comment]
@Tbolt10033 I've made a lot of changes to the codebase.  Please test again with the nightly release and let me know if you're still seeing missged calls?

**Comment by Tbolt10033** [comment]
> @Tbolt10033 I've made a lot of changes to the codebase. Please test again with the nightly release and let me know if you're still seeing missged calls?

I think it is working now. This can be closed.
