### ISSUE TITLE
Bad Links in Wiki

### ISSUE THREAD

**Issue by oblivionratula** [DSheirer/sdrtrunk#2026]
The first two links in the RadioReference section of this page are bad and try to link to github, not RadioReference.com:

https://github.com/DSheirer/sdrtrunk/wiki/User-Manual#where-to-find-radio-signals

**Comment by DSheirer** [comment]
Thanks for the report.  I found/fixed one bad link for radio reference.

Can you point me to the second one?

**Comment by oblivionratula** [comment]
My bad, I now see that was actually intended to self-reference.
