### ISSUE TITLE
SDRTrunk Window Scaling wont work on playlist editor

### ISSUE THREAD

**Issue by hrusakcha** [DSheirer/sdrtrunk#2037]
**sdrtrunk Version**
SDRTrunk Nightly (2024-09-22) , v0.6.1-beta-2, and 0.6.0 stable

**Describe the bug**
I use SDRTrunk on a Linux machine that I rarely have physical access to, so everything is done via remote. With that said, I noticed that regardless of physical or remote access, the SDRTrunk window is horribe at automatically scaling, or I cant resize it at all, even manually. So i run into situations where I actually have to resize different boxes and columns in the playlist editor just to even see the stuff I need to adjust. And this is even with a 1920x1080 monitor with 100% scaling on local and remote screens, but the window is still oversized. 

The main window opens and scales just fine, its the playlist editor thats the issue. The elements within the Playlist Editor window are fixed size and will not allow the window to be less than 1921x1568. (as reported by "xdotool selectwindow getwindowgeometry") And I also noticed that the maximize/window button between the close and minimize button does nothing for playlist editor either. Neither makes it bigger or smaller. 

Issue occurs at 1600 x 900 (16:9) aspect radio. By changing monitor resolution to 1280 x 1024 (5:4), the "drag to resize" line in the playlist editor will be visable and can be clicked and dragged to resize ONLY the elements in the page, not the window. This is somewhat of a temporary solution. But the Playlist Editor window will exceed display dimensions when screen resolution s 1600x900.

**To Reproduce**
1. Run SDRTrunk
2. Open Playlist Editor
3. Attempt to click and drag window edges to resize, and try clicking maximize / minimize buttons. 

**Expected behavior**
Neither of the actions above should resize window due to the bug.

**Screenshots**

**Application Log**
If applicable, include either the full application log,or a snippet of the error logging.

**Desktop (optional - complete the following information):**
 - OS: MX Linux v6.1.0-18 (AMD64) [Debian 6.1.76-1] 64bit. 
 - Dell OptiPlex 7010 - Intel Core i7-3770S @3.1ghz - 8GB DDR3 1600MHz.

**Additional context**
SDRTrunk group discussion regarding this... https://groups.google.com/g/sdrtrunk/c/5ZIksGBCeL8

**Comment by pauldonahue** [comment]
this also happens on Windows 10.19045.5011 JRE 1.8.0_231-b11
