### ISSUE TITLE
Receiving data but not audio playback

### ISSUE THREAD

**Issue by youcangetme** [DSheirer/sdrtrunk#204]
Hello! Thank you for the cool software.

I have tried to set the audio outputs but no luck. My system is some generic surround sound from RealTek. I can see the reception in the spectrum analyzer so I know the app is talking to the SDR. I do have a HDMI monitor with audio but I have also used headphones with the same results, not sure if that matters. I gave up on any meaningful audio coming out of Java a long time ago so not sure how to help you debug this.

**Comment by davidmckenzie** [comment]
Anything in the console output?
Anything in the events and messages panels for each channel?
Have you compiled + added JMBE? https://github.com/DSheirer/sdrtrunk/wiki/JMBE

**Comment by youcangetme** [comment]
Ah! OK, so I didn't have the channel enabled. Makes since.

Sorry for the alarm. Maybe a brief tutorial would help?
