### ISSUE TITLE
FR: Event view filters?

### ISSUE THREAD

**Issue by chudgoo** [DSheirer/sdrtrunk#205]
Would it be possible to add some filters to the event view so you could remove things like Register, Deregister, Response, Command, Query, Group Call, Telephone Interconnect, etc? 

I know this already exists in the Messages view. Would it be possible to reuse some of that code?
(in a nut shell I'd like to only see the calls themselves listed)

**Comment by DSheirer** [comment]
Yes.  I've downloaded the latest Jide JTable which supports filtering.  I'm planning to remove the filtering options on the messages table and replace it with the Jide version.  I'll add the Jide version in most of the places where there are tables of data, including the events table.

**Comment by DSheirer** [comment]
Implemented.
