### ISSUE TITLE
Hide talkgroups or radio IDs

### ISSUE THREAD

**Issue by cvk14** [DSheirer/sdrtrunk#2051]
**Is your feature request related to a problem? Please describe.**
I'm seeking to monitor one agency on a trunking radio service. They all fall in a range of radios, so I would like to hide the activity of radios outside of that range.

**Describe the solution you'd like**
I would like a flag on the playlist editor to "hide" - this should hide the talkgroup (or range) or the radio ID (or range). that should apply to the entire interface, thus hidden from the channel events, map, etc.

**Comment by DSheirer** [comment]
That would be too complicated to implement.
