### ISSUE TITLE
Add libusb DLLs to allow loading Windows ARM64 version

### ISSUE THREAD

**Issue by JVital2013** [DSheirer/sdrtrunk#2081]
**sdrtrunk Version**
v0.6.1 beta 3 - Windows ARM64 version

**Describe the bug**
SDRTrunk fails to load because libusb4java-1.3.0-win32-aarch64 is missing.

**To Reproduce**
Attempt to load the ARM64 build on any ARM64-based Windows 11 PC.

**Expected behavior**
libusb4java-1.3.0-win32-aarch64.jar needs to be included with sdrtrunk. Since this variant of libusb4java is not provided by the developer, I've attached a copy I built myself to this post: [libusb4java-1.3.0-win32-aarch64.zip](https://github.com/user-attachments/files/17611952/libusb4java-1.3.0-win32-aarch64.zip)

**Screenshots**
Before adding libusb4java-1.3.0-win32-aarch64.jar:
![image](https://github.com/user-attachments/assets/01a9ec05-cb92-4b16-a22c-3bc402de3bc4)

After adding libusb4java-1.3.0-win32-aarch64.jar:
![image](https://github.com/user-attachments/assets/afc24f31-807f-4a8d-b32c-e964e9415912)

**Comment by JVital2013** [comment]
Ah, missed one part - the libusb dll itself also needs to be added into SDRTrunk's `bin` folder. See attached:

[libusb-1.0-win32-aarch64.zip](https://github.com/user-attachments/files/17612012/libusb-1.0-win32-aarch64.zip)

**Comment by DSheirer** [comment]
@JVital2013 Thank you very much!  I'll get this added in.
