### ISSUE TITLE
Playlist saving all the time...

### ISSUE THREAD

**Issue by ImagoTrigger** [DSheirer/sdrtrunk#210]
sdrtrunk saves the playlist even when the playlist does not change.  this is a noticeable problem when my playlist xml file size is 10MB.  ive just gone ahead and commented out the schedulePlaylistSave() calls (besides running my entire setup from RAM)....

**Comment by ImagoTrigger** [comment]
hint: it's only due/with p25 channelmap?

**Comment by DSheirer** [comment]
It's only supposed to save the file at a max rate of once every 2 seconds when there have been one or more changes to aliases, channels, channel maps, or streaming configurations.

There can be a noticeable delay between when the change happens until the playlist is actually saved.

Are you seeing additional/recurring saves beyond the times when you're making changes?

**Comment by DSheirer** [comment]
Second question ... I'm planning on supporting multiple playlists in the near future, so that you can create custom playlists and don't have to have everything jammed into a single playlist.  Would that allow you to reduce the size of your playlist, if you could split it into multiple playlists and select one at runtime?

**Comment by ImagoTrigger** [comment]
i figured it out i tihnk

BROADCASTER_QUEUE_CHANGE is triggering it. 
![image](https://cloud.githubusercontent.com/assets/3333956/23445465/3cd7bff8-fe01-11e6-8b95-a569022f34d0.png)

**Comment by ImagoTrigger** [comment]
here is da fix

![image](https://cloud.githubusercontent.com/assets/3333956/23445604/24ba1cb2-fe02-11e6-8d34-5908cf0d33d9.png)

**Comment by ImagoTrigger** [comment]
as for the second question it is a non issue at this point ;-) my playlist does not need to be so big... would be nice to be able to run a separate playlist on each tuner from one instance of sdrtrunk, why else have a playlistmanager manager...

**Comment by DSheirer** [comment]
@ImagoTrigger thanks very much for tracking this down!
