### ISSUE TITLE
[wiki] updated instructions/FAQ for MacOS

### ISSUE THREAD

**Issue by n2ygk** [DSheirer/sdrtrunk#2112]
**Is your feature request related to a problem? Please describe.**
After getting SDRPlay API working on MacOS, I found a couple of gaps in the wiki documentation.

**Describe the solution you'd like**
See https://github.com/n2ygk/sdrtrunk-wiki/pull/1 as my suggestions. Unfortunately I can't do a PR against the actual sdrtrunk wiki.

**Comment by DSheirer** [comment]
All done!  Thanks for the inputs.
