### ISSUE TITLE
Enable logging for traffic channels

### ISSUE THREAD

**Issue by sysrun** [DSheirer/sdrtrunk#220]
Is it possible to log the contents of data calls for P25 somehow ?

**Comment by DSheirer** [comment]
I don't have an option to log the decoded messages from a traffic channel, but that's a good idea.

The decoded messages will show you the SNDCP data message contents if the protocol is IP/UDP or IP/TCP.

Is this what you're asking for, or are you looking for something like a packet capture?

**Comment by sysrun** [comment]
That would be awesome :)

**Comment by DSheirer** [comment]
-Add option to gui logging configuration editor to select logging for traffic channels.
-Update TrafficChannelManager to create a logging configuration instance that contains the traffic channel logging tag and add to the traffic channel configuration prior to starting via the ChannelProcessingManager.

**Comment by DSheirer** [comment]
Resolved under #299
