### ISSUE TITLE
Startup Screen with playlist options

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#221]
Create a startup screen that provides the user an option to continue with the previously saved channel settings in the playlist, or cancel all 'enabled' channels and start with no channels decoding.  

This should have a countdown timer that will default to the last setup after 5-10 seconds of delay.  Provide user a button to proceed with last configuration and a button to proceed without any channels enabled.

**Comment by ImagoTrigger** [comment]
This will allow multiple instances to run, I hope.  Right now I have to change the second instance's program name to SDRTrunk2
