### ISSUE TITLE
TrafficChannelManager does not allocate channels for Do Not Monitor aliases

### ISSUE THREAD

**Issue by CGUTH** [DSheirer/sdrtrunk#228]
As mentioned in the Google Group Thread:
https://groups.google.com/forum/#!topic/sdrtrunk/pLCvreoOOM4

If I set a TG to priority "Do Not Monitor", it will no longer stream, soon as I set any other priority it starts streaming those TG's again.

I have three different Icecast streams and it affects all three when I adjust the associated priorities.

- Chris KG7LER/WQWI942

**Comment by DSheirer** [comment]
Update the traffic channel manager to allow traffic channel allocation even if the alias is tagged as do not monitor to enable streaming audio.
