### ISSUE TITLE
Multiple active channels results in incorrect frequency values in the Events tab

### ISSUE THREAD

**Issue by sdrtrunkuser** [DSheirer/sdrtrunk#243]
With two (overlapping) simulcast P25 sites enabled, the frequencies in the "Events" tab are often (but not always) incorrect.

The values shown when the primary channel is selected are correct. With the secondary channel selected (normally in an 'Idle' state,) the frequencies vary from correct to some impossibly high value. Tuning and audio appear to still work w/o issue.

http://imgur.com/a/qL2nT

**Comment by DSheirer** [comment]
Sorry for the delay in responding ... if you can recreate this situation, could you copy/paste the contents of the channel details for the channel that is showing the incorrect frequencies and attach it back to this issue?  

There's a possibility that my parsing code for calculating the frequencies might need fixed.
