### ISSUE TITLE
soundcard dropout

### ISSUE THREAD

**Issue by rcummings14** [DSheirer/sdrtrunk#259]
i use a tapped scanner for my control channel. every so often i have to disable and enable the channel for it  to start decoding it again. not trying to be a pain or complain. just informing you of some of the issues i'm having so you can make this software the best it can be. fyi im using the new beta13

**Comment by DSheirer** [comment]
No worries, and thanks for reporting the issue.

Which decoder are you using?

**Comment by rcummings14** [comment]
C4fm

**Comment by DSheirer** [comment]
Closing.  Sound card input is no longer supported.
