### ISSUE TITLE
Unable to log control channel data.

### ISSUE THREAD

**Issue by vsboost** [DSheirer/sdrtrunk#264]
Hi there,

Love the program and noticed a small issue.

I was unable to log any data for a particular channel P25 - nothing was being displayed in the event_logs folder.

I noticed that the issue was that the name of the channel contained a tab at the end which prevented any data being saved.

for example  Name:  City P25<tab> will not log any data if you have something ticked, remove the tab and all is good.

Not a big deal but thought i would bring it to your attention.

**Comment by DSheirer** [comment]
This was resolved.
