### ISSUE TITLE
Alias with 2 control channels

### ISSUE THREAD

**Issue by Sparkz71** [DSheirer/sdrtrunk#293]
Minor problem.
I created an xyz alias with a talkgroup id: 7726.
I am monitoring 2 x P25 control channels from different sites. Same network.
When I receive both control/traffic channels, the alias is only converted to xyz on one channel & remains 7726 on the other.

**Comment by DSheirer** [comment]
Are both of the channel configurations specifying the same alias list name.  For the channel where the 7726 talkgroup does not get assigned the alias, do you see any of the other aliases working correctly?

**Comment by Sparkz71** [comment]
I have specified both control channels with the same alias list - P25.  It’s seems the alias list is ‘stuck’ to one control channel. I defined the talk group alias as 7726 = (eg) fire group. If I listen to 2 x P25 control ch, one detects talkgroup 7726 , as 7726 – ignoring the alias. The other channel converts 7726 to the ‘fire group’ alias. I am listening with ‘stereo’.  I don’t understand Java – just old school BASIC – I wish I could help further.

Regards.... Ian 

Sent from Mail for Windows 10

**Comment by DSheirer** [comment]
Could you please post your playlist.xml file here?

Note: if you have setup audio streaming, your streaming password will be listed in the file and would be available for anyone to see.  You can delete your streaming configuration(s) before posting it.

**Comment by Sparkz71** [comment]
False error, my mistake - Sorry! I apologise. Please close this issue. I had 2 similar alias list names & set the wrong list on 1 channel.
