### ISSUE TITLE
Adjust Bitrate For Cutom Icecast Stream

### ISSUE THREAD

**Issue by nomorecats** [DSheirer/sdrtrunk#297]
Hi Denny,

If possible, could users be able to define their on bitrate for Icecast2.4. I am currently hosting my own Icecast server and would like to decrease latency.

**Comment by DSheirer** [comment]
Changes to bitrate will primarily affect the audio quality (ie higher bitrates = better audio quality), but won't reduce latency.  

Are you trying to reduce the latency between transmission time and streaming time?  I think right now a call has to close out before it's queued for streaming which introduces a latency equal to the call duration, in addition to the streaming audio queue size.

**Comment by nomorecats** [comment]
Better audio quality would be nice too, I don't have Intellij to I would recompile it myself. Is there any way to output audio by means of the speaker talkgroup selectively? In past versions I've had to "block" all other talkgroups.

**Comment by DSheirer** [comment]
Audio (speaker) output is still controlled the same way using aliases by setting audio priority and/or setting a 'Do Not Monitor'

**Comment by DSheirer** [comment]
Additional bit rates added for streaming.
