### ISSUE TITLE
Audio Streaming Support

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#30]
Add support for Shoutcast/Icecast network streaming
-Multiple, simultaneous audio streams
-Stream designation by Alias/Talkgroup

Provide support for:
Sample Rate: 22050hz
Bit Rate: 16kbs CBR for a mono
Channels: 1 = Mono
ID3 Metadata tagging

**Comment by imagesafari** [comment]
This software is awesome. Thanks so much for your effort. With Audio streaming, it'd be cool to have a web interface to the recordings too -- like Trunking Recorder + Unitrunker. Happy to provide a demo link if you haven't seen it. The data is all there, just needs a web interface.

**Comment by DSheirer** [comment]
Thanks!  Yes, if you can post a link, I'll give it a look.

**Comment by imagesafari** [comment]
Link here: http://www.scannerbox.us/TrunkingRecorder/

I can give you a link to a running web interface so you see what it does via PM

**Comment by imagesafari** [comment]
I can't figure out how to send a PM on github.. drop me an email and I'll shoot you a link to a working Trunking Recorder. I've got some other ideas that I'd love to share / help with if I can. 

jon@anhold.com
