### ISSUE TITLE
No audio after gradle compile on Windows

### ISSUE THREAD

**Issue by endorphinrush** [DSheirer/sdrtrunk#307]
Not a bug just a suggestion.

If following "[Build the project](https://github.com/DSheirer/sdrtrunk#instructions)" instructions, sdrtrunk produces no audio. This is not resolved until adding jmbe back to <../build/libs>. 

<This would add gradle, download all project dependencies and build JAR>

Would this be considered a dependency that should be installed during build? If not another line might be useful to indicate the additional dependency needs.

**Comment by DSheirer** [comment]
The JMBE audio library is excluded from the normal build (and release) process due to potential copyright restrictions.  We leave it to the end-user to compile JMBE and co-locate the library in the execution folder to enable P25 audio decoding.

**Comment by endorphinrush** [comment]
No problem, I get that. It was just a suggestion for the readme file. Thanks for the hard work!

**Comment by chudgoo** [comment]
Would there be anything wrong with including a routine that checks for JMBE
and fetches/installs if needed?
You're not including the code itself in your software, but could provide an
automated way for it to be compiled. Maybe a prompt like "are you sure you
agree to the terms of the third party EULA?   Seems fairly safe from a
legal standpoint.... I think...  ???
