### ISSUE TITLE
GUI element scaling?

### ISSUE THREAD

**Issue by chudgoo** [DSheirer/sdrtrunk#313]
So when running in Win10 on a machine with a 4K screen, the entire interface goes microscopic.
In macOS, this scale as you'd expect and things are still visible and clickable.  Would implementing some kind of settings tab where things like UI scale could be set be possible or is this a java thing?  (and yes, I've tinkered with the scaling settings in win10. This only happens on >1080P screens)

**Comment by DSheirer** [comment]
I think this may be a Java issue.  I remember recently reading on the JDK dev forums that the Oracle folks were looking into this.

I could counter this by overriding (from default) all of the sizing and fonts, but that would be a maintenance nightmare doing it in Java Swing. 

I would like to eventually change the GUI over to JavaFX which allows you to use CSS style sheets to change every aspect of the GUI (size,color,rendering, etc).
