### ISSUE TITLE
Typo' in source code.     R820T mixer gain settings.   GAIN_153("153", 0x0F);

### ISSUE THREAD

**Issue by Sparkz71** [DSheirer/sdrtrunk#320]
Hi Denny,

As noted by Hans H in the google forum,
"Found a small bug.  In the Gain Mixer drop down the last list item is 153 which is out of numerical order..."

There seems to be  a typo in the source code.
 I found it @  line 775 (?) in sdrtrunk-0.3.3-beta.3\src\main\java\io\github\dsheirer\source\tuner\rtl\r820t\R820TTunerController.java  .

I don't understand java, but the hex value seems to be in order.  Looks like 153 is a typo. I assume it should be  a value above 161, 173? I assume the gain will still increase. above 161. 

Thanks,
Ian

**Comment by DSheirer** [comment]
I'll redo the labels for this.  The R820T2 tuner register document has the LNA gain settings listed as -12.0 db to +40.5 db, in steps of 3.5 db.

https://www.rtl-sdr.com/wp-content/uploads/2016/12/R820T2_Register_Description.pdf
