### ISSUE TITLE
Feature Request: Group inherited configuration

### ISSUE THREAD

**Issue by davidmckenzie** [DSheirer/sdrtrunk#333]
One for the backlog :)

Would be neat to be able to apply certain configuration at the "group" level for aliases, as the groups don't have much function at the moment. I'm thinking broadcast channel, audio priority, etc. If set on an individual alias it would override the settings on the group.

The use case for this would be to quickly mute a group of talkgroups, or to move things around different streams without clicking through tens of different aliases. I found myself getting RSI today when I wanted to mute all but a few talkgroups, and move a bunch to a different stream due to an active incident.

Thanks!
Dave

**Comment by DSheirer** [comment]
One current option is to use the column filter on the group column to isolate the aliases for a specific group and then select-all and use the multi-alias editor to apply/remove alias settings to the group as a whole.

There's an open issue to remove all broadcast channel settings from selected aliases, but most of the other group editing (add/remove) options can be applied to the group.
