### ISSUE TITLE
Create AM Squelch Control

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#35]
Create a squelch control for the AM decoder

**Comment by ah1102** [comment]
I would also like to see in the program noise reduction for analog FM and AM. I also noticed an echo in NFM.

The program may be more universal. With hackrf, it would be possible to have multichannel reception on the air or amateur radio.

**Comment by ah1102** [comment]
Dear developer! Enter squelch for AM. It is not difficult to add it for AM, taking it from the NBFM mode. Just add a similar feature for AM.

**Comment by DSheirer** [comment]
AM squelch control implemented in branch.  AM & FM now share common squelch control code.  Need to add dynamic channel noise floor monitoring to auto-adjust squelch threshold and change the squelch threshold to be a value that's added to the current noise floor.
![20230502_074623_screen_capture](https://user-images.githubusercontent.com/4079756/235658042-f3be24dc-6241-449c-a8ea-16ba2f48b7e7.png)

**Comment by DSheirer** [comment]
Closed via PR.
