### ISSUE TITLE
Not detecting SDRplay RSP1A

### ISSUE THREAD

**Issue by Azothyran** [DSheirer/sdrtrunk#356]
I have confirmed the SDR works in both SDRuno and HDSDR (with the extIO_*.dll plugin), but sdrtrunk does not appear to see my tuner. I have attempted this on three different machines with the same results. I have tried all of the latest betas after the stable release. I did attempt to run the stable release but received an error as follows:

`Error: Could not find or load main class gui.SDRTrunk
Caused by: java.lang.ClassNotFoundException: gui.SDRTrunk`

So I was unable to test it as a result.

I have seen other references to the SDRplay mentioning that support for the SDRplay series was built in. Is there something I could be missing?

Two of the machines I tested with are Windows 10, build 1803, the third machine was Windows 8.1 update 1.

![2018-06-15](https://user-images.githubusercontent.com/26119600/41487543-b8af84be-70ae-11e8-903a-01013d084f25.png)

**Comment by DSheirer** [comment]
sdrtrunk does not yet support sdrplay.
