### ISSUE TITLE
FEATURE REQUEST: Disable waterfall and/or spectral display CLI, settings, GUI toggle.

### ISSUE THREAD

**Issue by ScanCaster** [DSheirer/sdrtrunk#361]
If I missed this, point me to it, but I am not seeing a way to toggle the waterfall and spectral display off i the GUI or CLI.

Why would you want that?

For my use case, these are just not needed. I'd rather put resources into the CC log data, streaming, decoding than that display. 

I am sure its a useful think in some cases, but when you wan to control SDRTrunk via a remote connection be it XDMCP, SSH X, VNC thats a lot of data to send out. Data for me which is not really of use. If I was hunting signals or something, I am sure it would be a plus. Adding aliases, watching the CC data, etc.. is more important.

How would this work?

java -jar sdr-trunk -nowater -nospectral 

Then possibly some keyboard options: CTRL-ALT S toggle the spectral, CTRL -ALT W toggles the waterfall, and add it to the menu at the top.

Maybe you can put this on the feature request list for some time in the future. Thanks.

**Comment by DSheirer** [comment]
Feature request duplicates #96 

Merge #368 adds capability to enable/disable spectral display processing with setting persistent across user sessions.

CLI options will be added in a later milestone.
