### ISSUE TITLE
Bad C4FM reception since 0.3.4

### ISSUE THREAD

**Issue by smartynov** [DSheirer/sdrtrunk#378]
It seems that new decoder introduced in #338 breaks reception, at least for me. I compared all recent releases with same hardware setup (rtl-sdr + dipole antenna) and settings (p25 c4fm trunk), and `0.3.3-beta.3` is the last version that sounds good. Starting from `0.3.4-beta.1` voice gets interrupted and distorted (as it would be in case of weak signal). I would like to give additional info upon your request.

**Comment by DSheirer** [comment]
@smartynov Would you be able to get me a baseband recording using sdrtrunk, of either the control channel or one of the traffic channels that are not decoding correctly for you?  A 30+ second recording would be perfect.

Do you know who is the manufacturer of the P25 system (motorola, harris, etc.)?
