### ISSUE TITLE
Configuration option to display IDs in decimal rather than hexadecimal

### ISSUE THREAD

**Issue by davidmckenzie** [DSheirer/sdrtrunk#40]
Super low priority - just something for the "nice to have" list. Would be to good to be able to display talkgroup and unit IDs as decimal in the event log. Perhaps through right clicking anywhere in the log.

**Comment by DSheirer** [comment]
This would impact aliases and alias IDs.  Do you envision this being an either/or switch, so that the system uses all decimal values and users would setup their aliases with decimal values, and vice-versa for hexadecimal?

**Comment by davidmckenzie** [comment]
I was thinking just as a purely visual thing, nothing changing underneath, just choose whether to display the event log in dec or hex. Might it be easier to just display both values, e.g. "7730 (30512)"?

**Comment by vsboost** [comment]
Would love to see this as well.
