### ISSUE TITLE
tar.gz from download doesn't create a subdirectory

### ISSUE THREAD

**Issue by gbin** [DSheirer/sdrtrunk#44]
Conventionally the archive should decompress in a subdirectory.

Otherwise here is what happens:
cd ~/projects
tar xzvf tar xzvf ~/Downloads/sdrtrunk_20160101_0929_0.2.0.beta2.tar.gz
-> files everywhere ;)

should create files in sdrtrunk/*

**Comment by DSheirer** [comment]
I agree.  I'll fix this for the next release.
