### ISSUE TITLE
[feature request] Portable install

### ISSUE THREAD

**Issue by Tom-Neverwinter** [DSheirer/sdrtrunk#487]
can it install neatly onto the desktop. with configuration.

**Comment by DSheirer** [comment]
There's really no installation required, other than the sdr drivers required for windows and the udev permissions for linux.  

You can ask questions like this in the google support group.  

If there's still an issue to document, please add to some more details, or you can close this issue.

**Comment by Tom-Neverwinter** [comment]
is it possible to export the config for stations? I have been having issues with skywave Linux and the cursed pulse audio bug. I have been manually entering the stations in and the respective alias's (hopefully skywave linux will receive an update as well as your wonderful software.)

**Comment by Tom-Neverwinter** [comment]
That will work, I will simply write up a bash file for making the transfer easier. Thank you!!! I love your software!
