### ISSUE TITLE
Add interface to RadioReference.com

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DSheirer/sdrtrunk#5]
```
Add interface to radioreference.com to support retrieval of system, site and 
channel data into the application.
```

Original issue reported on code.google.com by `dennis.s...@gmail.com` on 6 May 2014 at 1:10

**Comment by imagesafari** [comment]
In the meantime, here's a perl script to generate the alias entries to be included in the playlist.xml file from Radio Reference talkgroup csv downloads:

[make_playlist.xml](https://gist.github.com/imagesafari/e41160e182631271bf16942b520924dc)

**Comment by chudgoo** [comment]
I recently moved to a city with a MUCH more complicated set of systems and was wondering what the status of this RR API integration was.
I ended up using the perl script written by @imagesafari and things worked out well for the TGID info, but given that one particular system ended up having something like 30 control channels, a full implementation would be great.

**Comment by Twilliamson3** [comment]
I have built a simple webapp to allow copy and paste data from a website and format it into the correct form for a playlist.  Similiar to @imagesafari perl script. 

http://trippwilliamson.com/digitalscanner/talkgroup.php

**Comment by ImagoTrigger** [comment]
here is my latest, also a perl script...  updated for V3

https://gist.github.com/ImagoTrigger/88518ca344188ea353ee4747d2986437
