### ISSUE TITLE
sdr-trunk.bat does not like spaces in folders

### ISSUE THREAD

**Issue by vsboost** [DSheirer/sdrtrunk#501]
Tried to run sdr-trunk.bat and get.

C:\Users\Me\Desktop\Radio & Phone\SDR\sdr-trunk-0.4.0-alpha.7-windows-x64\sdr-trunk-windows-x64\bin>sdr-trunk
'Phone\SDR\sdr-trunk-0.4.0-alpha.7-windows-x64\sdr-trunk-windows-x64\bin\' is not recognized as an internal or external command,
operable program or batch file.
'Phone\SDR\sdr-trunk-0.4.0-alpha.7-windows-x64\sdr-trunk-windows-x64\bin\..' is not recognized as an internal or external command,
operable program or batch file.

ERROR: JAVA_HOME is set to an invalid directory: C:\Users\Me\Desktop\Radio

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

If i copy it to another folder where there are no spaces everything runs fine. for eg. c:\Users\Me\sdrtrunk

**Comment by DSheirer** [comment]
This would be a bug in the gradle packager plugin that provides the canned launch scripts.  I'll submit a ticket against their library.

I'll leave this ticket open to track the issue through resolution (ie an update from the plugin author).

**Comment by ImagoTrigger** [comment]
rem out lines 19 and 21 in sdr-trunk.bat so it looks like this

@rem set JAVA_HOME=%~dp0..

@rem set JAVA_HOME=%JAVA_HOME:"=%

**Comment by vsboost** [comment]
Still didn't work, was easier to remove the & from my folder name from "Radio & Phone" to just Radio

Can close this one if you like.
