### ISSUE TITLE
alpha 8 error win x64 UnsatisfiedLinkError

### ISSUE THREAD

**Issue by vsboost** [DSheirer/sdrtrunk#521]
Error occurred during initialization of boot layer
java.lang.UnsatisfiedLinkError: java.io.UnixFileSystem.initIDs()V

**Comment by DSheirer** [comment]
Are you trying to run this on a 64-bit x86 machine?

**Comment by vsboost** [comment]
64bit Windows 10
Previous alpha7 worked no problem

**Comment by davidcomtois** [comment]
A fresh extraction gives a Java_Home error but if you copy alpha 8 over alpha 7, then I get the error above..

**Comment by vsboost** [comment]
Strange, re-downloaded it - extracted it - ran it - works...
