### ISSUE TITLE
Support for OSX < 10.12

### ISSUE THREAD

**Issue by russinnes** [DSheirer/sdrtrunk#555]
Compiled binary requires OSX >10.12 (Sierra). Versions < 10.12 do not support _clock_gettime in osx native libusb4java.dylib (when loading i.g.d.s.r.RecordingSourceManager)

**Comment by DSheirer** [comment]
I don't have any means to test older versions of OSX.  I'm updating minimum system requirements to be OSX 10.14 or higher.
