### ISSUE TITLE
Alias P25 Numbers and letters

### ISSUE THREAD

**Issue by riggs498** [DSheirer/sdrtrunk#557]

**Comment by riggs498** [comment]
Greetings,

I don't know if I am missing something. All my county hex are 232e, etc. There is no way for me to enter this in to the audio/identifier field. Should this be done in a different location? 

Example

DEC     HEX     Alpha Tag  DES             Tag
54516   d4f4     XSO-09     Statewide     Interop

When I go under audio/identifier it only lets you place in numbers. 

Thanks in advance.

**Comment by hans109h** [comment]
sdrtrunk uses the decimal format, so use the DEC which is provided right next to your hex code.

**Comment by riggs498** [comment]
Thanks fixed
