### ISSUE TITLE
trouble recording audio

### ISSUE THREAD

**Issue by chrkyl** [DSheirer/sdrtrunk#562]
I am having issues recording audio from trunked channels.  I can hear the chatter and have it set to record, but when I go to folder where the recording are its just static.  Any ideas where I am messing up?

**Comment by DSheirer** [comment]
Make sure you're setting up the aliases correctly and selecting record for each alias.  Audio recordings are triggered by the settings for each aliased radio or talkgroup id.

There are also record options listed in the recording tab, but those are not for recording call audio.  They're for recording the baseband signal and the demodulated bit stream.

You can also get help for recordings in the user support group: https://groups.google.com/forum/#!forum/sdrtrunk
