### ISSUE TITLE
MBECallSequenceRecorder.writeCallSequence is trying to save files with a "p:" in the filename.

### ISSUE THREAD

**Issue by davidbelle** [DSheirer/sdrtrunk#572]
Looks like any patched channels have a "P:" in the identifiers, and when the MBECallSequenceRecorder.writeCallSequence method tries to save the mbe files it is unable to because you can't have a ":" in the filename. 

Workaround: 

`sb.append("_").append(sequence.getToIdentifier().replace(":",""));`
and 
`sb.append("_").append(sequence.getFromIdentifier().replace(":",""));`

**Comment by DSheirer** [comment]
Thanks!  I added your fix to both the MBE recorder and to the audio recorders.
