### ISSUE TITLE
Recording P25 audio

### ISSUE THREAD

**Issue by MartinsZB** [DSheirer/sdrtrunk#579]
Hi! I was using sdrtrunk v0.3.3-beta.3 in Skywave linux and now I installed newest sdrtrunk (sdr-trunk-0.4.0-alpha.9-linux-x64.zip) under Debian.
In old version under Channel/Recording there was 3 options - Audio, Baseband I/Q and Traffic Channel Baseband I/Q.
In the new version there are Baseband I/Q, Traffic Channel Baseband I/Q, Demodulated Bitstream and Traffic Channel Bitstream, but no option to record audio.
Is there an option somewhere to record the audio like in old version?
Thanks for the nice tool! Martins

**Comment by DSheirer** [comment]
The AM and NBFM demodulators have a record audio option.  For all of the trunking protocols, you have to create an alias list and at least one alias.  Attach to the alias a recordable option and a talkgroup or talkgroup range of values.

When a talkgroup is active, it matches an alias and if the alias is marked recordable, then the audio is recorded.
