### ISSUE TITLE
Program not launching

### ISSUE THREAD

**Issue by RCCRAFT1** [DSheirer/sdrtrunk#587]
Hello. 

Do you understand why the program is not launching? 
It gives me errors about java home set to something else.
Thanks!

**Comment by DSheirer** [comment]
Make sure you're downloading the released version and unzip it.  Once unzipped, the bin directory is in the root folder where you unzipped it.  The release comes with Java, so the java home variable should already be set.

You can post user questions in the google support group: https://groups.google.com/forum/#!forum/sdrtrunk

Issues are for reporting bugs or requestion enhancements to the software.
