### ISSUE TITLE
Add DMR Decoder

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DSheirer/sdrtrunk#6]
```
Add decoder support for Digital Mobile Radio/Moto-TRBO decoder.
```

Original issue reported on code.google.com by `dennis.s...@gmail.com` on 6 May 2014 at 11:31

**Comment by spartancain** [comment]
Due to the exceptional breakdown you provide in SDRTrunk of the data stream itself and the specific messages received, SDRTrunk has a very useful professional application as a makeshift test set for digital functionality (as used by a tech stuck without a digital service monitor).

That usage would be greatly enhanced by the ability to view the data stream from a TRBO radio. For that reason, I respectfully request that this enhancement be completed as soon as reasonable possible as you continue to develop this outstanding software.

Thank you for all your hard work. I have only recently begun using SDRTrunk, and I am absolutely bowled over by the quantity of features and the clear dedication, persistence, and skill you have put into developing it. My life as a radio technician with hi-tech hardware to fix and low-tech test hardware to use has been measurably improved by this application. Thank you again.

**Comment by DSheirer** [comment]
I'm glad it's proving useful for you.  Once I get build 0.2.0 finalized, I'll be starting on the DMR decoder next.

**Comment by truedaystar** [comment]
I have one local dept that user DRM that I would love to decode.. So Add the vote in for me..   I love the software,,  I have a little to learn, like calibrating my tuners, but I will get there when I get time to set down and do it.

**Comment by DrekiDegga** [comment]
I have had my eye on this feature request for some time now and I would just like to say that I would love to be able to use sdrtrunk to decode DMR/mototrbo/capacityplus. Currently there is no good way to do this with available software So if DMR was added to sdrtrunk it would be the only decent option for trunking DMR.

Thanks for the work you do for sdrtrunk.

**Comment by maozhenyu123** [comment]
@DSheirer I've been trying to add DMR functionality to sdrtrunk, and if possible, I will do TETRA after that. 
I copied part of codes for P25 phase I because they are almost same on modulation level. But the Dibits I got did not match with DMR SYNC. 

Since DMR is 4FSK(+/-648HZ, +/-1944HZ) modulated, but P25 is C4FM(+/-600HZ and +/-1800HZ). Does that mean the current DQPSKDemodulator is not going to work with DMR? 
Just wanna get a place to start.

**Comment by DSheirer** [comment]
Since the deviation of the signal is a little bit wider than P25 C4FM, expand the baseband filter cutoff frequency to ensure the signal isn't being distored.

You may have to change the symbol gain value being passed to the InterpolatingSampleBuffer.  Phase 1 decoder uses a value of 0.3 and Phase 2 uses a value of .01

I normally add support for new decoders to the DemodulatorViewerFX application first so that I can visually monitor the performance of the decoder against a real-world signal and I adjust the filter and gain values until I'm happy with the symbol lock-on and tracking performance.  The viewer application allows you to manually step through a recording.  Warning: the viewer's coding has a lot of warts and is just a dev utility that I use.

**Comment by maozhenyu123** [comment]
> Since the deviation of the signal is a little bit wider than P25 C4FM, expand the baseband filter cutoff frequency to ensure the signal isn't being distored.
> 
> You may have to change the symbol gain value being passed to the InterpolatingSampleBuffer. Phase 1 decoder uses a value of 0.3 and Phase 2 uses a value of .01
> 
> I normally add support for new decoders to the DemodulatorViewerFX application first so that I can visually monitor the performance of the decoder against a real-world signal and I adjust the filter and gain values until I'm happy with the symbol lock-on and tracking performance. The viewer application allows you to manually step through a recording. Warning: the viewer's coding has a lot of warts and is just a dev utility that I use.

Awesome, it works!! I set the baseband filter cutoff to be 6100 rather than 5100, now SYNC can be detected. BTW, is the phase change still gonna be 45 degrees(since modulation index is now 0.27 rather than 0.25)

**Comment by DSheirer** [comment]
The phase change detector(s) work by detecting the sync patterns that will be transmitted when the PLL locks at +/- 90 degrees and 180 degrees.  You'll have to create these 3 sync patterns as derivatives from the normal sync pattern.  

If you look at the dibit/symbol plots for a normal PLL lock, then imagine rotating the entire constellation of dibits/symbols + or - 90 degrees and 180 degrees to formulate what the derivative sync patterns will be.

**Comment by DSheirer** [comment]
I just re-read what you posted and think I may have answered the wrong question.  

The differential decoder calculates the current symbol as the difference between the current symbol measurement and the previous symbol measurement and then the PLL locks onto this derived current symbol as a polar-aligned constellation instead of an offset QPSK (45 degree rotated) constellation to make it easier to calculate the phase error.

**Comment by maozhenyu123** [comment]
I've finished a startup at https://github.com/maozhenyu123/sdrtrunk/commit/c88fb9d46207544b490a5d4fadd6c30ae1e8c72e.
Now it can recognize different frame and message.

I think I have to do a little bit adjustment to the filter because sometimes it will miss some sync.

**Comment by DSheirer** [comment]
@maozhenyu123 Wow!  You've made a great bit of progress.  If I remember correctly, some of the DMR voice frames (b-f) do not have a sync pattern and that might be causing some of the sync loss.

**Comment by maozhenyu123** [comment]
@DSheirer Yes, voice frame b-e does not come with a SYNC pattern. But there is still 50%+ chance of missing a VOICE_FRAME_A, and it only happened when I am using a mobile radio.

**Comment by DSheirer** [comment]
There's a FilterViewer where you can visualize the parameters that you're using for your filter.  Modifiy the getFilter() method and copy your FIRFilterSpecification into that method and it will pop up a graphical display of the filter that's being used.

**Comment by maozhenyu123** [comment]
@DSheirer Unfortunately, I am not good at doing those stuff(not sure what is the ideal situation). If possible, could you plz help me to do this.

I am still working at higher level and now it supports CSBK/VLC/TLC parsing/validation and voice frame parsing as well. 
New commit: https://github.com/maozhenyu123/sdrtrunk/commit/c6d8012b96a28a4d7c2f0f9622daad7cddf7dbc7

**Comment by DSheirer** [comment]
I should have some time this weekend ... I'll see what I can do.

By the way ... there's already a DMR 3/4 rate Trellis decoder in the code base: ViterbiDecoder_3_4_DMR.

**Comment by maozhenyu123** [comment]
Nice. 
I realized sometime the program lost sync(when there is no transmission) and never get back when there is a new transmission. But I can definitely see some repeating pattern(but just not match with DMR sync). Is that coming due to the phase error(90 CW, CCW, 180)?

**Comment by DSheirer** [comment]
You're probably right about the PLL locking on with a phase error.  Calculating each of the 3 phase error patterns for each sync pattern is going to produce 27 variants to check.  

I had an idea to update the MultiSyncPatternMatcher so that it would only check the sync variants when it was in a lost sync state.  That would minimize the overhead of checking all patterns all the time.

**Comment by maozhenyu123** [comment]
I am not sure how to calculate a phase error.

**Comment by DSheirer** [comment]
No worries.  I was going to do it and send but ran out of time.  I'll try to work on those this weekend and send to you.

**Comment by DSheirer** [comment]
@maozhenyu123 Here's the phase inversion symbols.  I included code and explanations so that you can see how the derived phase inverted sync symbols are calculated.

cheers,
Denny
[Phase Inversion Sync Symbols.txt](https://github.com/DSheirer/sdrtrunk/files/4190971/Phase.Inversion.Sync.Symbols.txt)

**Comment by maozhenyu123** [comment]
@DSheirer Unfortunately, none of those sync was detected when there is sync-lost then re-sync. I am trying to figure out why.

**Comment by ah1102** [comment]
I would like to see a DMR decoder. On github there is a DSD repository with source codes. You can see how it is implemented there.

**Comment by maozhenyu123** [comment]
> I would like to see a DMR decoder. On github there is a DSD repository with source codes. You can see how it is implemented there.

Try my branch on https://github.com/maozhenyu123/sdrtrunk/tree/dmr-function

**Comment by ah1102** [comment]
Give thanks! But I would like to see DMR in the main branch of the project. Here are all the latest changes.

**Comment by ah1102** [comment]
Some errors at the end of the package
![Снимок экрана 2020-05-07 в 14 12 15](https://user-images.githubusercontent.com/58341369/81288289-05b7fb80-906d-11ea-83d1-0ef6eb4ac97a.png)

After a short time, the terminal stops displaying the received packet and "CONTROL" stops displaying yellow.
![Снимок экрана 2020-05-07 в 14 13 02](https://user-images.githubusercontent.com/58341369/81288392-3ac44e00-906d-11ea-812d-cedd1f93ead1.png)

In the window "Messages" such errors
![Снимок экрана 2020-05-07 в 14 15 56](https://user-images.githubusercontent.com/58341369/81288467-60515780-906d-11ea-904a-2b5087fdb80a.png)

My settings
![Снимок экрана 2020-05-07 в 14 13 18](https://user-images.githubusercontent.com/58341369/81288497-6f380a00-906d-11ea-9d61-c5214870d8d1.png)

I have never heard voices. Does your decoder support voice? Can you tell me how to configure?

**Comment by maozhenyu123** [comment]
> Some errors at the end of the package
> ![Снимок экрана 2020-05-07 в 14 12 15](https://user-images.githubusercontent.com/58341369/81288289-05b7fb80-906d-11ea-83d1-0ef6eb4ac97a.png)
> 
> After a short time, the terminal stops displaying the received packet and "CONTROL" stops displaying yellow.
> ![Снимок экрана 2020-05-07 в 14 13 02](https://user-images.githubusercontent.com/58341369/81288392-3ac44e00-906d-11ea-812d-cedd1f93ead1.png)
> 
> In the window "Messages" such errors
> ![Снимок экрана 2020-05-07 в 14 15 56](https://user-images.githubusercontent.com/58341369/81288467-60515780-906d-11ea-904a-2b5087fdb80a.png)
> 
> My settings
> ![Снимок экрана 2020-05-07 в 14 13 18](https://user-images.githubusercontent.com/58341369/81288497-6f380a00-906d-11ea-9d61-c5214870d8d1.png)
> 
> I have never heard voices. Does your decoder support voice? Can you tell me how to configure?

It does support voice. But it seems all data are CSBK-IDLE, which means there is no traffic. If a voice frame comes, it will show something like "Voice Frame A"

**Comment by ah1102** [comment]
Are my settings correct? Do you also get these errors or not?

**Comment by maozhenyu123** [comment]
> Are my settings correct? Do you also get these errors or not? Can I listen to two DMR sites at the same time?

My bad, should be fixed now.

**Comment by ah1102** [comment]
Now I will rebuild

**Comment by ah1102** [comment]
At first everything was fine, and then the output of packages in the linux terminal stopped, and in the sdrtrunk window this appeared
![Снимок экрана 2020-05-07 в 14 36 27](https://user-images.githubusercontent.com/58341369/81290245-6563d600-9070-11ea-94f3-b7014d70112f.png)

**Comment by maozhenyu123** [comment]
Is there any transmission on the spectrum? I realized when the transmission stopped at first time, the decoder might not work after that if you do not restart it because it's not detecting SYNC anymore. That might be a PLL problem but I don't know how to fix it

**Comment by ah1102** [comment]
Probably so, for clarity

![Снимок экрана 2020-05-07 в 14 43 22](https://user-images.githubusercontent.com/58341369/81290687-326e1200-9071-11ea-9e66-81e42906046c.png)

**Comment by maozhenyu123** [comment]
BTW, this program does not decode the signal from my mobile station. The demodulation does not correctly worked as I expected. I think I will need to ask someone for help.

**Comment by ah1102** [comment]
I am just learning programming. Tell me, does lsm or c4fm mode matter in your dmr decoder, what should I choose from the list?

**Comment by maozhenyu123** [comment]
No, DMR use 4FSK.

**Comment by ah1102** [comment]
Apparently, when a voice appears, such packets go, but I don’t hear anything. I have JMBE 1.0.4 and P25 is decoded.

`BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, BUSY
BS DATA, CC: 12 >>> [TermW/LC] Group Voice Service Options : NONEMG/No priority, TG = 12, ID = 131, channelId = 0 >>> >>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 1A, IDLE
BS DATA, CC: 12 >>> [IDLE]>>> TS = 0B, IDLE
Lost Sync of TS = 0, at 1588853981687 
Lost Sync of TS = 1, at 1588853981740 `

**Comment by maozhenyu123** [comment]
This is not a voice frame but a channel control frame. The actual voice frame should be on the channel assigned according to the control frame.

**Comment by ah1102** [comment]
I don’t know, some mistakes are coming. What could it be? I tried to change the frequency +/-, but it did not bring any result.

![Снимок экрана 2020-05-07 в 15 28 58](https://user-images.githubusercontent.com/58341369/81294465-9c89b580-9077-11ea-833d-9327bf03a7cb.png)

**Comment by maozhenyu123** [comment]
Hmm, interesting. This is a voice frame but seems not valid(may be encrypted?). This release does not come with encryption detection.

**Comment by ah1102** [comment]
I checked with dsd and there the voice is not encrypted.
![Снимок экрана 2020-05-07 в 15 47 43](https://user-images.githubusercontent.com/58341369/81296281-53873080-907a-11ea-8077-b0f06765efed.png)

**Comment by ah1102** [comment]
And you have implemented the function:
1) non / inverted DMR / MOTOTRBO signal
2) QPSK modulation auto detection threshold
3) Symbol buffer size for QPSK decision point tracking
4) Min / Max buffer size for QPSK decision point tracking

Can you check how and compare how it is implemented in dsd https://github.com/szechyjs/dsd? There is a wiki where you can read

**Comment by ah1102** [comment]
It seems that the DMR, in which firefighters work in our city, does not demodulate your decoder. But he demodulates the ham radio in DMR. But in both cases, I see errors in java files in the terminal. It must be modified. Because DSD demodulates everyone in the DMR.

**Comment by ah1102** [comment]
So I found another DMR decoder project - https://github.com/IanWraith/DMRDecode. This is the same DSD rewritten from "C" to "Java". 
 The program compiles in IJ, but errors are highlighted in red. And in the DMR decoder program itself, the audio device does not switch, so I can’t even check it. Then, it is not clear where the program outputs the sound.

![Снимок экрана 2020-05-09 в 09 02 28](https://user-images.githubusercontent.com/58341369/81465691-6ca3f480-91d4-11ea-9383-5d4b759a926e.png)

**Comment by cmartus** [comment]
I've done some testing with the dmr-function-denny-edits2 branch and get errors along the line of encrypted voice. Using an AnyTone D868UV, Simplex TS1 TG99.

`ERROR i.g.d.d.f.c.o.ChannelOutputProcessor - Error while processing polyphase channel samples  [155MB/321MB 48%]
java.lang.NullPointerException: null
	at io.github.dsheirer.edac.ReedSolomon_12_9.checkReedSolomon(ReedSolomon_12_9.java:320)
	at io.github.dsheirer.module.decode.dmr.message.data.lc.LCMessageFactory.createFull(LCMessageFactory.java:49)
	at io.github.dsheirer.module.decode.dmr.message.data.DataMessageWithLinkControl.getLCMessage(DataMessageWithLinkControl.java:61)
	at io.github.dsheirer.module.decode.dmr.message.data.DataMessageWithLinkControl.getIdentifiers(DataMessageWithLinkControl.java:79)
	at io.github.dsheirer.alias.action.AliasActionManager.receive(AliasActionManager.java:58)
	at io.github.dsheirer.alias.action.AliasActionManager.receive(AliasActionManager.java:43)
	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:152)
	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:59)
	at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:103)
	at io.github.dsheirer.module.decode.Decoder$MessageDistributor.receive(Decoder.java:96)
	at io.github.dsheirer.module.decode.dmr.DMRMessageProcessor.dispatch(DMRMessageProcessor.java:104)
	at io.github.dsheirer.module.decode.dmr.DMRMessageProcessor.receive(DMRMessageProcessor.java:61)
	at io.github.dsheirer.module.decode.dmr.DMRMessageProcessor.receive(DMRMessageProcessor.java:39)
	at io.github.dsheirer.module.decode.dmr.DMRMessageFramer.processDataBurst(DMRMessageFramer.java:316)
	at io.github.dsheirer.module.decode.dmr.DMRMessageFramer.burstDetectedWithSync(DMRMessageFramer.java:334)
	at io.github.dsheirer.module.decode.dmr.DMRBurstDetector.parseBurst(DMRBurstDetector.java:123)
	at io.github.dsheirer.module.decode.dmr.DMRBurstDetector.syncDetected(DMRBurstDetector.java:71)
	at io.github.dsheirer.bits.DMRSoftSyncDetector.checkSync(DMRSoftSyncDetector.java:59)
	at io.github.dsheirer.bits.MultiSyncPatternMatcher.receive(MultiSyncPatternMatcher.java:96)
	at io.github.dsheirer.module.decode.dmr.DMRSyncDetector.receive(DMRSyncDetector.java:128)
	at io.github.dsheirer.module.decode.dmr.DMRBurstDetector.receive(DMRBurstDetector.java:98)
	at io.github.dsheirer.module.decode.dmr.DMRMessageFramer.receive(DMRMessageFramer.java:180)
	at io.github.dsheirer.module.decode.dmr.DMRMessageFramer.receive(DMRMessageFramer.java:54)
	at io.github.dsheirer.sample.Broadcaster.broadcast(Broadcaster.java:152)
	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:59)
	at io.github.dsheirer.dsp.psk.PSKDemodulator.broadcast(PSKDemodulator.java:58)
	at io.github.dsheirer.dsp.psk.DQPSKDecisionDirectedDemodulator.calculateSymbol(DQPSKDecisionDirectedDemodulator.java:88)
	at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:115)
	at io.github.dsheirer.dsp.psk.PSKDemodulator.receive(PSKDemodulator.java:89)
	at io.github.dsheirer.module.decode.dmr.DMRStandardDecoder.receive(DMRStandardDecoder.java:109)
	at io.github.dsheirer.module.decode.dmr.DMRStandardDecoder.receive(DMRStandardDecoder.java:43)
	at io.github.dsheirer.sample.buffer.ReusableBufferBroadcaster.broadcast(ReusableBufferBroadcaster.java:42)
	at io.github.dsheirer.sample.buffer.ReusableBufferBroadcaster.broadcast(ReusableBufferBroadcaster.java:23)
	at io.github.dsheirer.sample.Broadcaster.receive(Broadcaster.java:59)
	at io.github.dsheirer.sample.buffer.ReusableComplexBufferAssembler.flush(ReusableComplexBufferAssembler.java:158)
	at io.github.dsheirer.sample.buffer.ReusableComplexBufferAssembler.receive(ReusableComplexBufferAssembler.java:132)
	at io.github.dsheirer.sample.buffer.ReusableComplexBufferAssembler.receive(ReusableComplexBufferAssembler.java:144)
	at io.github.dsheirer.dsp.filter.channelizer.output.OneChannelOutputProcessor.process(OneChannelOutputProcessor.java:97)
	at io.github.dsheirer.dsp.filter.channelizer.output.ChannelOutputProcessor.processChannelResults(ChannelOutputProcessor.java:124)
	at io.github.dsheirer.dsp.filter.channelizer.PolyphaseChannelSource.processSamples(PolyphaseChannelSource.java:248)
	at io.github.dsheirer.source.tuner.channel.TunerChannelSource$ScheduledIntervalProcessor.run(TunerChannelSource.java:321)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)`
