### ISSUE TITLE
sdr-trunk-0.4.0-beta.2. The input line is too long.

### ISSUE THREAD

**Issue by Hermite123456** [DSheirer/sdrtrunk#619]
Hello Dennis,

I tried the new build from scratch on Win 10/64 (gradlew.bat clean build).

My JAVA info is as follows:
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

Find below the build log.

![beta_2_build_log](https://user-images.githubusercontent.com/54645050/70942896-a86bd100-201d-11ea-9a72-d5e4f7e82561.jpg)

**Comment by DSheirer** [comment]
You're command line is too long.  Move your source code repo up to a higher directory so that the total path length doesn't exceed 255 characters.
