### ISSUE TITLE
USBMasterProcessor Servicing Thread Revisit Rate Should Be A User Configurable Item

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#652]
Either expose the Processor thread scheduled revisit rate setting to the user preferences so that user's with many tuners can adjust it, or possibly change the rate adaptively based on the number of tuners that are being used. 

https://groups.google.com/forum/#!topic/sdrtrunk/87oGoT5O3Tc

**Comment by ImagoTrigger** [comment]
very nice. i get the warning but it seems to work smooth.

6Mhz airspy mini
2.560mhz r820t
2.560mhz r820t

^--  on one bus  

below image shows all tuners locked in use

![Untitled](https://user-images.githubusercontent.com/3333956/74500687-4ad4f300-4ead-11ea-9181-1e144845a95b.jpg)

👍

**Comment by DSheirer** [comment]
@ImagoTrigger when I use my airspy at full 10MHz rate along with a 2.4MHz RTL dongle, on one bus it seems to work fine, but on the other, I get lots of dropped packets and choppy audio.  It's very visible in the spectral display also, with lots of horizontal lines where the data losses occur.
