### ISSUE TITLE
doesn't detect both of my identical rtl dongles

### ISSUE THREAD

**Issue by HuRRiK41N** [DSheirer/sdrtrunk#661]
beta version 4 only detects one dongle. I think they have the same serial number 000000001, but it shows up as two separate dongles in sdr#

**Comment by hans109h** [comment]
Change the serial number so they each are unique.  Google the software requirement.

**Comment by DSheirer** [comment]
@HuRRiK41N does the second tuner show up in the tuner's tab?  If not, are you seeing any error messages in the console window when the application starts up?

As @hans109h mentioned, you'll need unique serial numbers for each dongle for sdrtrunk to configure each of them properly.

**Comment by HuRRiK41N** [comment]
ive since fixed it by trying the port on the opposite side of my laptop

**Comment by DSheirer** [comment]
Very good.  I'll close this ticket.
