### ISSUE TITLE
AudioSegment Ignoring Do Not Monitor For Initial Aliased Identifiers

### ISSUE THREAD

**Issue by LordDonkey** [DSheirer/sdrtrunk#676]
With this mornings commit, the do not monitor priority is not working.

**Comment by DSheirer** [comment]
@LordDonkey Thanks.  I'll get this fixed ASAP.

**Comment by LordDonkey** [comment]
The issue persists with the latest build.

**Comment by 49handyman** [comment]
confirmed yesterday in my new builds

**Comment by DSheirer** [comment]
@LordDonkey @49handyman thanks, I'll do some more testing.
