### ISSUE TITLE
Streaming to Icecast 2.4.4 Server

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#690]
Test connections to Icecast 2.4.4 server.

Current code is only tested against 2.4.2 servers.

**Comment by dlsauer** [comment]
Testing with Harris system audio to 2.4.4 on Kubuntu 14.04!

Loud and clear

Connects.. fine..

Stream PERFECT!

METATAGS  FAIL -FROM UNKNOWN to UNKNOWN. :( :( :(

**Comment by hans109h** [comment]
Same here.  just to clarify, the metatags being sent to icecast (or at least icecast is displaying) is "TO: UNKNOWN FROM: UNKNOWN" for all clips.

**Comment by sdevine01** [comment]
I seem to have it working with win32 Icecast 2.4.4.  Metadata also seems to be working.

**Comment by DSheirer** [comment]
Ok.  I think with the metadata fix in 0.4.0 beta 8 this ticket is resolved.  Thanks to everyone for the feedback.
