### ISSUE TITLE
feature  - save multi-freq delay in preferences

### ISSUE THREAD

**Issue by 49handyman** [DSheirer/sdrtrunk#699]
would be nice. i have to reset every time i restart. which is often since its on my normal laptop i use at home and fairly short, micro usb cables pop out so easy when i'm moving around. no auto restart on the usb or hackrf usb enable after it looses power.

**Comment by DSheirer** [comment]
Bug.

ChannelMultiFrequencyPreference:40 - set initial value to null

**Comment by DSheirer** [comment]
Thanks for the bug report!
