### ISSUE TITLE
Add Support for Aliasing AMBE Tones

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#708]
Version 0.4.0 beta 7 added full support for generating AMBE tone identifiers that are broadcast as part of the audio.

Create an Alias Identifier (just like a talkgroup or radio id) that allows the use to specify a tone or a multi-tone sequence, or DTMF sequence. 

This will allow an alias to be correlated to an AMBE tone sequence and then Alias Actions (beep, script, etc) can be applied.

**Comment by ZacharyDuBois** [comment]
QCII decoding! :)
