### ISSUE TITLE
APCO-25 "Talkgroup range" does not work

### ISSUE THREAD

**Issue by ah1102** [DSheirer/sdrtrunk#720]
APCO-25 "Talkgroup range" does not work.  SDRTrunk software version 0.4.0 b8

![Снимок экрана 2020-03-30 в 13 13 02](https://user-images.githubusercontent.com/58341369/77902758-62fca800-728a-11ea-905b-c5743cf5c2a5.png)

![Снимок экрана 2020-03-30 в 13 13 26](https://user-images.githubusercontent.com/58341369/77902816-76a80e80-728a-11ea-93d5-fbffce0bd362.png)

**Comment by DSheirer** [comment]
Check that the talkgroup range 1301-1302 doesn't overlap with any other alias talkgroup ranges that you've defined.

When there is overlap between talkgroup ranges, sdrtunk will use the first one that it finds.

**Comment by DSheirer** [comment]
Which part is not working?  Is it not blocking the audio from playback?

**Comment by ah1102** [comment]
Overridden only by the blacklist group that I created to block unknown IDs

![Снимок экрана 2020-03-30 в 13 43 49](https://user-images.githubusercontent.com/58341369/77904211-d8697800-728c-11ea-87a6-810179b8edbe.png)

The same thing happened with another group, which had to be divided into separate IDs.

![Снимок экрана 2020-03-30 в 13 43 30](https://user-images.githubusercontent.com/58341369/77904445-3ac27880-728d-11ea-8f4c-df4b5ef6e57d.png)


> Which part is not working? Is it not blocking the audio from playback?

All IDs in the Talkgroup range are blocked. No audio output when monitoring priority is enabled.

**Comment by DSheirer** [comment]
If you have two or more talkgroup ranges that overlap, the software has no way of knowing which one it should use, so it picks the first one that it finds.

If the first one that it finds is your 0-65535 blacklist, then the call will not be monitored.

If you want to define a talkgroup range 1301 - 1302 to not be part of the blacklist, then you would have to change the 0-65535 blacklist to have two separate talkgroup ranges like this:

0 - 1300
1303 - 65535

This would allow another alias to use the range 1301-1302 and not conflict with your blacklist alias.
