### ISSUE TITLE
Identifier does not get added to event log if SDRtrunk misses the first packet

### ISSUE THREAD

**Issue by ZacharyDuBois** [DSheirer/sdrtrunk#732]
On a P25 Phase II system, if SDRtrunk misses the initial packet (either due to poor reception, etc) the identifier won't be displayed in the event log but the "Now Playing" will display it after it captures a packet with it. Will post example later today.

**Comment by DSheirer** [comment]
Thanks Zachary.  I'll might be able to fix this in the decoder state.

**Comment by DSheirer** [comment]
Update P25P2DecoderState closeCurrentCallEvent to inspect the FROM field of the current call event and inject a FROM value from the identifier collection when the value is missing.
