### ISSUE TITLE
Hackrf fix not working in windows

### ISSUE THREAD

**Issue by 49handyman** [DSheirer/sdrtrunk#735]
moved the sdrtrunk directory
cloned the current master & also tried beta.8

doesnt seem to work on Windows 10 but it worked on linux

let me know if i should try sometime different

thanks for the fix

**Comment by DSheirer** [comment]
@49handyman Have you tried the 0.4.0 release (instead of building it yourself) for Windows to verify that there is an issue?

**Comment by 49handyman** [comment]
that worked thanks.

can you let me know why that might happen on my windows machine. 

i use gradlew clean build if that right

the master has the fix right?

**Comment by DSheirer** [comment]
Yes, the source code master branch is the same.  I doesn't matter which OS you're using.

Make sure the source code is up-to-date.  Are you using git or are you just downloadin and unzipping the entire master branch and then compiling?
