### ISSUE TITLE
P25 Phase 1 Doesn't Show Encrypted Status

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#740]
Phase 1 encrypted audio is being handled correctly, but it doesn't appear that the decoder state is being updated to encrypted and therefore not displaying correctly in the Now Playing window.

**Comment by ryanthomp** [comment]
Ah okay, its odd this department will do dispatch encrypted and unencrypted
randomly the only way I can tell if they’re encrypted is that the status is
“call” but nothing is playing audio wise and I click on it and see
“encrypted” in the log.
