### ISSUE TITLE
Disable Event Logging

### ISSUE THREAD

**Issue by StaRipper** [DSheirer/sdrtrunk#747]
Hello,
Everything is working great here...
Just wanted to **disable** "Event Logs"
Is there a way to do so?

**Comment by DSheirer** [comment]
In the channel configuration, logging tab, uncheck any logging options you've selected.

You can post questions like this in the user forum on Google groups: https://groups.google.com/forum/#!forum/sdrtrunk or on the Discord server at: https://discord.gg/rhsZFAt
