### ISSUE TITLE
Audio Recording Metadata - Add Alias Name Separators for Title Metadata

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#751]
Surround each alias name with quotes and commas to support parsing.

io.github.dsheirer.record.wave.AudioMetadataUtils: LIne 100 change:

FROM:
                for(Alias alias: aliases)
                {
                    sb.append(" ").append(alias.toString());
                }
TO:
                if(!aliases.isEmpty())
                {
                    sb.append("\"").append(Joiner.on("\",\"").join(aliases)).append("\"");
                }

**Comment by jasoveen** [comment]
To get the change to compile I had to add "import com.google.common.base.Joiner;" to the file and escape the double quote characters.
I also added a space at the start to increase readability of the tag.

With these changes I was able to successfully parse the Alias Names for patch calls.

Final change:
if(!aliases.isEmpty())
{
sb.append(" \"").append(Joiner.on("\",\"").join(aliases)).append("\"");
}
