### ISSUE TITLE
Add Broadcastify Calls API Support

### ISSUE THREAD

**Issue by davidmckenzie** [DSheirer/sdrtrunk#757]
https://www.rtl-sdr.com/broadcastify-calls-radio-call-archiving-incentives-for-sdr-software-developers/

> If developers adapt their SDR based application to function as a call ingest platform for Broadcastify Calls, Broadcastify will pay them up to $2,500 for their efforts. Here are the details:

Might be worth a look :)

**Comment by ryanthomp** [comment]
It seems fairly simple given that SDRTrunk already records call segments and sends them in order to Broadcastify, seems like all that would be needed is to change where the data is sent and hook into the Broadcastify Calls API and send in the data that way.

**Comment by DSheirer** [comment]
@davidmckenzie @ryanthomp I've been emailing with Lindsay about this.  He's setup an account for me to develop and test against.  It's in the work hopper.

**Comment by DSheirer** [comment]
API: https://wiki.radioreference.com/index.php/Broadcastify-Calls-API

**Comment by khanfar** [comment]
any useful link how to stream to broadcastify step by step guide ?
