### ISSUE TITLE
Multisite receive single network

### ISSUE THREAD

**Issue by ah1102** [DSheirer/sdrtrunk#761]
I have 5 sites in different areas of my city. Many identifiers in them are duplicated, but there is an identifier that is not heard in others. I would like to include all 5 sites, but there is an unpleasant echo effect.

Is it possible to add the function of obtaining only the 1st identifier and blocking duplicates during multinodal reception?

![Снимок экрана 2020-04-26 в 15 20 24](https://user-images.githubusercontent.com/58341369/80307477-f1087780-87d1-11ea-8bed-9b7883d97a70.png)

**Comment by ah1102** [comment]
#831 solved the problem

**Comment by DSheirer** [comment]
Awesome!  Thanks!
