### ISSUE TITLE
RR Is Currently Unavaliable

### ISSUE THREAD

**Issue by ryanthomp** [DSheirer/sdrtrunk#762]
When I was testing out the RR interface in the fork it worked perfectly now that I downloaded from master I get this error in the playlist editor.

`13:19:06.935 ERROR i.g.d.g.p.r.RadioReferenceEditor - Error retrieving country information from radio reference - Error  [64MB/110MB 58%]`
![image](https://user-images.githubusercontent.com/21696945/80314649-b9dd9a80-87c0-11ea-98f5-56e9ea9c8040.png)

**Comment by ryanthomp** [comment]
Never mind took a couple of restarts and it finally connected

**Comment by fofeResonance** [comment]
Hi!
I'm having the same issue described above. I've tried several times to no avail.

`12:40:13.754 ERROR i.g.d.g.p.r.RadioReferenceEditor - Error retrieving country information from radio reference - Error  [81MB/154MB 52%]`

**Comment by bnmelvin** [comment]
Same issue here ... retries never seem to get to 100% ...

20200810 153257.352 [sdrtrunk pool-1-thread-8] ERROR i.g.d.g.p.r.RadioReferenceEditor - Error retrieving country information from radio reference - Error  [219MB/460MB 47%]
20200810 153303.156 [sdrtrunk pool-1-thread-7] ERROR i.g.d.g.p.r.RadioReferenceEditor - Error retrieving country information from radio reference - Error  [306MB/460MB 66%]
20200810 153311.513 [sdrtrunk pool-1-thread-6] ERROR i.g.d.g.p.r.RadioReferenceEditor - Error retrieving country information from radio reference - Error  [135MB/460MB 29%]
20200810 153315.530 [sdrtrunk pool-1-thread-4] ERROR i.g.d.g.p.r.RadioReferenceEditor - Error retrieving country information from radio reference - Error  [211MB/460MB 45%]
20200810 153403.057 [sdrtrunk pool-1-thread-7] ERROR i.g.d.g.p.r.RadioReferenceEditor - Error retrieving country information from radio reference - Error  [378MB/460MB 82%]
20200810 153406.896 [sdrtrunk pool-1-thread-3] ERROR i.g.d.g.p.r.RadioReferenceEditor - Error retrieving country information from radio reference - Error  [358MB/460MB 77%]
20200810 153411.854 [sdrtrunk pool-1-thread-3] ERROR i.g.d.g.p.r.RadioReferenceEditor - Error retrieving country information from radio reference - Error  [282MB/460MB 61%]
20200810 153415.648 [sdrtrunk pool-1-thread-6] ERROR i.g.d.g.p.r.RadioReferenceEditor - Error retrieving country information from radio reference - Error  [244MB/460MB 53%]
20200810 153419.172 [sdrtrunk pool-1-thread-1] ERROR i.g.d.g.p.r.RadioReferenceEditor - Error retrieving country information from radio reference - Error  [368MB/460MB 80%]
20200810 153422.641 [sdrtrunk pool-1-thread-8] ERROR i.g.d.g.p.r.RadioReferenceEditor - Error retrieving country information from radio reference - Error  [196MB/460MB 42%]

**Comment by DSheirer** [comment]
@fofeResonance and @bnmelvin Can you both confirm that you have a current paid premium subscription to radio reference and that you're running the software on a machine that has good access to the internet?

**Comment by awipslinuxuser** [comment]
Is there any free alternative to sdrtrunk that can decode p25 phase 1&2 besides openear
