### ISSUE TITLE
Playlist Editor - Clone Aliases Issue

### ISSUE THREAD

**Issue by ah1102** [DSheirer/sdrtrunk#766]
I compiled the program from the source code using the latest version of JDK14. Created a new playlist and a new alias

1) The frequency is not displayed on the “Channels - Source” tab, and in the “Channels” there is no column with the site frequency.

![Снимок экрана 2020-04-29 в 18 08 15](https://user-images.githubusercontent.com/58341369/80612868-354f7e00-8a45-11ea-9c2f-8504f949d9ac.png)

2) When cloning an “Alias” with two or more identifiers, not one clone is created, but several.

![Снимок экрана 2020-04-29 в 18 10 37](https://user-images.githubusercontent.com/58341369/80613128-895a6280-8a45-11ea-872f-ac4a8c22dbba.png)

3) Cannot delete more than 1 clone

![Снимок экрана 2020-04-29 в 18 19 24](https://user-images.githubusercontent.com/58341369/80613513-0f76a900-8a46-11ea-94c4-fd3e1ec3b17e.png)

**Comment by ah1102** [comment]
Without these corrections, the program cannot be used. I don’t see the frequency of sites from my playlist. Moreover, the program can overwrite the frequencies stored in the playlist. I already had to restore the playlist. Editing a playlist is also difficult, because when I add a new identifier, I use the clone function. But this does not work correctly. At least for me.

**Comment by DSheirer** [comment]
The frequency column is added.  I'm still working on the alias cloning issue.
