### ISSUE TITLE
Could not target platform: 'Java SE 13' using tool chain: 'JDK 12 (12)'

### ISSUE THREAD

**Issue by Hermite123456** [DSheirer/sdrtrunk#767]
I'm running latest Win10/64. Trying to setup Alpha 5 with clean install, but  get this:

D:\sdrtrunk-master>gradlew.bat clean build
> Task :compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Could not target platform: 'Java SE 13' using tool chain: 'JDK 12 (12)'.

This is my current JRE version:

java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

Any clue what I'm doing wrong?

Tks.

**Comment by ah1102** [comment]
The source says _"Updates gradle wrapper to 6.3. Updates embeded java to JDK 14 for bui ..."_ you need to install JDK14
