### ISSUE TITLE
No status or information displayed for Broadcastify Streaming 0.5.0 a1

### ISSUE THREAD

**Issue by ryanthomp** [DSheirer/sdrtrunk#769]
When streaming to broadcastify in alpha1 there is no queued number no connected status nor is there a streamed number that would normally be in the bar below in 0.4.0 it is all blank.

**Comment by khanfar** [comment]
any useful link how to stream to broadcastify step by step guide ?

**Comment by ryanthomp** [comment]
@khanfar You should refer all questions to the Google Groups [here](https://groups.google.com/forum/#!forum/sdrtrunk)

**Comment by DSheirer** [comment]
Resolved in #773
