### ISSUE TITLE
identifier may freeze

### ISSUE THREAD

**Issue by ah1102** [DSheirer/sdrtrunk#790]
I noticed that the identifier may freeze in the left or right audio channel. But if a new identifier is displayed on this channel, the old one will be reset and the program will continue to work in normal mode.

![Снимок экрана 2020-05-03 в 23 12 02](https://user-images.githubusercontent.com/58341369/80924862-3f9ab080-8d94-11ea-93f6-4517fa07c66d.png)

**Comment by DSheirer** [comment]
Closing.  Resolved.
