### ISSUE TITLE
not clone ID and Priority values 0.5.0a1

### ISSUE THREAD

**Issue by ah1102** [DSheirer/sdrtrunk#792]
Cloning does not clone ID and Priority values

![Снимок экрана 2020-05-04 в 15 08 35](https://user-images.githubusercontent.com/58341369/80964374-6949eb00-8e19-11ea-9472-1d9e3fc82eab.png)

**Comment by DSheirer** [comment]
Those specific pieces were causing issues when cloning an alias so I decided to exclude them from the cloning process.  Right now, cloning does not include alias identifiers or alias actions.  Likewise, it does not include monitor priority or recording.

**Comment by ah1102** [comment]
Too bad ((I hope in the future you will be able to configure this feature.
