### ISSUE TITLE
Icons not showing correctly in alias list.

### ISSUE THREAD

**Issue by LordDonkey** [DSheirer/sdrtrunk#800]
Alias icons aren't showing in the table, screenshot attached. Also noticed a delay when clicking on the icons menu drop down. It takes a few seconds to open the drop down menu. This is with the latest commit 2723926.

![image](https://user-images.githubusercontent.com/52051804/81210928-983e9900-8fa0-11ea-8176-b1b45bbd3955.png)

**Comment by ah1102** [comment]
It would be nice if the user icons are loaded into the main folder with the program settings, where playlists and other materials are stored.
