### ISSUE TITLE
Stopping Channel Causes Full Model Reset in ChannelMetadataModel

### ISSUE THREAD

**Issue by ah1102** [DSheirer/sdrtrunk#801]
When you right-click in the "Now Playing" window and select the "Disable" menu, for example, one of the two sites, such a crash appears in "Allias" and the color "CONTROL" of the remaining site disappears.

The same will happen if one of the two sites is turned off via the "Playlist editor".

![Снимок экрана 2020-05-06 в 23 56 27](https://user-images.githubusercontent.com/58341369/81227520-3ceac600-8ff5-11ea-990f-ee1ac5ff7e1a.png)

![Снимок экрана 2020-05-06 в 23 48 58](https://user-images.githubusercontent.com/58341369/81227322-e8474b00-8ff4-11ea-92e3-5f324e72ff12.png)

![Снимок экрана 2020-05-06 в 23 55 12](https://user-images.githubusercontent.com/58341369/81227411-1036ae80-8ff5-11ea-85e2-ea2b94dbbe81.png)

And something strange happened when two sites were launched.

![Снимок экрана 2020-05-07 в 00 01 05](https://user-images.githubusercontent.com/58341369/81227993-f8135f00-8ff5-11ea-910f-ac0dd921a398.png)

**Comment by DSheirer** [comment]
Note: there's a possibility that the context menu actions used here are invoking FX actions that are not on the FX thread.

**Comment by DSheirer** [comment]
This was a difficult bug to track down.  When the playlist editor issues a stop channel to the channel processing manager, which in turn removes the channel metadata from the channel metadata model, the model fires a table row delete notification for row with index of -1.  This is apparently a sentinel to JTable to fully recreate all of the table columns from the model, which causes the JTable to lose all customer table cell renderers.  I added a check to ensure that we never issue a fireTableRowDeleted() for a table row with index -1.
