### ISSUE TITLE
Changing settings in playlist editor causes playing issues

### ISSUE THREAD

**Issue by ryanthomp** [DSheirer/sdrtrunk#806]
When I change settings in the playlist editor this happens in the now playing section

![image](https://user-images.githubusercontent.com/21696945/81463521-24f77b80-9188-11ea-9b85-00f26bcd4eae.png)

**Comment by DSheirer** [comment]
Ryan, do you remember which setting you were changing that caused this?

**Comment by ryanthomp** [comment]
It happens alor for various settings but specifically when this happened I
played and stopped a passport channel.

**Comment by DSheirer** [comment]
Perfect.  There's another user that's reported (I think) the same issue.  I'll get it fixed this morning.

**Comment by ah1102** [comment]
Yes, the same problem. This happens when you disconnect and enable a channel from a playlist.

**Comment by DSheirer** [comment]
Closing issue.  Duplicate to #801
