### ISSUE TITLE
Airspy Mini Spectral Issues With 3.0 MHz Sample Rate

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#815]
User reported issue decoding P25 control channel when using airspy mini at 3.0 MHz sample rate.  Screen shot of spectral display reflected very wide filtering drop off across the right-most 25% of the spectral display.  The poor decodes were happening when the decode channel frequency landed in this region.

Investigate if this is an issue with the airspy mini, or if sdrtrunk is not configuring something correctly fo  r the 3.0 MHz sample rate setting on the mini.

**Comment by aaomidi** [comment]
Going to be getting an airspy mini, so let me know if i can help with any investigations

**Comment by DSheirer** [comment]
Change airspy tuner controller to use the following sample rates and usable spectrum settings:
10 MHz - 90%
2.5 MHz - 60%
6 MHz - 83%
3 MHz - 66%
