### ISSUE TITLE
Cannot add icon in Icon Manager

### ISSUE THREAD

**Issue by hans109h** [DSheirer/sdrtrunk#82]
In v0.3.0.alpha1 I can not add icons using the icon manager.  I click new, then select a file, add a name, but then when I click save nothing happens.  No errors to report in the log.

**Comment by hans109h** [comment]
UPDATE:
I was able to add new icons, however they aren't available until the next time I restart the application.

**Comment by DSheirer** [comment]
This should be an easy fix.  I'll work on it shortly.
