### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by sl0sh** [DSheirer/sdrtrunk#825]
the alias instructions wiki it doesnt even use wild cards it uses ranges now.. why is this like that? why is it incorrect?

**Comment by DSheirer** [comment]
@sl0sh The software is constantly evolving and it's difficult to keep the user documentation up to date with these changes.  

The correct user manual for version 0.5.0 for aliases is located here: https://github.com/DSheirer/sdrtrunk/wiki/Playlist-Editor

Also, please use the User Support forum for questions like these: https://groups.google.com/forum/#!forum/sdrtrunk

Issues is for reporting bugs and feature requests.

cheers,
Denny
