### ISSUE TITLE
No Audio on Any OS

### ISSUE THREAD

**Issue by sutterlaird** [DSheirer/sdrtrunk#841]
Hello all,

I know I must be doing something wrong but I just can't figure out what it is. I have installed sdrtrunk and JMBE on my MacBook Pro running macOS Mojave, an Ubuntu 20.04 VM in VirtualBox, and a Windows 10 VM in Parallels Desktop but I have not been able to get audio to work on any OS. I have the control channel set up, I see Messages and Events coming, and traffic channels are being created, but no sound is generated and the Audio Panel just shows "------" for both channels. Terminal confirms that JMBE is being loaded correctly. I've tried sdrtrunk 0.5 and 0.4 and JMBE 1.0.6 and 1.0.7 on all three platforms. I've attached screenshots of my configuration, do you see what I am missing?

Thank you,
Sutter

![Screen Shot 2020-06-03 at 1 18 51 AM](https://user-images.githubusercontent.com/42818540/83614337-e9a75d00-a539-11ea-9c86-274dfa29ff7a.png)
![20200603_011632_screen_capture](https://user-images.githubusercontent.com/42818540/83614188-b8c72800-a539-11ea-8f13-0b93df001302.png)
![20200603_011719_screen_capture](https://user-images.githubusercontent.com/42818540/83614191-b9f85500-a539-11ea-8aa5-0fd2d1f7a2d5.png)
![20200603_011804_screen_capture](https://user-images.githubusercontent.com/42818540/83614196-bbc21880-a539-11ea-8eb9-f4e5690ec9a5.png)

**Comment by DSheirer** [comment]
It looks like you're using the wrong control channel frequency.  Radio reference has it listed as 770.34375.

Change the channel configuration frequency from 770.25 to 770.34375 and then adjust the tuner PPM so that the control channel signal that you're currently decoding aligns with the frequency readout of 770.34375.

In your screen shot, you can see where sdrtrunk thinks the traffic channel should be, and then you can see the actual signal that sdrtrunk should be decoding is about 9.375 kHz off.  Once you adjust the tuner PPM, everything should line up and decode properly.

**Comment by DSheirer** [comment]
When a traffic channel is allocated, click on the traffic channel row in the now playing window and make sure you're seeing decoded messages.  If you were to click on the traffic channel as it is configured right now, you're probably seeing nothing but sync loss messages, indicating that the traffic channel is not decoding correctly.

**Comment by sutterlaird** [comment]
Thank you very much, that was what I was missing. I am now hearing some traffic. I dialed in the PPM to get the frequency as close as I could but I'm still seeing a lot of sync loss messages. My SDR dongle is an early generic model, would I have better luck with a better unit, like an authentic RTL-SDR unit?

**Comment by DSheirer** [comment]
The earlier screenshots look like your gain may be too high.  The generic dongles work ok once you get them adjusted

**Comment by sutterlaird** [comment]
I'll try experimenting with the gain. Thank you again!
