### ISSUE TITLE
Imported channels from RR are offset in spectrum monitor

### ISSUE THREAD

**Issue by rstevens011** [DSheirer/sdrtrunk#877]
sdrtrunk v0.5.0-alpha2 w/ JMBE 1.0.7b

This could be me being a noob here, but I imported KCERS (A SmartZone Type II system in the Seattle, WA area) and set it up with [Site 1](https://www.radioreference.com/apps/db/?siteId=733) and the spectrum monitor looks weird to me:

![20200628_005157_screen_capture](https://user-images.githubusercontent.com/15152527/85941930-e5712400-b8da-11ea-8bbb-7b21e9a74aa2.png)

LCN 8 (On 853.175) is the primary control channel for the site in question, but the width of the channel is not wide enough to "encompass" (for lack of a better term) the entire channel and seem to be offset to some degree.  This appears to also happen on the other channels as well.  I suspect that is why I am getting all SYNC LOSS errors:

![20200628_005304_screen_capture](https://user-images.githubusercontent.com/15152527/85941985-3e40bc80-b8db-11ea-91b4-60d9e355aff2.png)

Is this expected?  See [this gist](https://gist.github.com/rstevens011/63cd116d43794232d027201a71625f5a) for the playlist file.

**Comment by DSheirer** [comment]
Go to the tuners tab, select your tuner and then use the PPM adjustment to align the signals to the frequency readout.

Once you've updated the PPM, the signals should start decoding for you.

**Comment by rstevens011** [comment]
@DSheirer thanks for this bit.  I do indeed now have the channels aligned to the frequency/waterfall readout.  When configured with all of the channels listed in the radio reference link above, I do see messages other than SYNC LOSS, so that is a start.  

I however am not getting any audio at all.  I was able to verify using gqrx that I am able to pick up the primary control channel successfully.  I therefore limited the channel config in the playlist file to just the primary and alt control channels thinking that only the control channels should be imported as channels in the config:

<img width="1112" alt="Screen Shot 2020-06-28 at 2 06 03 PM PDT" src="https://user-images.githubusercontent.com/15152527/85958198-86e28f00-b948-11ea-94db-8fb32d9c6ef9.png">

I messed around with the max traffic channels and switched from C4FM and LSM and still no luck.  I also added a second tuner as well:

![20200628_140724_screen_capture](https://user-images.githubusercontent.com/15152527/85958222-c4471c80-b948-11ea-99f2-e0a5ec1bde8f.png)

![20200628_141517_screen_capture](https://user-images.githubusercontent.com/15152527/85958356-d7a6b780-b949-11ea-830b-a65366f23000.png)

Based on the channel config screenshot above and it being in auto-play mode, I was expecting at least one of these tuners tuned to the control channel on 853.175 but neither are.  I am still getting SYNC LOSS messages repeatedly.  Reading past issues people have suggested setting up a second tuner (despite all of the of these channels being fairly close together within 20Mhz), however with a second tuner,  I am also not picking up any audio either.

**Comment by DSheirer** [comment]
The system that you're trying to monitor is a hybrid Motorola SmartZone system with P25 CAI traffic channels.

sdrtrunk does not decode Motorola SmartZone control channels.  It does however decode the P25 traffic channels.  So, don't setup a channel configuration for the control channel.  Setup 1 channel configuration for each of the traffic channels.

When you import this system from radio reference, the playlist editor will setup this sytem automatically for you and it will create a P25 channel configuration for each of the traffic channels.
