### ISSUE TITLE
Traffic Channel Managers (P25, DMR, MPT1327)

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#880]
Update traffic channel manager logging to make the wording "MAX TRAFFIC CHANNELS EXCEEDED" be appended to the event description instead of replacing the event description.

**Comment by CurtisHx** [comment]
This looks pretty simple.  I can take a stab at implementing it.

**Comment by DSheirer** [comment]
Thanks!

**Comment by ah1102** [comment]
If you implement DMR soon, that will be great! At the moment, in order to listen to fire services and radio amateurs in this mode, I need to run a bundle from CubicSDR + DSD. The implementation of DMR in one SDRTrunk program is undoubtedly amazing!
