### ISSUE TITLE
V0.5.0-Alpha2 Broadcastify - No Audio Streaming

### ISSUE THREAD

**Issue by WD433** [DSheirer/sdrtrunk#883]
Earlier today, I got my Broadcastify stream setup and shows connected, however, no audio is streaming through when listening to feed. So I must be missing a simple step. 

I got all the alias selected to stream under the Broadcastify stream and ensured all the identifiers are set up correctly in hexadecimal. 

Checked the streaming status and did not see anything out of the ordinary that would cause this problem. 

Please let me know If I am missing anything in my setup.

**Comment by DSheirer** [comment]
You can post user support questions like these in the google groups email list, or you can post them on the Discord channel. I'll help you to get the situation resolved and then we can close this issue.

The next thing to check is the channel configuration.  Make sure it includes the Alias List Name that you used for each of the aliases that you've selected to stream.
