### ISSUE TITLE
Change Embedded Java from 14 to 13 

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#899]
Users are reporting out of memory errors with version 0.5.0 alpha 2 and 3 where previous 0.5.0 alpha 1 release was performing ok.

Consider rolling back the embedded JDK version from 14 back to 13 to see if this is what is causing the issue.

**Comment by NoahWL** [comment]
I've been getting this after leaving SDRTrunk run for a day or so.  I'll switch to Java 13 on the machine that runs it and see if I still get the issue.

Using 2 RTL-SDR dongles monitoring a very active P25 phase 2 system and streaming to a local Icecast 2.4 server.
