### ISSUE TITLE
Skip frequency limit?

### ISSUE THREAD

**Issue by thediex** [DSheirer/sdrtrunk#906]
I want to enter a frequency 5146.0000 Mhz, but it tells me that it has a limit. It turns out that with other software I can reach this frequency and it effectively delivers the radio signal that I want to monitor. How can I skip this restriction that is in the program that says it has a limit of 1782.0 Mhz

**Comment by DSheirer** [comment]
You can ask user support questions like these in the user support forum.  The issue tracker is for reporting bugs and feature requests.

The tuner frequency limit is hard-coded in the software.  The source code is available if you want to change and compile a separate version.  The class is R820TTunerController and the value that constrains the upper frequency limit is the MAX_FREQUENCY constant.
