### ISSUE TITLE
(0.5.0 DMR) DMR protocol missing from Playlist Editor

### ISSUE THREAD

**Issue by GTR8000** [DSheirer/sdrtrunk#927]
The DMR protocol is missing from the Add Identifier drop-down in the Playlist Editor Aliases section.

![image](https://user-images.githubusercontent.com/21224200/92298122-acc17c80-ef13-11ea-8767-70d1f9d68a27.png)

**Comment by ah1102** [comment]
Where did you get dmr version 0.5.0 ?

**Comment by ah1102** [comment]
I join the question

**Comment by DSheirer** [comment]
Resolved with latest commit.
