### ISSUE TITLE
Error init of VM - 0.5.0 alpha 3 - win7 

### ISSUE THREAD

**Issue by ah1102** [DSheirer/sdrtrunk#928]
When I try to start the application, an error is displayed via sdr-trunk.bat:

```
ERROR OCCURRED DURING INITIALIZATION OF VM.
Failed setting boot class path.
```

The release of the program is used. Windows 7 x64.

**Comment by DSheirer** [comment]
Make sure you don't have the program running from a directory that is nested too deeply like:

C:\This\Is\A\Reeeeeally\Long\Path\To\where\the\program\is\running\sdrtrunk-release\bin\sdrtrunk.bat.

**Comment by ah1102** [comment]
Yes thank you! It works. I have a localized Windows. Perhaps the path was not indicated in English. But the folder with the sdrtrunk program was on a long journey. As you wrote. Moved to c: //
