### ISSUE TITLE
Failed to compile DMR on Windows10

### ISSUE THREAD

**Issue by Hermite123456** [DSheirer/sdrtrunk#929]
Not sure what I am doing wrong...

**D:\sdrtrunk-5-dmr-decoder-part2>gradlew.bat clean build

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.UnsupportedClassVersionError: org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0**

java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
Java_Home: C:\Program Files\Java\jdk1.8.0_261

Path_To_Jfx: C:\Users\blablablabla\openjfx-11.0.2_windows-x64_bin-sdk\javafx-sdk-11.0.2\lib

![image](https://user-images.githubusercontent.com/54645050/92507823-95b1b180-f1d5-11ea-81fa-849fc7a2ebe0.png)

**Comment by Hermite123456** [comment]
Please IGNORE, Problem solved

**Comment by Paulo-D2000** [comment]
how did you fixed it ?
