### ISSUE TITLE
TG in audio channel is not always cleared

### ISSUE THREAD

**Issue by ah1102** [DSheirer/sdrtrunk#934]
The last call in the audio channel line is not always dropped

![Screenshot 2020-09-19 at 14 06 11](https://user-images.githubusercontent.com/58341369/93665758-c91bf800-fa81-11ea-93ba-84a36d866777.png)

**Comment by GTR8000** [comment]
I've also seen this issue, but only with the latest build of the DMR branch.

**Comment by ah1102** [comment]
P25 has the same problem. This does not affect the work in any way, just a cosmetic nuance.

**Comment by DSheirer** [comment]
Resolved.  Closing.
