### ISSUE TITLE
HackRF amplifier

### ISSUE THREAD

**Issue by ah1102** [DSheirer/sdrtrunk#943]
In what position is the "amplifier" button active?

In such:
![Снимок экрана 2020-09-28 в 15 46 59](https://user-images.githubusercontent.com/58341369/94434820-029be400-01a3-11eb-8ebd-25c54c7227ee.png)

or this:
![Снимок экрана 2020-09-28 в 15 51 54](https://user-images.githubusercontent.com/58341369/94434840-0a5b8880-01a3-11eb-99db-f23ecf1bc80d.png)

In the latter case, when the button is active, the signal levels, on the contrary, fall.

**Comment by TheKing505** [comment]
`src/main/resources/52-airspy.rules;src/main/resources/__````javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }:~/unrealircd$ ./unrealircd rehash
Rehashing Unreal Demon505@outlook.com~/unrealircd$ tail logs/ircd.log
[Sun Jun 28 15:03:00 2015] - TIME SYNCH: IRCd clock succesfully synchronized to known good time source.
[Sun Jun 28 15:27:42 2015] - Loading IRCd configuration ..
[Sun Jun 28 15:27:42 2015] - Configuration loaded without any problems ..
}
```15:31:28] -irc.test.net- *** Notice -- OperX is rehashing server config file
[15:31:28] -irc.test.net- *** Notice -- Loading IRCd configuration ..
[15:31:28] -irc.test.net- *** Notice -- Configuration loaded without any problems ..

**Comment by ah1102** [comment]
There is an assumption that the amplifier burned out in my device and the program is not to blame.
