### ISSUE TITLE
DMR Call Events Not Showing in Now Playing Window

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#959]
See: https://groups.google.com/forum/?oldui=1#!topic/sdrtrunk/1EcAeiu1Lec

The call events for the channel are appearing in the event window, but not showing in the now playing window.  This appears to be  con+ system.

**Comment by mikerobertsn** [comment]
I can’t hear dmr channels either which I can hear using dsd.

**Comment by radar223** [comment]
it seems like traffic only comes in the now playing window and records if traffic is on the control channel frequency only. Also hearing traffic that comes in that's not in my alias list.  yes this is a con+ system
