### ISSUE TITLE
Low audio quality when laptop unplugged

### ISSUE THREAD

**Issue by JoeyAbsi** [DSheirer/sdrtrunk#971]
When a laptop is unplugged from its power source, the audio quality becomes distorted.
This issue happened on all laptop I tested and it seems it is caused by the software.
I have the latest version of SDRTrunk and JMBE.

**Comment by GTR8000** [comment]
Sounds like the CPU is being throttled down when the laptop is running on battery. This is pretty typical, and not a flaw in the software. Adjust your power settings so that the performance is not degraded on battery.
